bazel-contrib/rules_python

- examples/boto/BUILD
WIP toward fixing #98. AFAIK creating a PR is necessary so I can trigger our CI to run.
> Fix boto_test

- WORKSPACE
Remaining issues are caused by subpar
Progress towards #134
> Update sass and skydoc dependencies

- WORKSPACE
Tested:
`bazel-0.21 test //... --all_incompatible_changes`
Fixes #134
> Update subpar dependency

- proposals/2018-10-25-selecting-between-python-2-and-3.md
- proposals/README.md
This is an overdue formality at this point. The proposal is mostly implemented.
> Mark Py 2/3 proposal accepted

- proposals/2019-02-12-design-for-a-python-toolchain.md
- proposals/README.md
mrovner and nlopezgi LGTM'd in bazelbuild/bazel#7375, and you made a few comments that I have addressed.
> Mark Python toolchain proposal as formally accepted

- examples/boto/requirements.txt
Forgot to push a change from my previous PR (#206).
> Refine the fix for examples breakage

- .bazelci/presubmit.yml
This PR uses two yaml mechanisms (anchors and the Merge Key Language-Independent Type) to avoid duplicate code.
> Remove duplicate code from presubmit config

- .bazelci/presubmit.yml
Expecting CI to fail if I did this right, then we can modify this PR to include the fix.
> Expand CI coverage to detect #225

- internal_deps.bzl
- internal_setup.bzl
> remove unneeded references to sass and skydoc.

- BUILD
- WORKSPACE
- distro/BUILD
- internal_deps.bzl
- internal_setup.bzl
- python/BUILD
- python/constraints/BUILD
- python/runfiles/BUILD
- tools/BUILD
- version.bzl
- set up for release 0.0.1
- update to Federation pre-release
> Use rules_pkg to create distributions

- .bazelci/presubmit.yml
- BUILD
- WORKSPACE
- distro/BUILD
- docs/BUILD
- examples/extras/BUILD
- examples/helloworld/BUILD
- experimental/examples/wheel/BUILD
- experimental/python/wheel.bzl
- internal_deps.bzl
- internal_setup.bzl
- packaging/BUILD
- python/BUILD
- python/defs.bzl
- python/pip.bzl
- python/private/reexports.bzl
- python/python.bzl
- python/repositories.bzl
- python/runfiles/BUILD
- python/whl.bzl
- tools/BUILD
This PR enables all buildifier checks on presubmit, plus it migrates the repo to fix violations.
> Enable buildifier presubmit check

- README.md
https://buildkite.com/bazel/rules-python-plus-bazelisk-migrate
> Add badge for incompatible flag pipeline

- docs/pip.md
- docs/whl.md
- python/pip.bzl
- python/whl.bzl
Fix formatting of docstrings and regenerate the pages. Fixes #250.
> Fix packaging rules documentation generation

- version.bzl
Just realised I [release `0.0.2` at latest `master`](https://github.com/bazelbuild/rules_python/releases) but neglected to bump this file beforehand 😖 .
> Update version in version.bzl

- README.md
> README update (related to 0.1.0 release)

- python/pip_install/repositories.bzl
Updates the versions of the PyPI dependencies that are used in the packaging rules.
pip: 19.3.1 -> 20.3.3 [Changelog](https://pip.pypa.io/en/stable/news/)
pkginfo: 1.5.0.1 -> 1.6.1 [Changelog](https://bazaar.launchpad.net/~tseaver/pkginfo/trunk/view/head:/CHANGES.txt)
setuptools: 42.0.2 -> 44.1.0 [Changelog](https://setuptools.readthedocs.io/en/latest/history.html)
wheel: 0.33.6 -> 0.36.1 [Changelog](https://wheel.readthedocs.io/en/stable/news.html)
Mostly adds Python 3.9 support, removes Python 3.4 support, adds macos Big Sur support and includes general bug fixes and improvements.
`setuptools` has been upgraded to the most recent version that supports Python 2.7. …
> Update pip_install dependencies

- tools/bazel_integration_test/test_runner.py
🧹🧹...
Just addressing  a small `TODO`.
> Remove TODO now that rules_python 0.0.3 (and 0.1.0) have been released

- README.md
> Remove wording incorrectly suggesting python2 was supported by pip_install

- python/pip_install/repositories.bzl
> Update to more recent pip version 21.0 -> 21.1

- .pre-commit-config.yaml
Fixed broken pre-commit hook
Issue Number: https://github.com/bazelbuild/rules_python/pull/583
In https://github.com/bazelbuild/rules_python/pull/583, the commit hooks were added but they were fighting each other. This change fixes it so they don't both always fail.
> Fix broken pre-commit hook

- README.md
> Fix buildozer command for substituting deps

- examples/pip_install/.gitignore
- examples/pip_parse/.gitignore
> Added `.gitignore` files to example directories

- python/pip_install/pip_repository.bzl
- tools/bazel_integration_test/bazel_integration_test.bzl
> Fixed buildifier defects

- .gitignore
- examples/build_file_generation/BUILD
- examples/build_file_generation/WORKSPACE
- examples/build_file_generation/__init__.py
- examples/build_file_generation/__main__.py
- examples/build_file_generation/gazelle_python.yaml
- gazelle/README.md
- gazelle/manifest/defs.bzl
- gazelle/manifest/generate/generate.go
- gazelle/manifest/manifest.go
- gazelle/pythonconfig/BUILD.bazel
- gazelle/pythonconfig/pythonconfig.go
- gazelle/resolve.go
- gazelle/testdata/monorepo/coarse_grained/packages_mapping.json
- gazelle/testdata/monorepo/gazelle_python.yaml
- gazelle/testdata/monorepo/three/BUILD.out
- gazelle/testdata/monorepo/three/__init__.py
- gazelle/testdata/monorepo/three/gazelle_python.yaml
Gazelle doesn't support pip_parse incremental.
Gazelle supports pip_parse incremental.
> feat: support pip_parse in Gazelle

- examples/pip_repository_annotations/WORKSPACE
- examples/relative_requirements/WORKSPACE
- python/pip_install/repositories.bzl
- tests/pip_repository_entry_points/WORKSPACE
The current pins of dependencies do not support python3.10. Now that `rules_python` can provide it's own toolchains, it feels like updating these dependencies is safer to do at this time.
Various packages were updated to support python3.10 as well as pick up some bug fixes and security patches.
> Updated `pip`, `pkginfo`, `setuptools`, and `wheel`.

- gazelle/README.md
> docs fix
Use a permalink instead of relative file path
> Fix example link in gazelle readme

- python/repositories.bzl
If the attempt to build `zstd` locally fails, the error is hidden and somewhat non-obvious (it results in the tar extract failing). This can happen if, e.g., `make` is not installed on the local system.
If the `make` command fails, prints the `stderr` of that make command to the console.
> Check return code of zstd make

- README.md
Issue Number: https://github.com/bazelbuild/rules_python/issues/691
> Add caveat about python_register_toolchain's hermeticty to README

- python/repositories.bzl
- python/versions.bzl
Using python packages with C modules, e.g. numpy, would fail when using
the "static" toolchain. See 
Issue Number: indygreg/python-build-standalone#124
When using the "shared" toolchain, importing numpy is successful
> Use "shared" msvc hermetic toolchain

- python/BUILD
Some `bzl` source files were missing from `@rules_python//python:bzl`, leading to stardoc errors.
This PR fixes issues related to missing sources in the `@rules_python//python:bzl` filegroup.
> Fixed missing bzl sources from bzl filegroup

- python/pip_install/extract_wheels/lib/bazel.py
**Issue Number: #721**
Packages such as https://github.com/google/etils/blob/main/pyproject.toml can be installed with `rules_python`.
> Fix #721. Remove self-link dependency pulled in sometimes by extras

- python/pip_install/extract_wheels/parse_requirements_to_bzl.py
- python/pip_install/extract_wheels/parse_requirements_to_bzl_test.py
Issue Number: https://github.com/bazelbuild/rules_python/issues/742
> Fix for `requirements_lock` with PEP440 direct references

- python/pip_install/repositories.bzl
- python/pip_install/requirements.bzl
Update pip-tools to 6.8.0
[Changelog](https://github.com/jazzband/pip-tools/releases)
> pip-tools: 6.6.2 -> 6.8.0

- python/private/toolchains_repo.bzl
- [ x ] Bugfix
Issue Number: #704 
Not sure if people are relying on the exec_compatible_with also being set.
> exec_compatible_with -> target_compatible_with #704

- python/repositories.bzl
Applies @f0rmiga's [suggestion](https://github.com/bazelbuild/rules_python/pull/758#discussion_r932415910) to simplify glob pattern to exclude static libraries from the hermetic Python toolchain.
> Simplify glob pattern to exclude static libraries

- python/repositories.bzl
The python repository interpreter target is different for each platform
Adds a consitent `:python` target that symlinks to the interpreter.
> Add a consistent `python` interpreter symlink

- python/packaging.bzl
The progress message for `py_wheel` is pretty generic and it makes logs less useful.
This change adds the label to the progress message so developers can quickly identify what's being built.
> Added label to py_wheel progress message.

- python/pip_install/pip_repository.bzl
> Use json.encode(<struct>)

- .bazelci/presubmit.yml
- WORKSPACE
- examples/wheel/BUILD
- examples/wheel/private/BUILD
- examples/wheel/private/directory_writer.py
- examples/wheel/private/wheel_utils.bzl
- examples/wheel/wheel_test.py
Issue Number: closes https://github.com/bazelbuild/rules_python/issues/521
> Add CI job for RBE.

- .bazelci/presubmit.yml
- python/repositories.bzl
Fixes https://github.com/bazelbuild/rules_python/issues/827.
> fix: re-enable python_3_8_10_x86_64-apple-darwin_test

- examples/build_file_generation/WORKSPACE
Bumping the version of Gazelle in the WORKSPACE file.
Both of the above are not applicable.
Updating the version of Gazelle that is used in the example.
We are using an old version
We are using the current version.
> Updating Gazelle version in example

- examples/BUILD
- internal_setup.bzl
- tools/bazel_integration_test/bazel_integration_test.bzl
- tools/bazel_integration_test/test_runner.py
- version.bzl
The existing bzlmod example does not support the latest version of Bazel.
Bzlmod example uses a prerelease version of Bazel 6 and properly overrides the module path during integration testing.
> Update bzlmod example to use latest Bazel release 

- .github/CODEOWNERS
I'm the original owner of the toolchains.
> chore: add f0rmiga as codeowner for toolchains

- .bcr/config.yml
Confirmed Thulio to be the releaser for BCR entries.
> Setup fixed releaser for Publish to BCR app

- python/repositories.bzl
The libpython target does not have an associated interface_library attribute so it cannot be linked with on windows.
Specify interface_library
> Expose python3n.lib as libpython's interface_library

- gazelle/manifest/test/test.go
It was kind of ambiguous before about where the user should look to find instructions on how to resolve the issue.
> chore(gazelle): clarify a particular failure message

- python/pip_install/tools/wheel_installer/wheel_installer.py
- python/pip_install/tools/wheel_installer/wheel_installer_test.py
The `incremental_dir` parameter is a confusing name. There are 2 unused private functions.
`incremental_dir` renamed to `installation_dir` to be a more descriptive name. The 2 unused functions are removed.
> Refactor poor naming and unused code in wheel_installer

- python/versions.bzl
- [?] Tests for the changes have been added (for bug fixes / features)
- [?] Docs have been added / updated (for bug fixes / features)
Add new entries to `versions.bzl`.
Python 3.11 has been out for a while but unsupported by the upstream `python-build-standalone` until recently.
Issue Number: Fixes #866
3.11 can now be targeted by `python_register_toolchains`.
> Add new Python versions including 3.11

- .github/workflows/release.yml
See https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
> fix(release): use correct GH workflows syntax

- python/repositories.bzl
#907 ended up accidentally adding excludes to the includes
> Fix glob includes/exclues

- python/pip_install/requirements.bzl
:requirements_test would previously fail if sandboxing was enabled.
> Add requires-network to pip requirements update.

- DEVELOPING.md
The mention in the release config isn't easily found and I want to make
sure there is some reference for how to manage the account.
> Document the pypi user and how to manage it.

- examples/build_file_generation/gazelle_python.yaml
This header was added in #1030 and since this file is generate we should potentially remove it.
Noticed whilst working on #965.
Regenerate the file using `bazel run //:gazelle_python_manifest.update` , which removes the header. Not sure if we should have a test for it.
> chore: regenerate gazelle_python.yaml manifest

- addlicense.sh
Remembering the whole dance of commands and tools is hard, so put it in a script.
Work towards #916
> Add a script to add missing license headers

- python/versions.bzl
> feat: add Python 3.8.16

- gazelle/README.md
> docs: Add starlark directive to code snippet

- examples/build_file_generation/README.md
This PR updates outdated README.md of example.
Closes #1160
> fix: `example/build_file_generation/README.md`

- WORKSPACE
- python/versions.bzl
This PR bumps mappings to latest version. 
Adding changes in a separate PR as discussed [here](https://github.com/bazelbuild/rules_python/pull/1352#pullrequestreview-1565600824).
cc @chrislovecnm
> feat: Update MINOR_MAPPING to latest version

- .github/PULL_REQUEST_TEMPLATE.md
Now that we have a changelog, add a reminder to update it as part of PRs.
> docs: add update changelog as part of pull request instructions

- CHANGELOG.md
This is to prepare for the 0.25.0 release.
> Update changelog for 0.25.0

- CHANGELOG.md
These patch level bumps were done in #1370 and are part of the 0.25.0 release.
> doc: Note Python version changes in CHANGELOG

- CHANGELOG.md
- python/versions.bzl
Towards #1396, defaults will be bumped in a separate PR.
> feat: add new Python toolchain versions

- CHANGELOG.md
- WORKSPACE
- python/versions.bzl
Updates versions:
* 3.8.15  -> 3.8.18
* 3.11.4  -> 3.11.6
Adds versions: 3.8.18, 3.11.6, 3.12.0
Fixes #1396
> chore: add new Python toolchains from indygreg

- gazelle/README.md
Remove incompatible_generate_aliases from docs as its no longer required.
> docs(gazelle): Update README.md for gazelle

- README.md
> docs: Fix URL in README.md

- python/private/coverage_deps.bzl
> docs: Fix typo in comment

- CHANGELOG.md
- python/private/py_wheel.bzl
- tools/wheelmaker.py
> chore!: switch py_wheel flags to True to start enforcing PEP440

- MODULE.bazel
Upgrade bazel_features to 1.1.1 to pick up a [fix](https://github.com/bazel-contrib/bazel_features/pull/26)
> fix: Upgrade bazel_features to 1.1.1

- CHANGELOG.md
This is to prepare for the 0.27.0 release
> release: update changelog for 0.27.0 release

- CHANGELOG.md
Updates the changelog headers and links for the 0.29.0 release
> chore: update changelog for 0.29.0 release

- CHANGELOG.md
Add the missing changelog from PR #1784.
> docs(changelog) Update changelog from PR #1784

- CHANGELOG.md
Updates release notes for 0.32.0
> chore: release notes for 0.32.0

- CHANGELOG.md
The target name and value were both incorrect.
> docs: fix doc for how to use new bootstrap impl

- python/private/whl_target_platforms.bzl
- tests/private/whl_target_platforms/select_whl_tests.bzl
Remove dead code only used in tests.
> chore: remove dead code from whl_target_platforms

- docs/sphinx/requirements.txt
Closes #1984
Closes #1985
Closes #2012
> chore: bump sphinxdocs deps

- CHANGELOG.md
- DEVELOPING.md
- WORKSPACE
- python/private/coverage_deps.bzl
- python/versions.bzl
- tools/private/update_deps/update_coverage_deps.py
Description:
- Added python 3.13.0 toolchain
- Updated other versions in the toolchain
- Bumped coverage version to 7.6.1
- Updated CHANGELOG.md
> feat(toolchain): add python 3.13.0, updated other versions and bumped coverage to 7.6.1

- CHANGELOG.md
Update the changelog for 0.37.0
> chore: update changelog for 0.37.0

- CHANGELOG.md
Add new version links and headers
> chore: update changelog for 0.40.0

- CHANGELOG.md
Update headers and version links in CHANGELOG.md for 1.1.0 release
> chore: update changelog for 1.1.0

- CHANGELOG.md
- docs/api/rules_python/python/config_settings/index.md
- docs/environment-variables.md
- docs/toolchains.md
- python/features.bzl
- python/private/local_runtime_toolchains_repo.bzl
- python/private/py_info.bzl
- python/private/py_library.bzl
- python/private/py_runtime_info.bzl
- python/private/py_runtime_rule.bzl
- python/private/pypi/env_marker_info.bzl
- python/private/python.bzl
Update version markers with upcoming version.
> chore: prepare for 1.5 release

- .github/ISSUE_TEMPLATE/patch_release_request.md
- docs/devguide.md
- docs/support.md
We've had several backport requests of late. It's tenable for users to do the more
time consuming working of backporting the code, so give steps on how to do so.
> docs: tell how to do and request patch releases/backports

- sphinxdocs/private/sphinx_build.py
Running Sphinx multiple times in the same process sometimes results in an error ("exit code 2"). Digging in, this is likely a bug in the sphinx_bzl plugin in how it merges data when parallel or incremental builds are performed.
Until that's fixed, work around the problem by internally retrying the Sphinx build when exit code 2 occurs. This is basically what we're doing today and should reduce the number of flakes for the RTD builds.
Along the way, improve the error reporting to make it easier to diagnose the underlying failure.
> fix(sphinxdocs): add retry logic when exit code 2 occurs
