bazel-contrib/rules_python

- gazelle/README.md
While figuring out how to use gazelle with a `src` dir (see https://github.com/bazelbuild/rules_python/issues/1775) (I figured it out by the way, hence this PR), I noticed that the docs were a little unclear.
This PR updates the `gazelle` docs to include details about the `python_root` directive and how to use it.
I also fix a the default value for the
`python_generation_mode_per_file_include_init` directive, as it was incorrectly listed as "package".
> docs(gazelle): Add details about python_root directive.

- CHANGELOG.md
- WORKSPACE
- python/versions.bzl
Updates versions:
* 3.11.7 -> 3.11.8
* 3.12.1 -> 3.12.2
Adds python versions: 3.11.8, 3.12.2
> chore: add python 3.12.2, 3.11.8 toolchain

- MODULE.bazel
- python/pip_install/repositories.bzl
- tools/private/update_deps/update_pip_deps.py
This fixes a minor error in the "maintained by" comments in
`./MODULE.bazel` and `./python/pip_install/repositories.bzl`. The
comments now agree with what `DEVELOPING.md` says.
> build(internal_deps): Update 'maintained by' comments to be correct

- python/pip_install/pip_repository.bzl
Bazel 7.1 has been released, and includes support for `repository_ctx.getenv`. Therefore, update the comments and docs to reflect the current status of the feature with released Bazel versions.
> docs: Update notice about rctx.getenv on Bazel 7

- python/private/common/attributes.bzl
- python/private/common/py_executable.bzl
Adds docs for: stamp, srcs, deps, srcs_version, data, and python_version
> docs: Add some missing attribute docs

- CHANGELOG.md
- python/private/coverage_deps.bzl
The updated covergepy version contains a fix for https://github.com/nedbat/coveragepy/issues/1733 which leads to sporadic issues
```
.../rules_python~~python~python_3_12_x86_64-unknown-linux-gnu_coverage/coverage/collector.py", line 511, in flush_data
for fname, packeds in packed_data.items():
RuntimeError: dictionary changed size during iteration
```
> chore: update coveragepy to 7.4.3

- CHANGELOG.md
- python/pip_install/pip_repository.bzl
- python/private/whl_target_platforms.bzl
- tests/private/whl_target_platforms/whl_target_platforms_tests.bzl
The #1693 PR incorrectly assumed that the platform tag will be os-arch
specific if and only if the abi tag is of form cpxy. However, there are
many wheels that are not like this (e.g. watchdog, tornado, libclang).
This fixes the starlark code that is overriding the user platforms with
something that only the wheel supports by also taking into account the
ABI.
Fixes #1810.
> fix(whl_library): correctly parse wheel target platforms

- python/private/common/py_executable.bzl
- python/private/common/py_executable_bazel.bzl
- python/private/common/py_test_rule_bazel.bzl
The code still supported legacy struct providers, although none were generated or used.
> cleanup: Remove uses of legacy struct providers

- sphinxdocs/private/BUILD.bazel
- sphinxdocs/sphinx.bzl
With this commit the visibility settings are adjusted to use the Sphinx Integration from rules_python also in other (dependent) projects.
Since the Sphinx integration is not yet stable, we denote in the documentation that this is done under the experimental API support. Meaning, breaking changes can occure at any point in time.
See the discussion in #1796
> feat: Make Sphinx integration experimental publicly visible

- CHANGELOG.md
- examples/wheel/BUILD.bazel
- examples/wheel/wheel_test.py
- python/private/py_wheel.bzl
- python/private/repack_whl.py
- tests/py_wheel/py_wheel_tests.bzl
- tools/wheelmaker.py
Fixes #1777
* Adds `data_files` attribute to `py_wheel` rule. 
* Minimal validation of the data-files target directories per [specification](https://packaging.python.org/en/latest/specifications/binary-distribution-format/#installing-a-wheel-distribution-1-0-py32-none-any-whl)
* Added two tests.  
* Added example
> feat: Add support for python-wheel data directory

- CHANGELOG.md
- python/pip_install/private/generate_whl_library_build_bazel.bzl
- python/private/bzlmod/pip.bzl
- tests/pip_install/whl_library/generate_build_bazel_tests.bzl
This removes the `alias` additions when the package groups are not used
fixing alias that attempt to traverse the entire py_library dependency
tree.
I noticed that for some code that I want to write for `whl_library`
having it explicit whether we are using groups or not in the `pip.parse`
and or `whl_library` makes the code easier to understand and write.
Fixes #1760
> fix(whl_library): only add group machinery when it is needed

- sphinxdocs/private/sphinx.bzl
Some Sphinx plugins require that other (not necessarily Python) tools are available.
One example is the plugin https://github.com/basejumpa/sphinxcontrib-umlet, which requires that UMLet is somehow within the sandbox.
* Adds `tools` arg to `sphinx_docs` to allow passing in arbitrary tools
that are made available at runtime
* Performs location expansion on `extra_opts`, which allows passing the
location of the tools onto sphinx.
> feat: Allow additional tools for sphinx_docs

- docs/sphinx/pip.md
Add credential helper docs that were requested in https://github.com/bazelbuild/rules_python/pull/1827#issuecomment-2031018674
> docs: Add basic docs for using credential helper with Bazel downloader of python packages

- gazelle/README.md
- gazelle/python/configure.go
- gazelle/python/testdata/directive_python_default_visibility/test3_injection/BUILD.in
- gazelle/python/testdata/directive_python_default_visibility/test3_injection/BUILD.out
- gazelle/python/testdata/directive_python_default_visibility/test8_multiple_python_root_dirs/proj2/src/pkg2/BUILD.in
- gazelle/python/testdata/directive_python_default_visibility/test8_multiple_python_root_dirs/proj2/src/pkg2/BUILD.out
Make the substitution pattern for `python_default_visibility` consistent
with the existing `python_*_naming_convention` pattern.
In #1787 I added the `python_default_visibility` directive and used a
substitution pattern `$python_root`. However, I missed that the existing
`python_*_naming_convention` directives include a trailing `$`.
This PR is just:
```
rg -l -F "\$python_root" | xargs sed -i 's/\$python_root/$python_root$/g'
```
> fix(gazelle): Consistent substitution pattern for python_default_visibility directive

- MODULE.bazel
- examples/py_proto_library/WORKSPACE
- internal_deps.bzl
- python/private/proto/py_proto_library.bzl
Enables use of `--incompatible_enable_proto_toolchain_resolution` flag that launched in Bazel 7. This allows users to choose a pre-built `protoc` or use the runtime from https://pypi.org/project/protobuf/ rather than be forced to use hard-coded values in Bazel core.
This change is also happening in other language rulesets that provide first-class protobuf support, e.g.
https://github.com/bazelbuild/rules_go/issues/3895
No update to CHANGELOG.md in this PR as the feature is not yet documented for end-users, this just makes it possible to enable the flag. A follow-up PR will provide user instructions.
> refactor: toolchainize py_proto_library

- gazelle/python/parse.py
The python parser uses ProcessPoolExecutor, which is problematic on macOS when it is distributed as a zip file, leading to errors like:
```
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/var/folders/fw/vythc6112ygfsvky8mdb5p580000gn/T/Bazel.runfiles_esxfeg_v/runfiles/python3_aarch64-apple-darwin/lib/python3.9/multiprocessing/resource_tracker.py", line 24, in <module>
from . import spawn
File "/var/folders/fw/vythc6112ygfsvky8mdb5p580000gn/T/Bazel.runfiles_esxfeg_v/runfiles/python3_aarch64-apple-darwin/lib/python3.9/multiprocessing/spawn.py", line 13, in <module>
import runpy
File "/var/folders/fw/vythc6112ygfsvky8mdb5p580000gn/T/Bazel.runfiles_esxfeg_v/runfiles/python3_aarch64-apple-darwin/lib/python3.9/runpy.py", line 19, in <module>
from pkgutil import …
```
> fix: using thread pool on macOS

- CHANGELOG.md
- python/pip_install/repositories.bzl
- python/pip_install/tools/requirements.txt
Bump pip_tools to >= 7.4.0 so that we can make use of better
`pyproject.toml` parsing error messages during compiling.
Specifically: https://github.com/jazzband/pip-tools/pull/1979
> build(deps): Bump pip tools to >= 7.4.0

- CHANGELOG.md
- python/private/bzlmod/pip.bzl
- python/private/pypi_index.bzl
I have found this to be useful when debugging auth issues when using a private
repo and I thought that having it configurable from the user's MODULE.bazel
is a better user experience.
Ammending #1827.
> feat(bzlmod): add a flag to control if the parallel downloading is used

- docs/sphinx/getting-started.md
- docs/sphinx/index.md
- docs/sphinx/toolchains.md
This largely comes from being regularly tagged on BCR PRs about how a module should be configured. This info was sort of already in the getting started docs, but that isn't an obvious place to go and bloated the what should be simplified steps to getting started.
> docs: document how to configure MODULE.bazel for different use cases

- docs/sphinx/index.md
The index had the wrong doc name, so it wasn't showing up in the rendered docs.
> docs: Fix link to toolchain configuration doc in side bar

- .gitignore
- CHANGELOG.md
- MODULE.bazel
- internal_deps.bzl
- python/private/BUILD.bazel
- python/private/common/BUILD.bazel
- python/private/common/attributes.bzl
- python/private/common/common_bazel.bzl
- python/private/common/providers.bzl
- python/private/common/py_executable.bzl
- python/private/current_py_cc_headers.bzl
- python/private/current_py_cc_libs.bzl
- python/private/py_cc_toolchain_rule.bzl
- python/repositories.bzl
- tests/cc/current_py_cc_headers/current_py_cc_headers_tests.bzl
- tests/cc/current_py_cc_libs/current_py_cc_libs_tests.bzl
- tests/cc/fake_cc_toolchain_config.bzl
Adds dependency on rules_cc 0.0.9 for both bzlmod and workspace
This elevates rules_cc from a dev dependency to a full dependency of rules_python.
Work towards incompatible_stop_exporting_language_modules, see https://github.com/bazelbuild/bazel/issues/19455
> deps: load cc symbols from @rules_cc

- CHANGELOG.md
The annotation is `include_dep`, not `include_deps`.
```console
$ # Before this PR:
$ rg -F "include_deps"
CHANGELOG.md
76:* (gazelle) Add a new annotation `include_deps`. Also add documentation for
$
$ # After this PR, there are no more references to "include_deps"
$ rg -F "include_deps"
$
```
> Fix typo in changelog text from #1863

- CHANGELOG.md
- python/pip_install/tools/wheel_installer/wheel.py
- python/pip_install/tools/wheel_installer/wheel_test.py
Before this PR we would incorrectly add deps to the platform-specific
list if there were multiple entries in the `METADATA` file. It seems
that some projects (e.g. [opencv-python]) have multiple entries in their
METADATA file to help SAT solvers with selecting the right version when
different interpreter versions are used.
In our case, we will have only one version of a given package because we
are operating with a locked dependency list, so we should ensure that we
do not have duplicates across the lists. With this PR we are solving
this during the construction of the dependency sets so that the internal
model is always consistent.
Fixes #1873
[opencv-python]: https://pypi.org/project/opencv-python/
> fix(whl_library): stop duplicating deps in whl_library

- .bcr/gazelle/presubmit.yml
The same as in f1d1732b11929671110e6a1b845c8d1a1a67530f.
Fixes that were needed in [bazel/bazel-central-registry#2019](https://github.com/bazelbuild/bazel-central-registry/pull/2019).
> fix(bcr): add mandatory gazelle bcr presubmit attrs

- CHANGELOG.md
- MODULE.bazel
- python/repositories.bzl
- tests/BUILD.bazel
- tests/support/BUILD.bazel
This affects Linux toolchains that have the `terminfo` databases bundled
with the toolchain. Our solution to this is to remove the
`share/terminfo` altogether if we are downloading an affected `linux`
toolchain.
Tested with (on a Mac):
```console
bazel build --platforms=//tests/support:linux_x86_64 @python_3_11//:files
bazel build --platforms=//tests/support:windows_x86_64 @python_3_11//:files
```
Workaround https://github.com/indygreg/python-build-standalone/issues/231
Fixes #1800
> fix(toolchain): delete 'share/terminfo' for recent linux python toolchains

- CHANGELOG.md
- gazelle/python/generate.go
- gazelle/python/kinds.go
- gazelle/python/testdata/remove_invalid_library/BUILD.in
- gazelle/python/testdata/remove_invalid_library/BUILD.out
- gazelle/python/testdata/remove_invalid_library/README.md
- gazelle/python/testdata/remove_invalid_library/WORKSPACE
- gazelle/python/testdata/remove_invalid_library/test.yaml
Before gazelle would leave generated py_library targets aroundeven when no files in a directory exist because X. With this change gazelle correctly handles this case.
> fix(gazelle): delete invalid py_library and use correct NonEmptyAttrs for py_*

- gazelle/python/generate.go
- gazelle/python/testdata/remove_invalid_library/others/BUILD.in
- gazelle/python/testdata/remove_invalid_library/others/BUILD.out
#1887 incorrectly generated an empty py_library for all dirs, although it will eventually be removed because it is empty, but it will easily conflict with other existing rules.
Fix this error, and only generate an empty py_library for bazel packages with the same name py_library rule.
> fix(gazelle): generate empty py_library only when need

- docs/sphinx/precompiling.md
The original PR accidentally said precompiling was enabledy by default.
> docs: doc that precompiling is disabled by default

- python/private/py_wheel.bzl
Fix typo in the py_wheel.bzl docs.
> doc: fix doc typo in py_wheel.bzl

- docs/sphinx/precompiling.md
- python/private/common/common_bazel.bzl
- tests/base_rules/precompile/precompile_tests.bzl
This is just to make the two implementations a bit closer; the mnemonic is a psuedo-public API as it shows up in flags, actions, queries, etc.
> chore(precompiling): use `PyCompile` as mnemonic to match Google mnemonic

- docs/sphinx/BUILD.bazel
- docs/sphinx/bazel_inventory.txt
- docs/sphinx/pyproject.toml
- docs/sphinx/requirements.txt
- sphinxdocs/BUILD.bazel
- sphinxdocs/private/sphinx.bzl
- sphinxdocs/src/sphinx_stardoc/BUILD.bazel
- sphinxdocs/src/sphinx_stardoc/stardoc.py
- sphinxdocs/tests/sphinx_stardoc/BUILD.bazel
- sphinxdocs/tests/sphinx_stardoc/aspect.md
- sphinxdocs/tests/sphinx_stardoc/conf.py
- sphinxdocs/tests/sphinx_stardoc/envvars.md
- sphinxdocs/tests/sphinx_stardoc/function.md
- sphinxdocs/tests/sphinx_stardoc/glossary.md
- sphinxdocs/tests/sphinx_stardoc/index.md
- sphinxdocs/tests/sphinx_stardoc/module_extension.md
- sphinxdocs/tests/sphinx_stardoc/provider.md
- sphinxdocs/tests/sphinx_stardoc/repo_rule.md
- sphinxdocs/tests/sphinx_stardoc/rule.md
- sphinxdocs/tests/sphinx_stardoc/target.md
- sphinxdocs/tests/sphinx_stardoc/xrefs.md
This implements a Sphinx plugin to support Starlark as a first-class domain in Sphinx.
A Starlark domain allows writing object descriptions directly using Sphinx's object
markup language, which allows better integration with cross references, understanding
and distinguishing types, rendering information about things, and referencing types
from other projects.
Note that this doesn't affect the docs today because the proto_to_markdown tool is
still generating regular markdown; updating that to generate Sphinx domain markdown
will be done separately.
Summary of features:
* Types and arguments can be documented using Python syntax, e.g. `list[str]` This includes
unions, generics, and custom types. Each component of the type expression is linked and
cross referenced appropriately. Each object …
> docs: implement Starlark domain plugin for Sphinx

- docs/sphinx/BUILD.bazel
- docs/sphinx/api/python/config_settings/index.md
- docs/sphinx/api/python/index.md
- docs/sphinx/api/tools/precompiler/index.md
- docs/sphinx/bazel_inventory.txt
- docs/sphinx/conf.py
- docs/sphinx/precompiling.md
- python/BUILD.bazel
- python/private/common/providers.bzl
- python/private/py_cc_toolchain_info.bzl
- python/private/py_runtime_pair_rule.bzl
- sphinxdocs/private/proto_to_markdown.py
- sphinxdocs/private/sphinx_server.py
- sphinxdocs/private/sphinx_stardoc.bzl
- sphinxdocs/src/sphinx_stardoc/stardoc.py
- sphinxdocs/tests/proto_to_markdown/BUILD.bazel
- sphinxdocs/tests/proto_to_markdown/proto_to_markdown_test.py
- sphinxdocs/tests/sphinx_stardoc/BUILD.bazel
- sphinxdocs/tests/sphinx_stardoc/bzl_function.bzl
- sphinxdocs/tests/sphinx_stardoc/bzl_providers.bzl
- sphinxdocs/tests/sphinx_stardoc/bzl_rule.bzl
- sphinxdocs/tests/sphinx_stardoc/function.md
- sphinxdocs/tests/sphinx_stardoc/rule.md
- sphinxdocs/tests/sphinx_stardoc/xrefs.md
This switches our doc generation over to using the Starlark domain markup from the sphinx_stardoc plugin instead of using regular markdown. This allows the docs generated from code to better integrate with each other and other parts of the doc site.
Overview of changes:
* Makes the doc paths under the API directory more directly mirror their actual location. e.g. moves "defs.md" -> "python/defs.md". This is so the //tools doc  entries have a more natural location, but can also be used for our other top-level directories.
* Adds API docs for some of the well known targets we have. These aren't automatically generated, but use the Starlark domain markup, so integrate nicely with everything.
* Ensures default values are parsable as Python expressions. Stardoc returns values like "<function …
> docs: generate Starlark domain markup instead of regular markdown

- docs/sphinx/api/python/cc/index.md
This come from the recent slack thread where someone was trying to figure out how to get at the runtime's headers.
> docs: document the current_py_cc_headers and libraries targets

- CHANGELOG.md
- docs/sphinx/requirements.txt
- python/pip_install/repositories.bzl
Bumps:
* importlib_metadata: 6.8.0 -> 7.1.0
* more_itertools: 10.1.0 -> 10.2.0
* packaging: 23.1 -> 24.0
* pep517: 0.13.0 -> 0.13.1
* pip: 23.2.1 -> 24.0
* pyproject_hooks: 1.0.0 -> 1.1.0
* setuptools: 68.1.2 -> 70.0.0
* wheel: 0.41.2 -> 0.43.0
* zipp: 3.16.2 -> 3.18.2
Fixes #1821
> build(deps): Update the pip_install dependencies

- docs/sphinx/toolchains.md
> doc: fix `toolchains.md` mistake

- CHANGELOG.md
- CONTRIBUTING.md
- docs/sphinx/api/python/config_settings/index.md
- docs/sphinx/api/python/index.md
- docs/sphinx/bazel_inventory.txt
- docs/sphinx/pip.md
- docs/sphinx/support.md
- docs/sphinx/toolchains.md
- examples/bzlmod/test.py
- python/BUILD.bazel
- python/config_settings/BUILD.bazel
- python/private/BUILD.bazel
- python/private/autodetecting_toolchain.bzl
- python/private/common/common.bzl
- python/private/common/providers.bzl
- python/private/common/py_executable.bzl
- python/private/common/py_executable_bazel.bzl
- python/private/common/py_runtime_rule.bzl
- python/private/flags.bzl
- python/private/python_bootstrap_template.txt
- python/private/stage1_bootstrap_template.sh
- python/private/stage2_bootstrap_template.py
- python/private/zip_main_template.py
- python/repositories.bzl
- tests/base_rules/py_executable_base_tests.bzl
- tests/base_rules/py_test/py_test_tests.bzl
- tests/support/support.bzl
This is a pretty major, but surprisingly not that invasive, overhaul of how binaries
are started. It fixes several issues and lays ground work for future improvements.
In brief:
* A system Python is no longer needed to perform bootstrapping.
* Errors due to `PYTHONPATH` exceeding environment variable size limits is no
longer an issue.
* Coverage integration is now cleaner and more direct.
* The zipapp `__main__.py` entry point generation is separate from the Bazel
binary bootstrap generation.
* Self-executable zips now have actual bootstrap logic.
The way all of this is accomplished is using a two stage bootstrap process. The first
stage is responsible for locating the interpreter, and the second stage is responsible
for configuring the runtime environment (e.g. import paths). This allows …
> fix: don't require system Python to perform bootstrapping

- CHANGELOG.md
- MODULE.bazel
- python/private/bzlmod/pip.bzl
With this PR we can finally have fewer lock file entries in setups which
do not use the `experimental_index_url` feature yet. This is fully
backwards compatible change as it relies on `bazel` doing the right
thing and regenerating the lock file.
Fixes #1643.
> fix(pip.parse): make the pip extension reproducible if PyPI is not called

- CHANGELOG.md
- python/private/bzlmod/pythons_hub.bzl
With this change we can finally have platform independent bzlmod lock
files in rules_python. This cleans up code paths that were not being
used in the `pip` extension for a while and the replacement is noted in
the CHANGELOG.
Fixes #1643
> fix: make the pythons_hub platform independent

- .bazelci/presubmit.yml
- CHANGELOG.md
- MODULE.bazel
- WORKSPACE
- WORKSPACE.bzlmod
- examples/bzlmod/MODULE.bazel
- examples/bzlmod/py_proto_library/example.com/another_proto/BUILD.bazel
- examples/bzlmod/py_proto_library/example.com/proto/BUILD.bazel
- examples/py_proto_library/WORKSPACE
- examples/py_proto_library/example.com/another_proto/BUILD.bazel
- examples/py_proto_library/example.com/proto/BUILD.bazel
- internal_deps.bzl
- internal_setup.bzl
- python/BUILD.bazel
- python/private/BUILD.bazel
- python/private/proto/BUILD.bazel
- python/private/proto/py_proto_library.bzl
- python/proto.bzl
This reverts commit d0e25cfb41446e481da6e85f04ad0ac5bcf7ea80.
We have the following concerns with the associated change:
- `sphinxdocs` is excluded entirely. Because protobuf fails to compile?
But why? Protos are needed as part of our docgen, but it is unclear
how the docgen is still working. Maybe we can get some clarification
here?
- The `py_proto_library` tests in the `bzlmod` example are excluded from
CI. Because protos also fail to compile? But why? It's an example and
should Just Work.
- Adding the `copts` needs to be done by all downstream users now. But
fixing that in protobuf blocks removing legacy struct providers? I
don't understand the connection.
Also @alexeagle noted extra
[regression](https://github.com/bazelbuild/rules_python/pull/1933#issuecomment-2155523751)
being caused …
> revert: upgrade to protobuf 27.0 and remove py_proto_library (#1933)

- examples/pip_parse/BUILD.bazel
- python/current_py_toolchain.bzl
- python/private/common/py_executable_bazel.bzl
- tests/toolchains/defs.bzl
The `@rules_python//python:toolchain_type` target is just an alias to the bazel tools one, so this should be a no-op change. It's less confusing to use a consistent label than to have a mix of them.
> chore: refer to rules_python toolchain type target instead of bazel_tools

- CHANGELOG.md
- python/private/common/py_executable_bazel.bzl
- tests/base_rules/py_executable_base_tests.bzl
It seems that there is an extra argument that is there but I am not sure about
the reason, it is most likely a leftover. As part of this change we add an
analysis test for non-windows zip building. I could reproduce the failure and
now the newly added test passes.
Fixes #1954
> fix(rules): drop the unused argument

- .bazelrc
- CHANGELOG.md
- MODULE.bazel
- examples/bzlmod/MODULE.bazel
- internal_deps.bzl
Makes `rules_python` compatible with `--incompatible_disallow_struct_provider_syntax`.
Fixes #1956
> fix: Remove transitive legacy struct provider usage

- python/config_settings/BUILD.bazel
- python/private/common/BUILD.bazel
- python/private/common/py_library.bzl
* Make py_library doc customizable.
* Correct a typo checkers are spammy about
* Add missing bzl_library. I would have expected our docgen to have also noticed this, but it must be picking it up from another transitive dependency, while the Google tests don't get that.
> chore: various cleanups to make google imports/patching easier

- .github/dependabot.yml
This way the requirements files in the examples and tests are not
managed, which should reduce the PR noise.
> ci: add a custom dependabot file

- CHANGELOG.md
- python/private/bzlmod/pip_repository.bzl
We have at least one instance in our pre-bzlmod workspace like:
```
deps = list(all_requirements)
deps.remove(requirement('foo'))
```
But when using bzlmod, the generated `all_requirements` list contains targets like `@@rules_python~~pip~my_deps//sqlalchemy:sqlalchemy`, whereas `requirement('sqlalchemy')` will return `@@rules_python~~pip~my_deps//sqlalchemy:pkg`. So this operation now fails.
This change makes `all_requirements` also use the `:pkg` targets to match `requirement`.
> fix(bzlmod): use same target in requirement('foo') and all_requirements

- CHANGELOG.md
- python/config_settings/BUILD.bazel
- python/private/config_settings.bzl
- python/private/pip_config_settings.bzl
- python/private/pip_flags.bzl
- tests/pip_hub_repository/render_pkg_aliases/render_pkg_aliases_test.bzl
Remove the `python_version` from `flag_values` and reduces the number of
targets we create by a lot because we no longer need to create all of the micro
version combinations to also match when we want to match e.g. 3.10 on a
particular platform by using a trick I've learned in #1968:
```starlark
select({
"is_python_3.x": "my_config_setting"
"//conditions:default": "is_python_3.x"
})
```
Then further optimization was done on how we create the aliases and config
settings and optimizing the usage of `pip_whl` flag finally reduced the
internal number targets. The number config settings targets in
`//tests/private/pip_config_settings/...` where we have multiple python
versions has changed:
* `:is_*` - from **995** to **996** (the extra addition being is_python_default).
* `:_.*is_*` - from …
> refactor(bzlmod): generate fewer targets for pip_config_settings

- python/private/common/py_executable.bzl
This enables an optimization in Bazel et al to better track when targets actually need stamping information. Accessing the `ctx.version_file` tells Bazel the target depends on stamping information, which related systems can use to optimize processing of the build graph.
> chore: access ctx.version_file to inform Bazel stamping info is needed

- python/private/common/attributes.bzl
- python/private/parse_requirements.bzl
- python/private/py_interpreter_program.bzl
- python/private/py_toolchain_suite.bzl
- python/private/render_pkg_aliases.bzl
- python/private/repo_utils.bzl
- python/private/zip_main_template.py
These were found by some Google internal typo checkers
> docs: Fix a few typos in docs and function names

- CHANGELOG.md
- python/private/common/attributes.bzl
This allows the precompile action to resolve its tools separately from other toolchains,
allowing toolchain types with otherwise incompatible `exec_compatible_with` definitions
to be used together.
> fix: enable auto exec groups using attribute

- python/config_settings/BUILD.bazel
- python/config_settings/private/BUILD.bazel
- python/entry_points/BUILD.bazel
This is to make Google patching and imports of rules_python easier. Within Google, `BUILD` is the file name instead of `BUILD.bazel`. It's also easy for the distribution filegroups to accidentally miss files, so to prevent that, just glob everything.
> chore: use `**` globs instead of explcit BUILD.bazel reference in distribution filegroups

- gazelle/manifest/defs.bzl
- gazelle/manifest/test/test.go
This makes it possible for the test to work with sibling repository layout.
Tested by running the :gazelle_python_manifest.test in build_file_generation with all combinations of both values of --legacy_external_runfiles, --enable_bzlmod and --sibling_repository_layout.
> fix: Resolve the test manifest with the runfiles lib.

- CHANGELOG.md
This is to include the changelog in the auto-generated docs.
> doc: Changelog updates for 0.33.2

- python/private/internal_config_repo.bzl
Mark internal_config_repo as `configure = True` so that it won't be vendored by Bazel vendor mode.
https://bazel.build/rules/lib/globals/bzl#parameters_7
> fix: Add `configure=True` for internal_config_repo

- CHANGELOG.md
- python/private/bzlmod/pip.bzl
Before this change `isolated`, `quiet` and `timeout` would get dropped
if they were specified to some non-default value. This fixes it.
Work towards #260.
> fix(bzlmod): pass only non-default values to whl_library

- README.md
I believe the intended content is now here: https://rules-python.readthedocs.io/en/latest/#migrating-from-the-bundled-rules
Im not sure there is much value linking to that page, but I don't mind. Just let me know.
> docs: Removes dead link after docs were migrated to sphinx

- CHANGELOG.md
- python/private/common/py_executable.bzl
- tests/base_rules/py_executable_base_tests.bzl
This fixes a small change in behavior identified by some Google regression tests. When precompiling was introduced, the target's executable was no longer the first file in the default outputs depset. While that behavior isn't a strong contract, it is the convention with many other rules, and the existing behavior for Bazel 7+.
To fix, put the executable as the first value in the default outputs list. Also adds a test for this behavior.
> fix: make first default output the executable again

- python/config_settings/BUILD.bazel
- python/private/pypi/BUILD.bazel
- python/private/pypi/flags.bzl
This is updated so tooling can more automatically process the files. In particular, it helps tools, like buildozer, process the files, which makes it easier to import the code into Google. This is because there is a named target that buildozer can be told to process, whereas, with a list comprehension, it's an arbitrary chunk of code that has to be patched, without an identifiable label.
> refactor: call a function to define internal pypi flags instead of listcomp

- CHANGELOG.md
- python/private/pypi/whl_installer/wheel.py
- tests/pypi/whl_installer/wheel_test.py
It seems that there was a single-line bug that did not allow us to
handle arch-specific deps and since the percentage of such wheels is
extremely low, it went under the radar for quite some time.
I am going to not implement any explicit passing of the default python
version to `whl_library` as it is a much bigger change. Just doing this
could be sufficient for the time being.
Fixes #1996
> fix(whl_library): correctly handle arch-specific deps in wheels

- python/versions.bzl
Enable i386 Linux platform detection support.
Without this change `rules_python` complains about an unrecognized platform when run on a 32-bit platform, e.g. where `os.uname().machine` returns `i686`. This effectively makes `rules_python` unusable on 32-bit platforms.
> fix(multiplatform): Add i386 Linux support

- CHANGELOG.md
- python/private/pypi/parse_requirements.bzl
parse_requirements.bzl includes a broken logger statement by passing a string instead of a lambda. The result is that when a hash is no longer available on pypi (say, due to a release being yanked) that rules_python causes Bazel to halt. Since we use Bazel to generate requirements files, this means the only solution is to use non-Bazel tooling to get back to a functional state before then running Bazel tooling to update the requirements file -- all down to a faulty log statement.
This PR corrects the faulty log statement. A more thorough fix might be to update the logger to warn if its invoked with a string instead of a lambda rather than failing.
An example traceback which led to this discovery:
```
ERROR: Traceback (most recent call last):
File …
```
> fix: Fix broken logger statement in parse_requirements.bzl

- .github/CODEOWNERS
It seems that I am not added to PyPI reviewers. After rereading the comment at the top of the file, it makes sense.
> chore: include aignas to PyPI code reviewers

- CHANGELOG.md
- python/private/pypi/parse_simpleapi_html.bzl
- tests/pypi/parse_simpleapi_html/parse_simpleapi_html_tests.bzl
This PR modifies the logic for finding the end of the of the <a> 
tag metadata attributes in the pypi `parse_simpleapi_html` function.
This was discovered after investigation of the following error:
```
Error in repository_rule: invalid user-provided repo name 'pypi_311_=2_7,!=3_0_*,!=3_1_*,!=3_2_*">six_py2_none_any_8abb2f1d': valid names may contain only A-Z, a-z, 0-9, '-', '_', '.', and must start with a letter
```
which was traced back to the to a `data-requires-python` attribute containing a `>` sign (instead of `&gt;`) in the Azure Artifacts pypi feed, e.g.:
`<a href="https://microsoft.pkgs.visualstudio.com/REDACTED_URL/six-1.16.0-py2.py3-none-any.whl#sha256=8abb2f1d86890a2dfb989f9a77cfcfd3e47c2a354b01111771326f8aa26e0254" data-requires-python=">=2.7,!=3.0.*,!=3.1.*,!=3.2.*">six-1.16. …
> fix: pypi parse_simpleapi_html.bzl is robust to metadata containing ">" sign

- gazelle/MODULE.bazel
- gazelle/deps.bzl
- gazelle/python/BUILD.bazel
The `http_file` repo rules relied on Github-specific per-file HTTP API. Change this to use an `http_archive` repo rule, which refers to a simple URL containing the source tarball for stdlib-list.
The release version of pypi/stdlib-list this is now pointing to is [v0.10.0](https://github.com/pypi/stdlib-list/releases/tag/v0.10.0). This tag is slightly older than the original commit it was pointing to (`8cbc2067a4a0f9eee57fb541e4cd7727724b7db4`) but, as discussed in https://github.com/pypi/stdlib-list/issues/122, the only differences are build or doc related, there are no differences in the sources (see the [diff](https://github.com/pypi/stdlib-list/compare/v0.10.0...8cbc2067a4a0f9eee57fb541e4cd7727724b7db4)).
(Creating an associated issue didn't feel particularly useful but happy to do it …
> refactor: use http_archive for the stdlib list

- CHANGELOG.md
- python/private/stage1_bootstrap_template.sh
When the two-stage bootstrap is used, the parent shell process runs python as a child 
process, which changes how signals are propagated. Specifically, if a signal is sent
_directly_ to the parent (e.g. `kill $parent`), the child process (python) won't receive
it and it will appear to be ignored. This is because the parent process is busy waiting
for the child process.
To fix, invoke the python process using `exec` instead. Because the process is entirely
replaced, signals are sent directly to the replacement. This can't be used for zip files,
though, because they rely on a catching the exit signal to perform cleanup of the extracted
files.
Fixes https://github.com/bazelbuild/rules_python/issues/2043
> fix: use `exec` to invoke the stage-2 bootstrap for non-zip case

- .bcr/presubmit.yml
For some unknown reason, the BCR Mac jobs require `-std=c++14` when compiling. Without this, they fail with the error `C++ versions less than C++14 are not supported.`
This only appears to happen in the BCR presubmits.
> chore: add cxxopt std=c++14 to BCR presubmit config

- python/private/pypi/deps.bzl
- python/private/pypi/pip_compile.bzl
- python/private/pypi/whl_installer/BUILD.bazel
- python/private/pypi/whl_library.bzl
As a general practice, the repo-phase and build-phase shouldn't load code from one
another because they can't use each other's objects. It can also result in confusing
behavior because the "starlark environment" is slightly different between the two phases.
Additionally, Google's version of Bazel essentially disables repo-phase objects, so
loading e.g. http_archive results in errors. This makes it more difficult to import
rules_python into Google, as we have to maintain patches to cut out the code (and thus
we spend more time trying to import the code than working on it).
> refactor: don't load repo-phase objects from build-phase

- gazelle/manifest/defs.bzl
Fixes #2057.
Commit a1d2e45 (#1993) added a reference to `@com_github_bazelbuild_rules_go`, but the module is already added as `@io_bazel_rules_go`.
> fix(gazelle): Use the correct rules_go label in gazelle/manifest/defs.bzl

- python/uv/private/BUILD.bazel
- python/uv/private/toolchains_repo.bzl
- python/uv/private/versions.bzl
- python/uv/repositories.bzl
Follows: https://github.com/bazelbuild/rules_python/pull/1989
Addresses the following:
* Removes usage of `maybe`
* Pretty-print renders some generated *.bazel
* Shorter default_repo_names
> refactor: Address a few improvements on `uv` toolchain

- CHANGELOG.md
- python/private/stage1_bootstrap_template.sh
- tests/base_rules/BUILD.bazel
- tests/base_rules/bin.py
- tests/base_rules/run_binary_zip_no_test.sh
- tests/base_rules/run_binary_zip_yes_test.sh
- tests/base_rules/run_zip_test.sh
- tests/support/sh_py_run_test.bzl
Macs have an older version of `mktemp`, one that doesn't support the `--suffix` arg. This
caused the combination of Macs and `--build_python_zip --bootstrap_impl=script` to fail.
To fix, remove the `--suffix` arg. As far as I can tell, the suffix string,
"Bazel.runfiles_", is just informational, so this is fine to remove.
Also adds tests to verify that a binary runs with/without zip and for the script
bootstrap.
Fixes https://github.com/bazelbuild/rules_python/issues/2030
> fix: make mac zip builds work

- python/private/pypi/BUILD.bazel
- python/private/pypi/extension.bzl
- python/private/pypi/parse_requirements.bzl
- python/private/pypi/pip_repository.bzl
- python/private/pypi/pypi_repo_utils.bzl
- python/private/pypi/render_pkg_aliases.bzl
- python/private/pypi/requirements_files_by_platform.bzl
- python/private/pypi/whl_library.bzl
- tests/pypi/parse_requirements/parse_requirements_tests.bzl
- tests/pypi/render_pkg_aliases/render_pkg_aliases_test.bzl
- tests/pypi/requirements_files_by_platform/BUILD.bazel
- tests/pypi/requirements_files_by_platform/requirements_files_by_platform_tests.bzl
This is extra preparation needed for #2059.
Summary:
- Create `pypi_repo_utils` for more ergonomic handling of Python in repo context.
- Split the resolution of requirements files to platforms into a separate function
to make the testing easier. This also allows more validation that was realized
that there is a need for in the WIP feature PR.
- Make the code more robust about the assumption of the target platform label.
Work towards #260, #1105, #1868.
> refactor(pypi): split out more utils and start passing 'abi_os_arch' around

- docs/sphinx/environment-variables.md
- docs/sphinx/index.md
- python/private/pypi/attrs.bzl
This is so they're more discoverable for both developers and users.
> docs: document some environment variables

- python/private/local_runtime_repo.bzl
- python/private/pypi/BUILD.bazel
- python/private/pypi/extension.bzl
- python/private/pypi/parse_requirements.bzl
- python/private/pypi/pip_repository.bzl
- python/private/pypi/pypi_repo_utils.bzl
- python/private/repo_utils.bzl
This also changes the local_runtime_repo to explicitly check for
supported platforms instead of relying on a `None` value returned by the
helper method. This makes the behaviour exactly the same to the
behaviour before this PR and we can potentially drop the need for the
validation in the future if our local_runtime detection is more robust.
This also makes the platform detectino in `pypi_repo_utils` not depend
on `uname` and only use the `repository_ctx`. Apparently the
`module_ctx.watch` throws an error if one attempts to watch files on the
system (this is left for `repository_rule` it seems and one can only do
`module_ctx.watch` on files within the current workspace. This was
surprising, but could have been worked around by just unifying code.
This splits out things from #2059 and …
> refactor(internal): move the os/arch detection to repo_utils

- python/private/pypi/pip_repository.bzl
My default expectation would be that the keys to the `annotations` dictionary passed to `pip_parse` would use the `normalize_name(...)` convention, as is used elsewhere in the API. However, this does not appear to be the case. I originally was going to file a bug, but maybe just documenting the current behavior is enough?
For a minimal repro showing that this capitalization is indeed required, see https://github.com/bruno-digitbio/bug-rules-python-annotation-pyqt
In that repo, 
```bash
$ bazel run //:test_has_comment
$ tail $(bazel info output_base)/external/pip_pyqt6/BUILD.bazel
$ tail $(bazel info output_base)/external/pip_wheel/BUILD.bazel
```
will both show `# A comment` at the bottom, as requested in the `WORKSPACE` file. However, if you first run
```bash
$ bazel run …
```
> docs: describe `annotations` attr of `pip_parse`

- CHANGELOG.md
- python/private/pypi/extension.bzl
- python/private/pypi/parse_requirements.bzl
- python/private/pypi/whl_library.bzl
- python/private/pypi/whl_target_platforms.bzl
- python/private/repo_utils.bzl
- tests/pypi/parse_requirements/parse_requirements_tests.bzl
- tests/pypi/whl_target_platforms/select_whl_tests.bzl
It seems that a few things broke in recent commits:
- We are not using the `MODULE.bazel.lock` file and it seems that it is easy to
miss when the components in the PyPI extension stop integrating well
together. This happened during the switch to `{abi}_{os}_{plat}` target
platform passing within the code.
- The logger code stopped working in the extension after the recent additions
to add the `rule_name`.
- `repo_utils.getenv` was always getting `PATH` env var on bazel `6.x`.
This PR fixes both cases and updates docs to serve as a better reminder. By
fixing the `select_whls` code and we can just rely on target platform triples
(ABI, OS, CPU). This gets one step closer to maybe supporting optional
`python_version` which would address #1708. Whilst at it we are also adding
different status …
> fix(pypi): fix the whl selection algorithm after #2069

- sphinxdocs/private/readthedocs.bzl
This just makes it possible to use the macro outside `rules_python`.
Not adding anything to the CHANGELOG as this is not a documented
API.
> fix(sphinxdocs): use Label in the readthedocs_install macro

- CHANGELOG.md
- python/private/pypi/whl_library.bzl
Before this PR the extra arguments added by the `experimental_index_url`
code paths were not used and the `sdist` was being redownloaded every time
we would build from `sdist`.
This PR fixes the code to not ignore the extra args added in
https://github.com/bazelbuild/rules_python/pull/2091/files#diff-c007ed21502bf8ea19b98b3f1b402e7071615f8520e4291b00a71bca2cd451e8R231
Fixes #2090
> fix: use downloaded archive in sdist

- python/private/python.bzl
- tests/toolchains/defs.bzl
This PR uses the `flag_values` from the platform definitions
for the toolchains so that in the future we can distinguish
between `musl` and `glibc` toolchains in our tests.
For now the change is no-op.
As part of this change we are also registering the coverage
tools so that we can run `bazel coverage` with no errors.
See comment on #2095.
> test(toolchain): use flag_values in test platform defs

- CHANGELOG.md
- python/private/BUILD.bazel
- python/private/python.bzl
Before this PR we would warn when non-root modules register interpreter
versions and the owners of root modules would have no way to silence the
warning except for patching rules_python.
This PR reduces the default verbosity of the warning to INFO to avoid
spamming users by default.
Fixes #1818.
> fix(bzlmod): silence duplicate version registrations

- CHANGELOG.md
- python/config_settings/transition.bzl
- tests/config_settings/transition/multi_version_tests.bzl
This makes the versioned rules return both the `@builtin` and `@rules_python` provider
objects. This makes the versioned rules more compatible with the non-versioned rules.
Fixes https://github.com/bazelbuild/rules_python/issues/2114
> fix: make versioned rules return both builtin and rules_python providers

- examples/bzlmod/test.py
Bazel is changing its separate character from tilde (`~`) to plus (`+`) to address a performance issue on Windows. The test was using tilde to help match files of interest.
To fix, have the test look for either tilde or plus.
Fixes https://github.com/bazelbuild/rules_python/issues/2105
> tests: fix example bzlmod coverage test for latest Bazel

- CHANGELOG.md
- python/private/python_repositories.bzl
- tests/cc/current_py_cc_libs/BUILD.bazel
Previously, `//tests/cc/current_py_cc_libs::python_libs_linking_test` failed on macOS because the bootstrapped toolchain's dylib had an incorrect LC_ID_DYLIB field set, pointing to a local directory on the Python standalone build host machine.
To fix, add a small conditional to the Python repository rule patching the LC_ID_DYLIB field of the bootstrapped Python's dylib with its fully qualified file system path. Patching is carried out with macOS's own `install_name_tool`, which is part of the standard macOS dynamic linking toolchain.
Qualifies the mentioned test as executable on Mac, now only Windows linker errors are left to fix.
> fix: Fix up search path of bootstrapped Python toolchain dylib

- CHANGELOG.md
- python/private/pypi/parse_simpleapi_html.bzl
- python/private/pypi/simpleapi_download.bzl
- tests/pypi/parse_simpleapi_html/parse_simpleapi_html_tests.bzl
This PR addresses a typo and improves the handling of absolute URLs in the
`parse_simpleapi_html.bzl` file and corrects a minor issue in the
`simpleapi_download.bzl` file.
Summary:
1. parse_simpleapi_html.bzl:
- Introduced a new private function `_get_root_directory(url)` to extract
the root directory from a given URL.
- Enhanced `_absolute_url` function to correctly handle absolute URLs by
utilizing the `_get_root_directory` function. This ensures that URLs
starting with a "/" are correctly resolved to their full path, avoiding
potential incorrect concatenation.
2. simpleapi_download.bzl: Corrected the handling of the `real_url` variable in
the `_read_simpleapi` function, ensuring that the correct URL is passed to
`_read_index_result` when using non-blocking downloads.
> fix: correctly handle absolute URLs in parse_simpleapi_html.bzl

- docs/sphinx/BUILD.bazel
- sphinxdocs/inventories/BUILD.bazel
- sphinxdocs/inventories/bazel_inventory.txt
- sphinxdocs/tests/sphinx_stardoc/BUILD.bazel
This moves the inventory file for Bazel objects under the sphinxdocs directory. Inventory
files are the manifest of things that can be cross referenced from some external source.
They're moved under sphinxdocs since these are about Bazel in general and aren't specific
to rules_python.
> docs: move Sphinx object inventory for Bazel under sphinxdocs

- CHANGELOG.md
- gazelle/manifest/test/test.go
I'm getting a build error in my builds because nogo complains about this bug. I guess I could configure my nogo to no check this code, but I think it should be fixed.
> fix: formatting directive bugs in test

- python/private/common/attributes.bzl
- python/private/common/py_executable.bzl
- sphinxdocs/docs/sphinx-bzl.md
- sphinxdocs/src/sphinx_bzl/bzl.py
I found turning these into clickable links made browsing the docs to understand behavior easier.
* Also adds `{flag}` as a valid reference role.
> docs: turn a couple mentions of flags into cross references

- CHANGELOG.md
- examples/bzlmod/MODULE.bazel.lock
- python/private/pypi/parse_simpleapi_html.bzl
- tests/pypi/parse_simpleapi_html/parse_simpleapi_html_tests.bzl
This updates the simpleapi parser to handle indexes where wheel and sdist may be an index_url relative path. It also organises the conditionals with fewer negations so they're easier to read
Fixes: #2150
> fix: Handle relative paths properly in _absolute_url

- CHANGELOG.md
- gazelle/python/testdata/dependency_resolution_order/BUILD.in
- gazelle/python/testdata/dependency_resolution_order/BUILD.out
- gazelle/python/testdata/dependency_resolution_order/gazelle_python.yaml
- gazelle/python/testdata/dependency_resolution_order/third_party/BUILD.out
- gazelle/python/testdata/dependency_resolution_order/third_party/baz.py
- gazelle/pythonconfig/pythonconfig.go
In https://github.com/bazelbuild/rules_python/pull/2048, `FindThirdPartyDependency` was updated to walk up the module import path to try to find a match in gazelle_python.yaml. This is unnecessary, as the main resolve loop will accomplish the same task.
Additionally, the change broke the ability to configure a more specific resolve override or resolve more specific indexed libraries.
For a real-world example of where this is a problem, `pytype` has a `third_party` module at its top-level. In a repo that also has a `third_party` directory, we can no longer resolve our indexed libraries in `third_party`. When the resolve loop tried to resolve `third_party.foo.bar`, `FindThirdPartyDependency` will immediately match `third_party` and not give the resolve loop a chance to look in the rule …
> fix(gazelle): Correctly resolve deps that have top-level module overlap with a gazelle_python.yaml dep module

- tools/precompiler/precompiler.py
This is supposed to check that all argument counts are equal, but due to an incorrect inversion of the conditional, it was checking that *any* pair of argument counts is equal
> fix: correctly check the arg count in precompiler.py

- python/private/common/py_library.bzl
This allows the Google fork to pass additional fragment names.
> refactor: allow py_library to accept additional fragments

- CHANGELOG.md
- python/private/config_settings.bzl
- sphinxdocs/inventories/bazel_inventory.txt
Make the `--python_version` flag also return the `FeatureFlagInfo` provider.
There are two reasons to also return the FeatureFlagInfo provider:
First, it allows the flag implementation to change the value and have that value respected
by config_setting() later. This allows, for example, the rule to use custom logic (and
information from things it depends on) to determine the effective flag value.
Secondly, it makes the flag compatible with the Google fork of this rule, which is 
implemented using FeatureFlagInfo, to help eventually converge them.
Along the way, add config_common to the Sphinx Bazel inventory.
> refactor(flags): return FeatureFlagInfo in --python_version flag

- CHANGELOG.md
- python/packaging.bzl
- python/private/BUILD.bazel
- python/private/py_wheel_dist.py
While trying to modernize an older repo I tried building wheels on windows and ran into a failure:
```
Windows Subsystem for Linux has no installed distributions.
Use 'wsl.exe --list --online' to list available distributions
and 'wsl.exe --install <Distro>' to install.
Distributions can also be installed by visiting the Microsoft Store:
https://aka.ms/wlstore
Errorcode: Bash/Service/CreateInstance/GetDefaultDistro/WSL_E_DEFAULT_DISTRO_NOT_FOUND
```
This appears to be caused by the `py_wheel_dist` rule which gets caught by `//...`. This target should be considered a side-effect/optional target of `py_wheel`. To fix:
1. Mark the target as `manual`, so it's only built when explicitly requested.
2. Implement copying to the directory with a Python program instead of shell, so bash
isn't …
> fix(py_wheel): Avoid reliance on bash in `py_wheel` macro.

- CHANGELOG.md
- docs/BUILD.bazel
- python/BUILD.bazel
- python/private/BUILD.bazel
- python/private/common/BUILD.bazel
- python/private/common/py_executable.bzl
- python/private/py_executable_info.bzl
- python/py_executable_info.bzl
- sphinxdocs/inventories/bazel_inventory.txt
- tests/base_rules/py_executable_base_tests.bzl
- tests/support/py_executable_info_subject.bzl
The PyExecutableInfo provider exposes executable-specific information that isn't easily accessible outside the target. The main purpose of this provider is to facilitate packaging a binary or deriving a new binary based upon the original.
Within rules_python, this will be used to pull the zip-building logic out of executables and into separate rules. Within Google, this will be used for a similar "package a binary" tool.
Along the way:
* Add runfiles references to sphinx inventory
> feat(rules): add PyExecutableInfo

- docs/api/rules_python/python/index.md
- docs/api/rules_python/python/runtime_env_toolchains/index.md
- sphinxdocs/inventories/bazel_inventory.txt
- sphinxdocs/private/sphinx.bzl
- sphinxdocs/src/sphinx_bzl/bzl.py
- sphinxdocs/tests/sphinx_stardoc/BUILD.bazel
- sphinxdocs/tests/sphinx_stardoc/bzl_rule.bzl
- sphinxdocs/tests/sphinx_stardoc/index.md
- sphinxdocs/tests/sphinx_stardoc/sphinx_output_test.py
- sphinxdocs/tests/sphinx_stardoc/xrefs.md
This changes the way objects are tracked to use Bazel label format instead of dotted notation.
The dotted notation was problematic because it was ambiguous. For example, `foo.bar.baz`
could mean `@foo//bar:baz` or `@foo//:bar.bzl%baz`. It also required various internal hacks
to try and "unparse" the dotted notation into the "meaningful" part of an object to use
in various contexts. For example, `//foo:bar` usually means `bar` is the key term to
show, and `//foo:bar.bzl%baz.qux` usually means `qux` or `baz.qux` is the meaningful part.
Also:
* Make referring to things by the bzl-relative symbol names work. e.g. `baz.qux` can be
used to reference `//foo:bar.bzl%baz.qux`
* Fix the name/referencing of runtime_env_toolchains (it was using singular in the docs)
* Add some more references to …
> refactor(sphinxdocs): use bazel label format for internal object tracking

- CHANGELOG.md
- docs/api/index.md
- docs/conf.py
- python/private/pypi/pip_repository.bzl
- sphinxdocs/docs/sphinx-bzl.md
This fixes a few warnings Sphinx emits when processing docs
* Fix py_console_script_binary reference in changelog
* Remove `*` that doesn't match anything in index
* Replace heading with rubric to remove warning about non-consecutive indent
* Remove duplicate bzl:type role definition
> docs: fix some doc warnings and xrefs

- tools/precompiler/precompiler.py
This allows one to actually run this script with *just* these flags: src, src_name, pyc
Extra: refactor how the enum member is parsed
> refactor(precompiler): give optimize/invalidation_mode flags default values

- python/private/common/attributes.bzl
Also mention the pyc_collection attribute and precompiling guide to better guide users on how to use precompiling and use binary-level opt-in.
> doc: clarify the precompile attribute affects the local target

- .bazelci/presubmit.yml
Only do this for latest Bazel (--enable_workspace was only introduced in 7.1.0).
Fixes https://github.com/bazelbuild/rules_python/issues/2175
> build(bazelci): explicitly enable workspace where Bzlmod is disabled

- python/private/py_exec_tools_info.bzl
- sphinxdocs/inventories/bazel_inventory.txt
Also sorts the names in the inventory.
> docs: add `testing.*` Bazel objects to Sphinx inventory and xref in docs

- CHANGELOG.md
- python/private/stage1_bootstrap_template.sh
- tests/bootstrap_impls/run_binary_zip_no_test.sh
The script-based bootstrap wasn't computing the correct runfiles directory when
`RUNFILES_MANIFEST_FILE` was set. The path it computed stripped off the manifest
file name, but didn't re-add the `.runfiles` suffix to point to the runfiles
directory.
To fix, just re-append the `.runfiles` suffix after it removes the manifest file
name portion of the path.
Reproducing this is a bit tricky and it's difficult to reproduce the necessary build
flags in a test; all of the following must be met:
* `--enable_runfiles=false`, but this cannot be set by transitions, only via command line
* `--build_runfile_manifests=true` (this can be set in a transition, but see below)
* Due to https://github.com/bazelbuild/bazel/issues/7994, even if a manifest is created,
the RUNFILES_MANIFEST_FILE env var won't be …
> fix: make bootstrap_impl=script compute correct directory when RUNFILES_MANIFEST_FILE set

- tests/base_rules/precompile/precompile_tests.bzl
This is a stray commented out line that was left over from debugging.
> cleanup: remove commented out debug statement in precompile tests

- docs/api/rules_python/python/config_settings/index.md
- python/config_settings/BUILD.bazel
- python/private/common/attributes.bzl
- python/private/flags.bzl
This defaults the `--precompile_source_retention` flag to a new value, `auto`. The effective default remains the same (`keep_source`).
Having a separate value as the default allows detecting if the value was specified on the command line, which allows distinguishing between "pick for me" vs "I specifically want this behavior".
> fix: allow detecting if `--precompile_source_retention` was specified on the command line

- sphinxdocs/inventories/bazel_inventory.txt
And sort the list again - used `nvim` `:sort` after selecting
all attributes.
> docs: add module_ctx, repository_ctx and path for xref support

- CHANGELOG.md
- docs/BUILD.bazel
- examples/bzlmod/MODULE.bazel.lock
- python/private/BUILD.bazel
- python/private/python_repositories.bzl
- python/repositories.bzl
The bazel inventory for this sphinxdocs is in #2188.
Removed the things that are definitely not used and the rest of the symbols
can be left until we become bzlmod only - they do not require much maintenance.
> chore: cleanup exposed python_repository symbols and add docs

- python/private/common/py_executable.bzl
- python/private/py_executable_info.bzl
PyExecutableInfo was added in https://github.com/bazelbuild/rules_python/pull/2166 with the field `runfiles_without_exe` that intentionally excludes files that are specific to
that target/executable, such as the build data file (which may contain the target name,
or other target-specific information).
However, consuming tools (such as ones used within Google) may need to derive a file from
that build data, override it completely, or be happy with its content as is. To aid that
case, expose it via PyExecutableInfo.
> feat(rules): add build_data_file field to PyExecutableInfo

- tests/base_rules/precompile/precompile_tests.bzl
When imported into Google, the workspace-relative path changes, which makes the tests fail. Using the `{package}` format kwarg makes the tests independent of their location in the workspace.
> tests: use `{package}` instead of hard-coded path in precompile_tests

- python/private/BUILD.bazel
- python/private/py_exec_tools_info.bzl
- python/private/py_exec_tools_toolchain.bzl
- python/private/sentinel.bzl
- tests/py_exec_tools_toolchain/BUILD.bazel
- tests/py_exec_tools_toolchain/py_exec_tools_toolchain_tests.bzl
This allow the exec_interpreter attribute to propagate None even though it's a label
with a default value. Such attributes can't _directly_ be set to None because None
means to use the default. To work around that, a sentinel target is used, which allows
breaking the dependency on the default and triggering the rule to use None instead.
A null exec interpreter is necessary in environments that don't provide a separate Python
interpreter.
> fix: allow disabling exec_tools toolchain from looking up an interpreter

- docs/BUILD.bazel
- python/py_runtime_pair.bzl
Their doc targets weren't included in the main docs deps list, so they weren't showing up.
Also xref from the py_runtime_pair macro to the underlying rule.
> docs: document py_cc_toolchain and py_runtime_pair

- CHANGELOG.md
- python/private/py_cc_toolchain_info.bzl
- python/private/py_cc_toolchain_rule.bzl
- tests/cc/py_cc_toolchain/py_cc_toolchain_tests.bzl
This is for cases when shared libraries aren't available.
> feat: allow py_cc_toolchain libs to be optional

- CHANGELOG.md
- examples/wheel/BUILD.bazel
- examples/wheel/wheel_test.py
- tools/wheelmaker.py
Currently, if extra requirements are provided via a file, it is allowed to contain markers, but if it is passed via extra_requires field, it will run into error since the extra in this case is blindly added in the following line in `py_wheel.bzl`
```
metadata_contents.append(
"Requires-Dist: %s; extra == '%s'" % (requirement, option),
)
```
Thus, this PR adds a post-process for this case, to make it possible to pass something like
```
extra_requires = {"example": [
"pyyaml>=6.0.0,!=6.0.1",
'toml; (python_version == "3.11" or python_version == "3.12") and python_version != "3.8"',
'wheel; python_version == "3.11" or python_version == "3.12" ',
]},
```
to `py_wheel`
> fix: Fix incorrectly generated `Required-Dist` when specifying requirements with markers in extra_requires in py_wheel rule

- CHANGELOG.md
- examples/bzlmod/MODULE.bazel.lock
- python/private/python_repositories.bzl
- python/versions.bzl
This value has been hardcoded for a long time, so let's add the `patch_strip`
attribute to the `WORKSPACE` setups now so that we add less tech debt in the
`bzlmod` world later and need to migrate `bzlmod` users from the hard coded
value to something that can be configured.
This should be backwards compatible because of the default `int` value of `1`
for the `patch_strip` attribute.
Summary:
- feat: add `patch_strip` to `python_repository`.
- feat: add the default value of patch_strip to get_release_info.
- refactor: handle patch_strip key in `TOOL_VERSIONS`.
Work towards #2081.
> feat(toolchain): add patch_strip attr for python_repository

- CHANGELOG.md
- python/private/common/py_runtime_rule.bzl
- tests/py_runtime/py_runtime_tests.bzl
This changes `py_runtime` to get its interpreter version from the `--python_version` flag if
it wasn't explicitly specified. This is useful in two contexts:
For the runtime env toolchains, a local toolchain, or platform interpreter (basically any
py_runtime without a known version), it allows getting some Python version into the
analysis phase, which allows e.g. precompiling.
For environments using embedded Python, it allows defining fewer (e.g. 1) `py_runtime`
target instead of one for every Python version. This is because `py_runtime` serves a minor
role in such builds.
> feat: default `py_runtime` version info to `--python_version`

- examples/bzlmod/MODULE.bazel.lock
- python/private/BUILD.bazel
- python/private/config_settings.bzl
- python/private/full_version.bzl
- python/private/pypi/BUILD.bazel
- python/private/pypi/multi_pip_parse.bzl
- python/private/pypi/whl_library_alias.bzl
- python/private/python.bzl
- python/private/python_repositories.bzl
- python/private/pythons_hub.bzl
- python/private/toolchains_repo.bzl
This PR just makes the `MINOR_MAPPING` overridable and explicit in
many macros/rules that we own. Even though technically new API is
exposed, I am not sure if it is possible to use it and I am not sure
if we should advertise it.
Explicit minor_mapping results in easier wiring of `python.override`
`bzlmod` extension tag class planned for #2081.
> refactor(internal): make the usage of MINOR_MAPPING variable explicit in full_version

- examples/bzlmod/MODULE.bazel.lock
- python/private/BUILD.bazel
- python/private/pypi/BUILD.bazel
- python/private/pypi/extension.bzl
- python/private/semver.bzl
- tests/semver/BUILD.bazel
- tests/semver/semver_test.bzl
This `semver` function may turn out to be useful in validating
the input for the `python.*override` tag classes to be added in
a followup PR. Because this is a refactor of an existing code and
adding tests, I decided to split it out.
For a POC see #2151, work towards #2081.
> refactor(internal): add a semver parsing utility function

- docs/api/rules_python/python/cc/index.md
- docs/api/rules_python/python/index.md
- docs/index.md
- docs/toolchains.md
- sphinxdocs/docs/sphinx-bzl.md
- sphinxdocs/inventories/bazel_inventory.txt
- sphinxdocs/src/sphinx_bzl/bzl.py
From the discussion in #2216, it's clear that some better docs are needed to help people
figure out how to define a toolchain and what the different pieces me.
This gives some more explanation of the toolchain types, what they do, and how to
define them.
Along the way:
* Add some more bazel objects to the inventory
* Fix attribute lookups in the bazel inventory
* Allow using parens in crossrefs, e.g. `foo()`
> docs: give some general guidance on how to define custom toolchains

- CHANGELOG.md
- docs/BUILD.bazel
- docs/api/rules_python/python/cc/index.md
- docs/api/rules_python/python/index.md
- docs/toolchains.md
- python/BUILD.bazel
- python/cc/BUILD.bazel
- python/private/BUILD.bazel
- python/private/py_cc_toolchain_macro.bzl
- python/private/py_cc_toolchain_rule.bzl
- python/private/py_exec_tools_toolchain.bzl
- python/py_exec_tools_info.bzl
- python/py_exec_tools_toolchain.bzl
- sphinxdocs/inventories/bazel_inventory.txt
- sphinxdocs/src/sphinx_bzl/bzl.py
When writing the toolchain docs, I realized there wasn't a public target to use for
disabling the exec_interpreter.
Fixed by adding an alias to the internal target.
Along the way:
* Add the exec tools and cc toolchains to the doc gen
* A few improvements to the cc/exec tools docs
* Add public bzl file for py_exec_tools_toolchain and PyExecToolsInfo
* Fix a bug in sphinx_bzl where local names were hiding global names even if the
requested type didn't match (e.g. a macro foo referring to rule foo)
* Fix xrefs in the python/cc/index.md; it wasn't setting the default domain to bzl
* Fix object type definition for attributes: the object type name was "attribute",
but everything else was using "attr"; switched to "attr"
> feat: add //python:none as public target to disable exec_interpreter

- CHANGELOG.md
- python/versions.bzl
This function that allows us to generate config settings for
supported platforms did not get the flag_values addition.
> fix(platforms): include flag_values in config_settings

- CHANGELOG.md
Prep for 0.36.0 release (can be tagged after this PR is merged).
> chore: prepare 0.36.0 release

- python/private/python_repository.bzl
Previously this set the install name of the binary, which is put into
any binaries that link this, as an absolute path that is user specific.
Instead this can be fetched relatively, and bazel will automatically
handle adding the correct rpaths for this.
> Remove absolute path from libpython.dylib

- python/private/BUILD.bazel
- python/private/util.bzl
This avoids the tag being added when it doesn't need to be, which can look confusing to users without context about what it means.
Work towards #1361
> chore: don't add migration tag if Starlark implementation is enabled

- CHANGELOG.md
- python/private/whl_filegroup/extract_wheel_files.py
- tests/whl_filegroup/extract_wheel_files_test.py
Why this change is being made, briefly.
* We need to also get the `RECORD` file from a wheel in order to package everything
* It seems a bit weird to me that the `RECORD` file is *not part* of `whl_filegroup` even no pattern filtering was applied (or I am misunderstanding something)
* Further: neither `hash` nor `filelen` have been used in the code, so why are only files considered with those attributes?
> fix(whl_filegroup): Make RECORD from wheel available

- CHANGELOG.md
- python/private/py_wheel.bzl
- tools/wheelmaker.py
This is useful for development where, for large wheels, a significant
portion of the time can be spent compression native binaries
Fixes https://github.com/bazelbuild/rules_python/issues/2240
> feat: add py_wheel.compress to control using compression

- CHANGELOG.md
- python/private/common/py_runtime_rule.bzl
This defaults `py_runtime.implementation_name` to `cpython`, the value that is most likely
to be used. This is done not only because it's the most likely value, but because of how
it affects whether precompiling works.
Within py_runtime, automatically computing `pyc_tag` requires both `implementation_name`
and Python version information. With upcoming changes to make `--python_version` always
set to the correct value, it'll make enabling precompiling easier, especially if there
are custom toolchains defined.
> feat(toolchains): default py_runtime.implementation_name to cpython

- CHANGELOG.md
- docs/api/rules_python/python/config_settings/index.md
- examples/bzlmod/MODULE.bazel.lock
- python/private/config_settings.bzl
- python/private/pypi/config_settings.bzl
- python/private/pypi/generate_whl_library_build_bazel.bzl
- tests/config_settings/construct_config_settings_tests.bzl
- tests/pypi/generate_whl_library_build_bazel/generate_whl_library_build_bazel_tests.bzl
With this change the users can simply reuse our internal flag that will
correctly report the `X.Y` version in `select` statements. If users
previously depended on now removed `is_python_config_setting` now they
have an alternative.
Followup to #2253
> feat(toolchains): expose the //python/config_settings:python_version_major_minor

- CHANGELOG.md
- examples/wheel/lib/BUILD.bazel
- examples/wheel/wheel_test.py
- python/private/pypi/repack_whl.py
- python/private/whl_filegroup/extract_wheel_files.py
- tests/whl_filegroup/extract_wheel_files_test.py
- tools/wheelmaker.py
The `RECORD` file written when wheels are patched using `pip.override()` is not quoting filenames as needed, so wheels that (unfortunately) include files whose name contain commas would be written in such a way that https://pypi.org/project/installer/ would fail to parse them, resulting in an error like:
```
installer.records.InvalidRecordEntry: Row Index 360: expected 3 elements, got 5
```
This PR fixes that by using `csv` to read and write `RECORD` file entries which takes care of quoting elements of record entries as needed. See PEP376 for more info about the `RECORD` file format here: https://peps.python.org/pep-0376/#record
Fixes #2261
> fix(py_wheel): Quote wheel RECORD file entry elements if needed

- CHANGELOG.md
- examples/bzlmod/MODULE.bazel.lock
- python/private/pypi/whl_library.bzl
With the current behavior, we see really long progress messages in the console like
```
Running whl_library.ResolveRequirement(foobar_pip_deps_regex, regex==2023.12.25     --hash=sha256:0694219a1d54336fd0445ea3\
82d49d36882415c0134ee1e8332afd1529f0baa5
<many more lines of --hash values>
```
This spams the console and isn't very useful.
To fix, only print up to the first white space, which captures the important information
(e.g. "regex==2024.12.25") and is brief.
Closes https://github.com/bazelbuild/rules_python/issues/2206
> fix(whl_library): avoid excessive report_progress() messages

- docs/api/rules_python/python/runtime_env_toolchains/index.md
This stems after some conversation with a user where they were surprised that building C extensions wasn't working when using the runtime env toolchain.
> docs: clarify that the runtime env toolchains don't provide build info

- CHANGELOG.md
- python/private/pypi/pip_compile.bzl
> fix: pass kwargs `env` to both update and test targets

- CHANGELOG.md
- python/private/BUILD.bazel
- python/private/python.bzl
- python/private/python_register_toolchains.bzl
While migrating to bzlmod, users may have a hybrid build where WORKSPACE contains
python_register_toolchain() calls. Because these calls originate from WORKSPACE files,
the `native.register_toolchain` APIs are still available. At the same time, we still
detect that bzlmod is enabled, and thus disable calling those functions. The net
effect is, users aren't able to register toolchains in such a hybrid setup. At the
same time, because the code path is shared, we can't have the bzlmod toolchain code
try to call them, as it'll fail.
To accomodate both cases, have the bzlmod toolchain code pass a special arg so that
`python_register_toolchains` knows to skip parts that don't apply to the bzlmod toolchain
invocation.
This was all unwound by some users and pointed out in a Slack thread. A few …
> fix(bzlmod): let workspace-invoked python_register_toolchains to register toolchains

- CHANGELOG.md
- examples/bzlmod/MODULE.bazel.lock
- python/private/pypi/patch_whl.bzl
- python/private/pypi/whl_library.bzl
Previously if you pulled multiple wheels of the same dep, even ones not affected by patches would be processed, which is expensive for larger wheels because of the unzipping / re-zipping.
Fixes https://github.com/bazelbuild/rules_python/issues/2263
> fix(pip): skip wheel patching with empty patches

- python/private/common/py_binary_rule_bazel.bzl
- python/private/common/py_library_rule_bazel.bzl
- python/private/common/py_runtime_rule.bzl
- python/private/common/py_test_rule_bazel.bzl
The Bazel docs link to the implementation files, which were recently moved. To avoid users getting a 404, add stub files with some text to direct them somewhere useful.
Work towards https://github.com/bazelbuild/bazel/issues/24014
> docs: add stubs so Bazel docs link to a valid file

- sphinxdocs/private/proto_to_markdown.py
- sphinxdocs/tests/proto_to_markdown/proto_to_markdown_test.py
This fixes a bug where tag-classes/functions that didn't have a doc string, but did
have arguments/attributes, would render the args/attrs immediately after the directive
line, which made them get interpreter as direction options (settings that apply to
the overall directive) instead of doc fields nested within the directive (separate
block-level elements that get rendered).
To fix, update the code to ensure there's a newline between the directive line and
subsequent arg/attr lines. Also adds tests for this.
> sphinxdocs: fix rendering of args in directives with empty doc

- python/extensions/python.bzl
The file doc string used increasing colon-counts for directives (a 3-colon directive contained a 4-colon directive), which messes up subsequent nesting later on the page.
To fix, use 4 colons for the outer topic and 3 for the inner topic.
> docs: fix rendering of python extension

- CHANGELOG.md
The changelog header text doesn't turn into nice linkable ids. e.g. the "0.37.0" header
is simply "id1" (and similar for all the other headers).
To fix, use block attributes (made possible by the MyST attrs_block extension) to give them
ids manually. The ids start with "v" and use dashes because a dotted number isn't
accepted as a valid id.
It was a bit tedious to update all the headers with ids, so I only did it for the last few
releases.
> docs: give user-friendly permalinks in changelog

- .bazelci/presubmit.yml
This is per https://github.com/bazelbuild/rules_python/pull/2293#issuecomment-2407749777
From what I can tell ubuntu1604 is very old and not well supported.
> ci: upgrade to rbe_ubuntu2004

- docs/precompiling.md
typo: due Python -> due to Python
> docs: fix typo in precompiling docs

- CHANGELOG.md
Update the headers and sections for the 0.37.1 release.
> docs: update changelog for 0.37.1

- sphinxdocs/docs/index.md
- sphinxdocs/docs/readthedocs.md
This comes from setting up readthedocs integration with rules_testing.
It'd be nice if so much copy/paste wasn't necessary, but I'm not sure how to best
reduce that, so at the least, document what one has to do.
> docs: tell how to setup readthedocs integration with sphinxdocs

- CHANGELOG.md
- python/private/py_repositories.bzl
- tests/integration/compile_pip_requirements/WORKSPACE
- tests/integration/ignore_root_user_error/WORKSPACE
- tests/integration/pip_parse/WORKSPACE
- tests/integration/py_cc_toolchain_registered/WORKSPACE
In order for WORKSPACE to work with newer bazel versions, rules_cc 0.0.13 or higher is
necessary. rules_cc then requires a newer protobuf version.
Note I couldn't figure out the minimum protobuf version, but 27.0 seems to work OK.
AFAIK only WORKSPACE is affected. Our bzlmod uses 0.0.9 and hasn't had issues.
Fixes https://github.com/bazelbuild/rules_python/issues/2310
> deps: use rules_cc 0.0.13 to support newer bazel versions

- .github/workflows/create_archive_and_notes.sh
The generated release notes provide some very simple copy/paste quick start, but don't
tell where to find more detailed info. Link to our main docs so users know where to
find out more.
Along the way:
* Drop Bazel 6 mention. It'll be unsupported pretty soon.
* Drop "bzlmod is beta" mention, since the APIs are stable enough (and stability is
better covered in other docs which can handle the nuance of what is/isn't GA)
> docs: link to main docs in generated release notes

- .bcr/metadata.template.json
It seems that it got removed in bazelbuild/bazel-central-registry#2838
> chore: add aignas to the BCR maintainers

- python/private/py_executable.bzl
* There is no such method `common_runfiles.add_runfiles`; use `add_targets()` instead. This
only occurs when there are extra deps, which currently only Google-patches trigger.
* The docs say that `BuiltinPyInfo` might be None, but that case is not handled here. This
occurs in newer Bazel versions where the builtin PyInfo has been removed.
> fix: breakages in unused codepaths after recent refactors

- .gitattributes
- CHANGELOG.md
- python/features.bzl
This adds a `features.version` value that is populated by git when `git archive` is run. This means it will be expanded when our release action runs to the tag name. Otherwise, it isn't expanded. When it isn't expanded, the value is set to the empty string.
> feat: add features.version value

- examples/bzlmod/MODULE.bazel
- examples/bzlmod/MODULE.bazel.lock
Under Bazel 8, the bzlmod example is failing because newer versions of some dependencies
request Python 3.8 to be available.
To fix, just comment out the restriction in the example. The example has a somewhat
large dependency footprint, so enforcing this restriction seems untenable. The config is 
left commented out so users can discover the feature.
Fixes https://github.com/bazelbuild/rules_python/issues/2361
Work towards https://github.com/bazelbuild/bazel-central-registry/issues/3056
> tests: don't restrict python versions in bzlmod example

- CHANGELOG.md
- examples/bzlmod/MODULE.bazel.lock
- python/private/pypi/whl_library.bzl
Fixes #2328.
In #2126, we discussed and added `--no-build-isolation` to ensure that sdist builds pulled from rules_python supplied dependencies. An unanticipated/misunderstood side-effect of this is that pip will no longer resolve necessary, declared build time dependencies from a package index. That's a significant point of friction for users, and, it's much harder to opt-out of the behavior than to opt-in given the presence of `extra_pip_args`.
> fix: Remove --no-build-isolation from pip install command

- python/private/py_info.bzl
The docs previously somewhat implied that the `srcs` were always present, which isn't true
for e.g. pyc-only builds.
> docs: clarify that PyInfo.transitive_sources may not include py files

- CHANGELOG.md
- examples/bzlmod/MODULE.bazel.lock
- python/private/pypi/extension.bzl
- tests/pypi/extension/extension_tests.bzl
Before this change the `extra_pip_args` would not be passed down the
chain if `experimental_index_url` is set. This adds a test and fixes the
bug.
> fix(pypi): correctly pass `extra_pip_args` when building sdists

- CHANGELOG.md
- examples/bzlmod/MODULE.bazel.lock
- python/private/pypi/patch_whl.bzl
- tests/pypi/patch_whl/BUILD.bazel
- tests/pypi/patch_whl/patch_whl_tests.bzl
Before this change the installation of the patched wheels using `uv` or
similar would break. This change fixes that by using local version
specifier, which is better than using a build tag when installing the
wheels.
Before the change:
```console
$ cd examples/bzlmod
$ bazel build @pip//requests:whl
$ uv pip install <path to requests wheel in the example>
error: The wheel filename "requests-2.25.1-patched-py2.py3-none-any.whl" has an invalid build tag: must start with a digit
```
After:
```
$ uv pip install <path to requests wheel in the example>
Resolved 5 packages in 288ms
Prepared 5 packages in 152ms
Installed 5 packages in 13ms
+ certifi==2024.8.30
+ chardet==4.0.0
+ idna==2.10
+ requests==2.25.1+patched (from file:///home/aignas/src/github/aignas/rules_python/examples/bzlmod/bazel-bzl …
```
> fix(pypi): use local version specifiers for patched whl output

- .bazelci/presubmit.yml
- CHANGELOG.md
- examples/bzlmod/BUILD.bazel
- examples/bzlmod/MODULE.bazel
- examples/bzlmod/MODULE.bazel.lock
- python/private/pypi/extension.bzl
- python/private/pypi/hub_repository.bzl
- python/private/pypi/render_pkg_aliases.bzl
- tests/pypi/extension/extension_tests.bzl
Before this change, it was impossible for users to use the targets
created with `additive_build_content` whl annotation unless they relied
on the implementation detail of the naming of the spoke repositories and
had `use_repo` statements in their `MODULE.bazel` files importing the
spoke repos.
With #2325 in the works, users will have to change their `use_repo`
statements, which is going to be disruptive. In order to offer them an
alternative for not relying on the names of the spokes, there has to be
a way to expose the extra targets created and this PR implements a
method. Incidentally, the same would have happened if we wanted to
stabilize the #260 work and mark `experimental_index_url` as
non-experimental anymore.
I was hoping we could autodetect them by parsing the build content …
> fix(bzlmod): allow users to specify extra targets to be added to hub repos

- sphinxdocs/private/sphinx.bzl
- sphinxdocs/tests/sphinx_docs/BUILD.bazel
- sphinxdocs/tests/sphinx_docs/conf.py
- sphinxdocs/tests/sphinx_docs/defs.bzl
- sphinxdocs/tests/sphinx_docs/index.md
The logic to relocate files assumed that all the inputs were plain file artifacts. When
a directory artifact was used, then `ctx.actions.symlink()` would fail because it requires
the output artifact and input target artifact to be the same type of file (plain file or
directory).
To fix, use `File.is_directory` to detect if the input is a directory or file, then call
`declare_file()` or `declare_directory()` as appropriate. The later `symlink()` call is
then happy the two args match.
Fixes https://github.com/bazelbuild/rules_python/issues/2374
> fix: make sphinxdocs support directory inputs

- .bazelci/presubmit.yml
The name was using "integration" when it should have been "generation"
> tests: fix the job name for the debian bzlmod gazelle job

- CHANGELOG.md
When making a Slack announcement I noticed that the changelog could be clarified.
> chore: improve the CHANGELOG for the new release

- CHANGELOG.md
- examples/bzlmod/MODULE.bazel.lock
- python/private/pypi/extension.bzl
With this PR we are changing the defaults in the upcoming `0.39` version, and
if all goes well, the release after that will be `1.0`.
Work towards #1361
> chore: change the parse_all_requirements_files default value

- CHANGELOG.md
- python/private/BUILD.bazel
- python/private/py_runtime_info.bzl
- python/private/py_runtime_rule.bzl
This adds attributes and fields for storing the runtimes ABI flags value, i.e. `sys.abiflags`.
For freethreaded interpreters, the abi flags contain `t`, which is used creating e.g.
virtualenvs.
The attribute can be directly specified, or if it's not, will be computed based on the
`--py_freethreaded` flag.
> feat: add attrs/fields for the runtime's ABI flags

- CHANGELOG.md
- python/private/common_bazel.bzl
When the `@bazel_tools//python/tools:python_autodetecting` toolchain is used, it returns
the Bazel-builtin PyRuntimeInfo provider. Because this provider doesn't support the
additional fields needed for precompiling (`pyc_tag`, among others), it would result in
an attribute error.
To fix, detect the absence of the `pyc_tag` attribute and return early, as is done when
the pyc_tag field is empty.
Fixes https://github.com/bazelbuild/rules_python/issues/2364
> fix: skip precompiling if using Bazel-builtin PyRuntimeInfo

- .bcr/config.yml
- .bcr/gazelle/metadata.template.json
- .bcr/metadata.template.json
Just tidy up the config. I've put my name in there, but I am happy to make the
BCR app use someone else's name as well. @oprypin, @rickeylev, what do you
think?
> chore: remove Thulio from BCR app configs

- CHANGELOG.md
Update changelog for 0.39.0 release
Along the away, stash a template for the "Unreleased" text in a comment for easier copy/pasting
in the future.
> chore: update changelog for 0.39.0

- .bcr/gazelle/presubmit.yml
- .bcr/presubmit.yml
This removes Bazel 6 and adds last_rc (Bazel 8) in our BCR presubmit config. Right now, BCR releases fail because they try to test with Bazel 6, which doesn't work.
> chore: change bcr presubmit to drop bazel 6, add last_rc (bazel 8)

- .bazelci/presubmit.yml
Run the bzlmod example with last_rc to match the BCR config. This should help catch any
issues before a BCR release occurs.
Along the way, cleanup the extraneous pystar configs. The rules_python Starlark
implementation is enabled by default, and disabling it is unsupported.
> ci: add last_rc, remove extraneous pystar configs

- CHANGELOG.md
- python/private/common.bzl
The collect_imports() function added import strings from BuiltinPyInfo if it was non-None.
However, operator precedence caused the `if-else` ternary to ignore both list comprehensions
(one for PyInfo and one for BuiltinPyInfo) if BuiltinPyInfo was None.
To fix, I rewrote the function as a regular for loop to eliminate the ambiguous looking
ternary expression.
Fixes: https://github.com/bazelbuild/rules_python/issues/2414
> fix: keep import path values if Bazel-builtin PyInfo is removed

- docs/precompiling.md
Someone one Slack asked if this was possible and how to do, so document it for better
visibility. There's a lot of flags, so its easy to not see how to do this.
> docs: tell how to do pyc-only builds

- docs/precompiling.md
Regular md docs need the `bzl:` prefix. Without it, the string doesn't render at all.
> docs: fix refs to precompile source retention flag/attr in precompiling docs

- CHANGELOG.md
- gazelle/python/file_parser.go
While investigating #2396 and why #2413 doesn't appear to be working for us, I realized that one of the things I was making heavy use of was additional parser logging that I had added. This adds some of that logging. I also throw in some documentation because I found it helpful.
Users can (attempt to) get additional parse failure information by setting the `GAZELLE_VERBOSE` environment variable to `1`. Eg:
```console
$ GAZELLE_VERBOSE=1 bazel run //:gazelle
```
Here are some example logs:
```console
$ GAZELLE_VERBOSE=1 bazel run //:gazelle
INFO: Invocation ID: a4e026d8-17df-426c-b1cc-d3980690dd53
...
INFO: Running command line: bazel-bin/gazelle
INFO: Streaming build results to: https://btx.cloud.google.com/invocations/a4e026d8-17df-426c-b1cc-d3980690dd53
gazelle: WARNING: failed to parse …
```
> refactor: Add GAZELLE_VERBOSE env and log parser failures

- CHANGELOG.md
- examples/bzlmod/MODULE.bazel.lock
- python/uv/private/versions.bzl
`uv` cannot be used on aarch64-apple-darwin computers because the sha256sum is incorrect.
The correct version can be seen [here](https://github.com/astral-sh/uv/releases/download/0.4.25/uv-aarch64-apple-darwin.tar.gz.sha256).
Fixes #2411
> fix(uv): Fix sha256 for uv binary for aarch64-apple-darwin

- CHANGELOG.md
- docs/environment-variables.md
- gazelle/python/file_parser.go
Address PR comments from #2420:
+ Add and update comments
+ idiomatic go: return early
+ rename and document env var
> chore(gazelle): Rename GAZELLE_VERBOSE env var; use idiomatic go; add comments

- .bazelci/presubmit.yml
- tests/integration/local_toolchains/test.py
The CI setups claiming to run in WORKSPACE mode were wrong. This fixes it.
Disable integration tests on Windows WORKSPACE mode. They are failing: https://buildkite.com/bazel/rules-python-python/builds/9791#01934eac-3a03-445d-ad53-6683371ca289
Example failure: `java.lang.UnsatisfiedLinkError: 'int com.google.devtools.build.lib.windows.WindowsFileOperations.nativeIsSymlinkOrJunction(java.lang.String, boolean[], java.lang.String[])'`
> tests: make workspace CI jobs enable workspace mode

- tests/base_rules/base_tests.bzl
- tests/base_rules/py_info/py_info_tests.bzl
- tests/config_settings/transition/multi_version_tests.bzl
- tests/py_runtime_pair/py_runtime_pair_tests.bzl
In Bazel 9, the builtin symbols don't exist. This fixes some tests that fail when those symbols
are missing.
> tests: make some tests compatible with Bazel 9 fix various tests relying on Bazel builtin providers existing

- python/private/py_executable_bazel.bzl
- python/private/stage1_bootstrap_template.sh
- tests/bootstrap_impls/BUILD.bazel
- tests/bootstrap_impls/a/b/c/BUILD.bazel
- tests/bootstrap_impls/a/b/c/nested_dir_test.py
- tests/bootstrap_impls/venv_relative_path_tests.bzl
Computing the relative path from the venv interpreter to the underlying interpreter was
incorrectly using the actual interpreter's directory depth, not the venv interpreter's
directory depth, when computing the distance from the venv interpreter to the runfiles root.
The net effect is the correct relative path would only be computed for binaries with
the same directory depth as the actual interpreter (e.g. 2).
This went undetected in CI because the tests for this logic just happen to have the
same directory depth as the actual interpreter used.
To fix, compute the relative path to the runfiles root using the venv interpreter
directory. Also added a test in a more nested directory to test this case.
Along the way:
* Change relative path computation to compute a minimum relative path.
* Fix …
> fix: correctly obtain relative path required for the venv created by `--bootstrap_impl=script`

- sphinxdocs/private/sphinx.bzl
This ensures tags like `manual` (and other attributes) are copied into the `{name}.run`
target and properly respected.
Fixes https://github.com/bazelbuild/rules_python/issues/2441
> fix: Propagate common kwargs to sphinx_run

- CHANGELOG.md
- MODULE.bazel
bazel_features has a bug where it doesn't detect Bazel 8 rc3 correctly. This is 
fixed in release 1.21.0.
From the discussion on https://github.com/bazel-contrib/bazel_features/issues/82,
it's likely this only occurs due to the "rc" notation of the Bazel release, so an
earlier bazel_features version will probably work fine once Bazel 8 is no longer rc.
> fix: upgrade to bazel_features 1.21.0 for Bazel 8 rc3 support

- python/private/pypi/extension.bzl
- python/private/pypi/render_pkg_aliases.bzl
- python/private/pypi/whl_config_setting.bzl
- tests/pypi/extension/extension_tests.bzl
- tests/pypi/render_pkg_aliases/render_pkg_aliases_test.bzl
It seems that during #2424 I broke the rendering of aliases for the
cases when the target platform is set. This means that the feature for
multiplatform whls when `experimental_index_url` has never worked even
though it was advertised. This ensures that the rendering is happening
correctly and adds extra missing tests.
Whilst at it:
- add an extra test for `pip.parse` handling of env markers that I added
to ensure that the error is not in the module extension.
- Cleanup unused code - error message constant and the repo arg in
`whl_config_setting`.
Fixes #2446
> fix(render_pkg_aliases): correctly render when we have target_platforms set

- CHANGELOG.md
- MODULE.bazel
Stardoc 0.7.2 fixes a bug with Bazel 8 where a symbol was undefined. Upgrading to that
version makes the Bazel 8 CI job that builds our docs pass.
Fixes https://github.com/bazelbuild/rules_python/issues/2448
> deps: upgrade to stardoc 0.7.2 for Bazel 8 support

- .github/workflows/release.yml
This makes the release workflow automatically compute the prelease setting based on the
tag name being processed. It looks for the "-rc" text in the tag to do this.
> chore: auto compute prelease setting

- CHANGELOG.md
- python/runfiles/runfiles.py
- tests/runfiles/runfiles_test.py
Bazel 7.4.0 introduced support for all characters in runfile source and target paths: https://github.com/bazelbuild/bazel/pull/23912
This is a backwards-compatible change, based on a similar change in rules_go: https://github.com/bazel-contrib/rules_go/pull/4136
> feat(runfiles): add support for spaces and newlines in runfiles paths

- MODULE.bazel
The rules_bazel_integration_test rules had a missing load for sh_binary. This is fixed
in release 0.27.0.
> fix: upgrade to rules_bazel_integration_test 0.27.0 for bazel 9 compatibility

- python/private/pypi/pkg_aliases.bzl
Summary:
* Add more flag values that we actually use.
* Point users to online docs.
I still think it is not good enough when somebody needs to debug, but I
am not sure what to add. Maybe we just need user documentation outlining
what each config setting means and what values it is using? Maybe we
should generate the config settings inside the `rules_python` repository
so that we have better visibility into what needs to be documented and
explained.
> doc: improve alias error msg in pip hubs

- CHANGELOG.md
- python/private/pypi/dependency_resolver/dependency_resolver.py
`compile_pip_requirements` doesn't work as expected on Windows unless both `--enable_runfiles` and `--windows_enable_symlinks` are used. Both options default to off on Windows because the filesystem on Windows makes setting up the runfiles directories with actual files very slow. This means that anyone on Windows with a default set up has to search around the Github issues to try and figure out why things don't work as advertised.
The `dependency_resolver.py` doesn't inherently require these options, it just had two bugs that prevented it from working.
1. calling pip_compile exits the whole program so it never gets to run the code that should copy the output to the source tree. Things just happen to work on linux because the runfiles are symlinks, and it does not need to copy anything.
2. …
> fix: dependency resolver on windows only works when --enable_runfiles and --windows_enable_symlinks is used

- python/private/BUILD.bazel
- python/private/api/BUILD.bazel
The distribution file groups are mostly used by integration tests, not releases, so these
filegroups missing doesn't usually cause a problem.
This was found when importing rules_python into Google, where filegroups of the rules sources
are fed into various tests.
> fix: add missing api distribution target

- docs/toolchains.md
Mention where register_toolchains() should be when defining custom toolchains. Also link
to the Bazel docs about toolchains.
This stems from Slack discussion where someone was trying to define custom toolchains and
got hung up on the last step or registering them.
> docs: mention calling register_toolchains in custom toolchain docs

- tests/cc/current_py_cc_libs/BUILD.bazel
Also explicitly include ABI3 in the name of the other Windows-only testcase, since that is the whole point of the test, and no ABI3-only libs exist on non-Windows platforms.
-----------
Follow-up of #1820.
> test: Enable non-ABI3 libs linking test for Windows

- gazelle/python/generate.go
This is a code error (from typo).
> fix(gazelle): empty list

- CHANGELOG.md
Fixes #1361
Closes #2459 as won't do
> chore: bump the changelog to 1.0

- .bazelci/presubmit.yml
- examples/pip_repository_annotations/.bazelrc
- examples/py_proto_library/.bazelrc
Bazel 9 won't support workspace builds, so skip them in the Bazel@head pipeline. The bzlmod
equivalents of these examples is covered elsewhere.
Along the way, enable workspace by default in the examples for a bit of futureproofing.
Work towards https://github.com/bazelbuild/rules_python/issues/2469
> tests: skip workspace-specific examples for bazel 9

- .bazelignore
If the examples/pip_repository_annotations had build performed in it, then outer invocations
try to traverse the symlink, wasting memory and causing errors.
To fix, add the path to `.bazelignore` so bazel doesn't try to visit it.
> chore: ignore examples/pip_repository_annotations bazel-bin symlink

- python/private/pypi/BUILD.bazel
- python/private/pypi/pip_compile.bzl
This is for overall code hygiene, but also because it seems to make some progress on Bazel 9
being able to load files in WORKSPACE mode (something about defs.bzl triggers loading
more symbols which can't be found)
Work towards https://github.com/bazelbuild/rules_python/issues/2469
> chore: use per-rule loads in pip_compile.bzl

- examples/multi_python_versions/tests/BUILD.bazel
- examples/multi_python_versions/tests/version_test.sh
This is basically part of #2395, but for the workspace test. Same as that PR, the `$(rootpath)`
expansion isn't valid for a target with multiple outputs. To fix, use `$(rootpaths)` and parse
out the particular value of interest.
Work towards https://github.com/bazelbuild/rules_python/issues/2469
> tests: make multi_python_versions pass with Bazel 9 workspace

- python/private/python_bootstrap_template.txt
When the shell test invokes the python binary, it uses a combination of forward slashes and
backslashes. Under Bazel 9, that mixture of slashes is preserved. This later breaks a regex
that looks for the OS-specific path separator.
To fix, normalize forward slashes to the OS path separator.
Oddly, it's not Bazel that is passing the mixture of slashes (it's the shell), but behavior seems to
vary based on which version of Bazel is used.
Along the way, copy the nicer `print_verbose` function from the stage2 bootstrap into the old
bootstrap. It prints debug information in a nicer format.
Work towards https://github.com/bazelbuild/rules_python/issues/2469
> fix: normalize argv0 so runfiles root can be found on windows with bazel 9

- MODULE.bazel
- python/config_settings/BUILD.bazel
- python/private/pypi/config_settings.bzl
- python/private/pypi/pkg_aliases.bzl
- python/private/pypi/whl_library.bzl
- python/private/pypi/whl_target_platforms.bzl
- tests/pypi/config_settings/config_settings_tests.bzl
- tests/pypi/pkg_aliases/pkg_aliases_test.bzl
- tests/pypi/whl_target_platforms/select_whl_tests.bzl
With this we:
* Fix the previous behaviour where `abi3` wheels would be selected when
freethreaded builds are selected. Whilst this may work in practise
sometimes, I am not sure it has been supported by reading PEP703.
* Start selecting `cp313t` wheels when we scan what is available on PyPI.
* Ensure that the `whl_library` repository rule handles `cp313t` wheel
extraction.
* Generate `cp313t` config_settings so that we can use them in
`pkg_aliases`.
* Generate `cp313t` references in `pkg_aliases` macro.
* Add the 3.13 deps to dev_pip for testing.
Also tested by manually running:
```
$ bazel cquery --//python/config_settings:python_version=3.13 --//python/config_settings:py_freethreaded=yes 'kind("py_library rule", deps(@dev_pip//markupsafe))'
INFO: Analyzed target …
```
> feat(pypi): support freethreaded in experimental_index_url

- CHANGELOG.md
- python/private/py_wheel.bzl
Clean macOS installs place `python` in `/usr/local/bin`, which is not searched by default when calling `actions.run()`. This caused builds to fail when they were executing python tools on an unmodified macOS host.
> fix: Make sure wheelmaker uses the default shell env

- CHANGELOG.md
- python/BUILD.bazel
- python/defs.bzl
This removes re-exporting the `find_requirements` aspect from `@bazel_tools`.
The find_requirements aspect is only useful for analyzing the `srcs_version` relationship
between targets, which was only needed as part of the Python 2 to 3 upgrade. With Python
2 no longer supported, it's defunct.
Removing it entirely because I can't find any real references to it in the wild. It looks
entirely unused.
> chore: remove find_requirements re-export from bazel_tools

- CHANGELOG.md
> doc: freethreaded support changelog

- WORKSPACE
Building with Bazel 9 using WORKSPACE results in an odd error that `PyInfo`
isn't defined. Oddly, the error refers to `rules_python/python/private/reexports.bzl`
for rules_python 0.28.0. This seems to only happen when the main module is rules_python.
While Bazel 9 is supposed to drop workspace support, I've been advised it's better to
keep testing WORKSPACE support until closer to when Bazel 9 fully removes it.
My best guess about what's happening is Bazel's autoloading is triggering and somehow
defining rules_python before it's recognized that the main module is rules_python.
The autoloading appears to be triggered, eventually, by things in bazel_tools loading
rules_python.
While removing unnecessary `@bazel_tools` loads in rules_python helps, the particular
case I can't find a clean …
> fix: make bazel 9 workspace recognize rules_python as the main module

- CHANGELOG.md
- python/private/pypi/pip_repository.bzl
The code path pip_parse follows when using a WORKSPACE file with
use_hub_alias_dependencies enabled forgets to pass requirement cycles
along to alias creation, leading to the _groups package never being
created and aliases skipping them.  Requirement cycles are just ignored
entirely.  In this patch we attempt to fix that so grouping works more
or less the same way as it does under bzlmod with that flag enabled.
> fix(pypi): Fix use_hub_alias_dependencies with WORKSPACE

- docs/toolchains.md
The code example comment uses `toolchain_impls` (extra s), while the target references
use `toolchain_impl` (no s). This made me go back and double-check when reading the
custom toolchain example (especially the definitions in L425ff).
Remove the extra "s" in the comment so it matches what the target references are.
> docs: Fix toolchain implementation file name

- docs/toolchains.md
- examples/pip_parse_vendored/README.md
This clarifies a few points about how to use the python interpreter in the repository
context. It also fixes outdated documentation as noted by some users of 1.0.
See discussion: https://github.com/bazelbuild/rules_python/discussions/2509
Fixes #2494
> doc: correct toolchain usage in repository_rule context docs

- .bazelignore
- CHANGELOG.md
- examples/bzlmod/.bazelignore
- examples/bzlmod/MODULE.bazel
- examples/bzlmod/py_proto_library/BUILD.bazel
- examples/bzlmod/py_proto_library/foo_external/BUILD.bazel
- examples/bzlmod/py_proto_library/foo_external/MODULE.bazel
- examples/bzlmod/py_proto_library/foo_external/nested/foo/my_proto.proto
- examples/bzlmod/py_proto_library/foo_external/py_binary_with_proto.py
- python/private/proto/py_proto_library.bzl
Previously, the import path within the runfiles was only correct for the case --legacy_external_runfiles=True (which copied the runfiles into `$RUNFILES/<main repo>/external/<external repo>/<path>` in addition to `$RUNFILES/<external repo>/<path>`. This flag was flipped to False in Bazel 8.0.0.
Fixes https://github.com/bazelbuild/rules_python/issues/2515.
Tested locally against the minimal reproducer in that issue.
> fix: py_proto_library: external runfiles

- CHANGELOG.md
- docs/api/rules_python/python/config_settings/index.md
- python/config_settings/BUILD.bazel
- python/private/config_settings.bzl
- python/private/pypi/pkg_aliases.bzl
- tests/pypi/pkg_aliases/pkg_aliases_test.bzl
With this change we get the current values of the python configuration
values printed in addition to the message printed previously. This
should help us advise users who don't have their builds configured
correctly.
We are adding an extra `build_setting` which we can set in order to get
an error message instead of a `DEBUG` warning. This has been documented
as part of our config settings and in the `no_match_error` in the
`select` statement.
Example output now
```console
$ bazel cquery --@rules_python//python/config_settings:python_version=3.12 @dev_pip//sphinx
WARNING: Build option --//python/config_settings:current_config has changed, discarding analysis cache (this can be expensive, see https://bazel.build/advanced/performance/iteration-speed).
DEBUG: …
```
> refactor(pypi): A better error message when the wheel select hits no_match

- python/private/pypi/extension.bzl
- python/private/pypi/parse_requirements.bzl
The warning is somewhat non-actionable and the sources can be
inspected via the MODULE.bazel.lock file if needed. This makes it
easier to make this option a default at some point.
At the same time cleanup the code since we are not using the
`get_index_urls` to print the warning.
> refactor: stop warning if we don't find anything via SimpleAPI

- CHANGELOG.md
- python/private/pypi/parse_requirements.bzl
- tests/pypi/extension/extension_tests.bzl
Later in the code we would only use the results of SimpleAPI
if the package has shas, so actually doing these calls is just
wasting time, because we would be dropping the results anyway.
Work towards #2100
> feat(pypi): only query SimpleAPI for pkgs that have shas

- python/private/pypi/extension.bzl
- python/private/pypi/whl_repo_name.bzl
- tests/pypi/whl_repo_name/whl_repo_name_tests.bzl
Summary:
- Move the `whl_library` creation into a separate function and remove
the `TODO` note.
- Move the creation of the `get_index_urls` functions into outer
`parse_modules` function and simplify the reproducible extension
setting logic.
- Remove the `prefix` parameter from the `*repo_name` functions.
- Add an extra error message, for ensuring that invariants are met.
> refactor(pypi): further cleanup of `pip.parse` code

- CHANGELOG.md
- python/private/attributes.bzl
- python/private/common.bzl
- python/private/py_executable.bzl
- python/private/py_info.bzl
- python/private/py_library.bzl
- tests/base_rules/base_tests.bzl
- tests/base_rules/py_info/py_info_tests.bzl
- tests/support/py_info_subject.bzl
This adds attributes and fields of use to static analysis.
For type definition files (usually `.pyi` files), the `pyi_srcs` and `pyi_deps`
fields are added to the rules. They end up in the PyInfo fields direct_pyi_files
and transitive_pyi_files.
So that static analysis tools can retain access to a target's Python source files,
even if precompiling is enabled, `direct_original_sources` and
`transitive_original_sources` fields are added to PyInfo.
Work towards https://github.com/bazelbuild/rules_python/issues/2537, https://github.com/bazelbuild/rules_python/issues/296
> feat: add pyi attributes/fields, original source fields

- CHANGELOG.md
- gazelle/python/testdata/dont_ignore_setup/BUILD.in
- gazelle/python/testdata/dont_ignore_setup/BUILD.out
- gazelle/python/testdata/dont_ignore_setup/README.md
- gazelle/python/testdata/dont_ignore_setup/test.yaml
- gazelle/python/testdata/python_ignore_files_directive/BUILD.out
- gazelle/pythonconfig/pythonconfig.go
Don't ignore `setup.py` files when running Gazelle.
Fixes #2108.
I believe that `setup.py` was originally ignored because it, when found that the repo root, is part of `setuptools` config and may have caused problems with Gazelle.
I've been running our Google Quantum code with this patch for a long while now and not seen any issues. I figured it was time to upstream it.
> fix(gazelle): Don't ignore `setup.py` files when running Gazelle

- CHANGELOG.md
- python/private/pypi/extension.bzl
- python/private/pypi/simpleapi_download.bzl
- tests/pypi/simpleapi_download/BUILD.bazel
- tests/pypi/simpleapi_download/simpleapi_download_tests.bzl
Instead of querying everything in parallel and yielding a lot of 404
warnings, let's query the main index first and then query the other
indexes only for the packages that were not yet found.
What is more, we can print the value of `experimental_index_url_overrides`
for the users to use.
Whilst at it, add a unit test to check the new logic.
Fixes #2100, since this is the best `rules_python` can do for now.
> fix(pypi): change the parallelisation scheme for querying SimpleAPI

- CHANGELOG.md
- python/private/pypi/deps.bzl
- python/private/pypi/evaluate_markers.bzl
- python/private/pypi/whl_library.bzl
This is reusing a bit of code used in `evaluate_markers` and makes use
of the RECORD files in the `whl` files that we use to extract whls in
`whl_library`. This should be merged before #2514 to avoid any cache
invalidation issues downstream.
Fixes #2468
> fix(whl_library): track sources in whl_library

- CHANGELOG.md
- python/private/pypi/dependency_resolver/dependency_resolver.py
- python/private/pypi/deps.bzl
We had an issue to install jaxlib with bazel when running the following command (using rules_python v0.39):
```bash
bazel test \
--repo_env=HERMETIC_PYTHON_VERSION=3.13-ft \
--repo_env=JAX_NUM_GENERATED_CASES=$JAX_NUM_GENERATED_CASES \
--repo_env=JAX_ENABLE_X64=$JAX_ENABLE_X64 \
--repo_env=JAX_SKIP_SLOW_TESTS=$JAX_SKIP_SLOW_TESTS \
--repo_env=PYTHON_GIL=$PYTHON_GIL \
--repo_env=TSAN_OPTIONS="halt_on_error=1" \
--//jax:build_jaxlib=false \
--nocache_test_results \
--test_output=all \
//tests:cpu_tests
```
According to @vam-google, this was due to old pip/packaging versions. We updated them and this helped to make work the whole building/testing pipeline: https://github.com/jax-ml/jax/pull/24898
So, we would like to upstream the patch: …
> Updated pip and packaging versions to work with free-threading packages

- .github/workflows/create_archive_and_notes.sh
- CONTRIBUTING.md
In a couple recent PRs, I put "VERSION_NEXT_{feature,patch}" as place holders since I
wasn't sure what the next appropriate version would be for unreleased code. e.g.
specifying `1.0.1` becomes invalid if a subsequent PR would make it `1.1.0`.
To help remind us to populate these values before a release, have the release workflow
check for the marker strings.
> chore: add check for version_next markers

- python/features.bzl
Internally rules_python decides whether the implementation should use the legacy builtin rules from bazel or not.
The rules_python attributes have diverged from the builtin rules e.g. `precompile` and so a consumer of this library that wants to support bazel versions that are still using the legacy builtin rules needs a method to be able to query whether the rules are being used.
This change adds a entry to features.bzl to expose whether the legacy builtin rules are being used.
> feat: Add feature to expose whether the native rules are used

- python/config_settings/transition.bzl
- python/private/attributes.bzl
- python/private/py_executable.bzl
- python/private/py_runtime_info.bzl
* Change "VERSION_NEXT" markers to upcoming 1.1.0 release
* Change incorrect 0.41.0 mention to 1.0.0
> chore: update version strings in docs.

- CHANGELOG.md
- python/private/pypi/whl_library_targets.bzl
- tests/pypi/whl_library_targets/whl_library_targets_tests.bzl
Make pypi-generated targets set `pyi_srcs` to include `*.pyi` files.
Work towards https://github.com/bazelbuild/rules_python/issues/2537
> feat: make pypi-generated targets include pyi files

- CHANGELOG.md
- python/private/repo_utils.bzl
Currently, the _which_unchecked helper unconditionally watches the `PATH` env var via repository_ctx.getenv. getenv is documented https://bazel.build/rules/lib/builtins/repository_ctx#getenv:
> any change to the value of the variable named by name will cause this repository to be re-fetched.
Thus, any change to `PATH` will cause any repository rule that transitively calls _which_unchecked to be re-fetched. This includes python_repository and whl_library.
There are reasonable development workflows that modify `PATH`. In particular, when git runs a hook, it adds the value of `GIT_EXEC_PATH` to `PATH` before invoking the hook. If the hook invokes bazel (for example, a pre-commit hook running `bazel build ...`), it will cause the Python repository rules to be re-fetched.
This commit lowers …
> fix: _which_unchecked: don't watch PATH if binary exists.

- python/private/py_info.bzl
The pyi_srcs and pyi_deps attributes have this disclaimer already. The provider should, too, so behavior is better specified.
> docs: note direct_pyi_files/transitive_pyi_files are usually build-time only

- docs/toolchains.md
This improves readability by clearly marking the beginnings and ends of the three involved source files.
Follow-up of #2512, as discussed.
> docs: Add horizontal spacers around filenames in custom toolchain guide

- gazelle/README.md
There's no longer a python subprocess since switching to tree-sitter in https://github.com/bazelbuild/rules_python/pull/1895
> docs: update gazelle README.md

- CHANGELOG.md
- python/private/pypi/extension.bzl
This patch enable calls to pypi override from a non-root module without failing. The call will instead be silently ignored.
Fixes #2550
> fix: Don't fail in override from a non-root module

- CHANGELOG.md
- python/private/py_executable.bzl
- python/private/site_init_template.py
- python/private/stage2_bootstrap_template.py
The script based bootstrap wasn't expanding the coverage template variable, which prevented
coverage from activating. This was introduced when it was switched to the venv layout.
To fix, expand the `%coverage_tool%` template variable as done elsewhere.
Tested manually, per repro instructions in #2572. While I did devise a way to mostly
test this without an integration test, it was thwarted by some other bugs.
Along the way, improve some of the bootstrap debug output and fix a comment.
Fixes https://github.com/bazelbuild/rules_python/issues/2572
> fix: make coverage work with bootstrap=script

- .github/workflows/create_archive_and_notes.sh
This is so that we can start pointing users at a more helpful changelog that
has announcements about deprecations, etc.
> doc: point users to our CHANGELOG at the top of the release note

- tests/support/sh_py_run_test.bzl
I noticed that my `$(location //path/to:target)` wasn't getting
expanded when writing a test. This patch fixes the issue by forwarding
the already-expanded environment from the inner target to the outer
target.
> fix: Enable location expansion for `sh_py_run_test`

- CHANGELOG.md
- sphinxdocs/private/proto_to_markdown.py
- sphinxdocs/tests/proto_to_markdown/proto_to_markdown_test.py
It seems that there was a typo in the code and instead of calling
`self._write` we were calling `self.write`. It went unnoticed because of
lack of coverage. This adds test code exercising the edge case and fixes
the typo.
Fixes #2579
> fix(sphinxdocs): do not crash when tag_class does not have doc

- CHANGELOG.md
- docs/_includes/py_console_script_binary.md
- docs/toolchains.md
Updates examples and docs to tell to use the base rules and the python_version attribute
instead of the wrapper transition rules.
> docs: using python_version attribute for specifying python version

- CHANGELOG.md
- python/private/zip_main_template.py
- tests/bootstrap_impls/BUILD.bazel
- tests/bootstrap_impls/bootstrap_script_zipapp_test.sh
- tests/support/sh_py_run_test.bzl
The `__main__.py` template (zip_main_template.py) was using the wrong path when creating
the interpreter symlinks. It as computing it correctly, just the wrong variable was used
in the symlink() call.
To fix, pass the correct variable.
Also adds a test to check that it's runnable.
Fixes https://github.com/bazelbuild/rules_python/issues/2596
> fix: make plain zipapp work with bootstrap=script

- examples/bzlmod_build_file_generation/BUILD.bazel
The location of gazelle has changed to bazel-contrib, so update the example accordingly.
> docs: Update URL in gazelle example

- CHANGELOG.md
- docs/api/rules_python/python/config_settings/index.md
- docs/environment-variables.md
Update changelog and VERSION_NEXT markers
> chore: updates for 1.2.0 release

- DEVELOPING.md
We're not using 0-version anymore, so update the docs to reflect that.
> docs: update dev docs on how to pick next version

- DEVELOPING.md
It's easier to do patch releases when the branch is already created. Some of the bugs
fixes in recent releases we probably could have easily released as patch releases if
we already had the branch ready.
> docs: tell how to create branches for releases

- CHANGELOG.md
This was a forgotten part of the original PR (#2507) implementing it.
> docs: add changelog update for //python/bin

- python/proto/BUILD.bazel
Follow-up to #2604, fixes a breaking change in v1.2.0-rc0
Note that this toolchain_type became unused in that PR. We leave behind an alias to make this a non-breaking change.
Verified in a downstream repo that requires the toolchain_type to register pre-built `protoc`: https://github.com/aspect-build/toolchains_protoc/pull/50/files
> refactor: cleanup now-unreferenced proto toolchain type

- .github/workflows/mypy.yaml
The mypy check on CI has been failing. The problem was the combination of:
* We were using Python 3.8
* jpetrucciani/mypy-check@master updated to use mypy 1.15
* mypy 1.15 dropped support for Python 3.8
To fix, use Python 3.9.
> ci: use Python 3.9 for mypy workflow to fix ci

- CHANGELOG.md
When adding the 1.2 section, everything was updated exception the section title.
> docs: fix changelog header for 1.2.0 entry

- CHANGELOG.md
- python/private/python.bzl
- python/private/python_repository.bzl
- tests/python/python_tests.bzl
Currently, by default, rules_python immediately fails when Bazel is run as root. The reasoning behind this involves .pyc files being generated for hermetic toolchains when they're first used, causing cache misses; to work around this, rules_python opts to make the toolchain installation directory read-only, but running Bazel as root would circumvent this. So rules_python actively detects if the current user is root, and hard fails. This check can be disabled by the root module by setting `python.override(ignore_root_user_error=True)`. (See more context in the linked issues/PRs.)
This causes a reverberating effect across the Bazel ecosystem, as rules_python is essentially a dependency of every single Bazel project through protobuf. Effectively, any Bazel project wishing to run as root need …
> fix: Downgrade "running as root" error to a warning by default

- CHANGELOG.md
- gazelle/modules_mapping/def.bzl
- gazelle/modules_mapping/generator.py
Calls to the modules mapping rule contains very long command line args due to the use of the full `wheels` parameter. This change adds support for spilling the args into a file as needed.
In addition, it improves the performance of the `modules_mapping` rule:
* Remove the calls `to_list` that are unnecessary on the depset.
* Remove the iteration over the depset when passing to `args`, and other calls to `.path`, and instead let args do this lazily.
> fix: spill module mapping args to a file

- python/private/pypi/extension.bzl
This makes it more clear when you've misconfigured pip.parse
> Add error for pip.parse attrs that require other attrs

- docs/BUILD.bazel
- sphinxdocs/private/sphinx.bzl
- sphinxdocs/tests/sphinx_docs/BUILD.bazel
- sphinxdocs/tests/sphinx_stardoc/BUILD.bazel
Remove implicit `build_test`s from `sphinx_docs` targets. Instead, users can decide whether or not to add `build_tests` for docs. This also keeps `sphinx_docs` builds out of `bazel test //...`, which may not be desirable.
Add `build_test`s to cover in-tree `sphinx_docs` targets. Rename the existing `build_test` for `//sphinxdocs/tests/sphinx_docs:docs` to match the new targets.
Also, tag the `sphinx_docs` `*.run` and `*.serve` targets as `"manual"` so they are excluded from wildcards. These are only needed for interactive development.
> chore: Remove *_build_test targets from sphinx_docs (#2645)

- CHANGELOG.md
- python/private/pypi/evaluate_markers.bzl
- python/private/pypi/patch_whl.bzl
- python/private/pypi/pypi_repo_utils.bzl
- python/private/pypi/whl_library.bzl
Before this change we would just invoke the Python interpreter. This
means that in the `rules_python` directory there would be `__pycache__`
folders created in the source tree and the same `__pycache__` folders
would be created in the python interpreter repository rules if the
directories were writable.
This change ensures that we are executing `python` with `-B` in those
contexts and reduces any likelihood of us doing the wrong thing.
Work towards #1169.
> fix(pypi): use python -B for repo-phase invocations

- CHANGELOG.md
- examples/build_file_generation/gazelle_python.yaml
- examples/bzlmod_build_file_generation/gazelle_python.yaml
- examples/bzlmod_build_file_generation/gazelle_python_with_types.yaml
- gazelle/manifest/generate/generate.go
Update `gazelle_python.yaml` to include the YAML docstart string:
```diff
-- a/gazelle_python.yaml
+++ b/gazelle_python.yaml
@@ -3,6 +3,7 @@
+---
manifest:
modules_mapping:
30fcd23745efe32ce681__mypyc: black
```
While _technically_ not required, it is good practice to include. And then users don't have to exclude `gazelle_python.yaml` from their linters :upside_down_face:.
/cc @joshgc
> fix(gazelle): Include YAML 'docstart' in gazelle manifest file

- gazelle/modules_mapping/generator.py
When running python with `-S` to disable the `site` module, `exit` isn't implicitly imported and you need to explicitly call `sys.exit` instead. Seems to be a remnant of the REPL
> fix(gazelle): Explicitly call sys.exit in the modules_mapping generator

- CHANGELOG.md
- docs/BUILD.bazel
- docs/_includes/volatile_api.md
- docs/extending.md
- docs/index.md
- python/api/BUILD.bazel
- python/api/executables.bzl
- python/api/libraries.bzl
- python/private/BUILD.bazel
- python/private/attr_builders.bzl
- python/private/py_binary_rule.bzl
- python/private/py_executable.bzl
- python/private/py_library.bzl
- python/private/py_library_rule.bzl
- python/private/py_test_rule.bzl
- python/private/rule_builders.bzl
- tests/support/sh_py_run_test.bzl
This exposes public functions for creating builders for py_binary, py_test, and py_library.
It also adds some docs and examples for how to use them.
I'm calling this a "volatile" API -- it's public, but the pieces that comprise
it (e.g. all the rule args, attributes, the attribute args, etc) are likely to change
in various ways, and not all modifications to them can be supported in a backward
compatible way. Hence the "volatile" term:
* hold it gently and its fine
* shake it a bit and its probably fine
* shake it moderately and something may or may not blow up
* shake it a lot and something will certainly blow up.
Work towards https://github.com/bazelbuild/rules_python/issues/1647
> feat(rules): allow deriving custom rules from core rules

- CHANGELOG.md
- python/private/py_executable.bzl
- python/private/stage1_bootstrap_template.sh
- tests/bootstrap_impls/BUILD.bazel
- tests/bootstrap_impls/interpreter_args_test.py
Today, there's way to control what startup args are used for the interpreter.
To fix, add an `interpreter_args` attribute. These are written into the bootstrap.
This is only implemented for the bootstrap=script method
Fixes https://github.com/bazelbuild/rules_python/issues/2668
> feat(binary/test): add interpreter_args attribute

- CHANGELOG.md
- docs/environment-variables.md
- python/private/py_executable.bzl
- python/private/stage1_bootstrap_template.sh
There is no means to be able to provide additional interpreter arguments to the `bash`-based stage 1 bootstrap system at launch time.
The Intelli-J / Bazel plugin typically launches a `py_*` rule build product with something like this (abridged) using a Python interpreter from the local environment;
```
python3 /path/to/pydev/pydevd.py --client 127.0.0.1 --port 12344 --file /path/to/built/python-file
```
When the `bash`-based bootstrap process is used, this mechanism not longer works. This PR will mean that a potential future Intelli-j / Bazel plugin version may be able to launch the build product differently and inject additional interpreter arguments so that the debug system can be stood up in this sort of a way;
```
RULES_PYTHON_ADDITIONAL_INTERPRETER_ARGS="/path/to/pydev/pydevd.py …
```
> feat: env-var for additional interpreter args in bootstrap stage 1

- docs/index.md
It's been released so this was out-of-date.
> chore(docs): fix forward-ref to 1.0

- python/private/pypi/whl_library.bzl
- python/private/python_repository.bzl
- python/versions.bzl
The repo was donated. It also trivially removes the need for a redirect on the URL that fetches artifacts.
> chore: account for new GH org of standalone interpreter

- CHANGELOG.md
- python/private/py_executable.bzl
- python/private/stage2_bootstrap_template.py
- tests/bootstrap_impls/BUILD.bazel
- tests/bootstrap_impls/main_module.py
This implements the ability to run a module name instead of a file path, aka
`python -m` style of invocation.
This allows a binary/test to specify what the main module is without having to
have a direct dependency on the entry point file.
As a side effect, the `srcs` attribute is no longer required.
Fixes https://github.com/bazelbuild/rules_python/issues/2539
> feat(rules): add main_module attribute to run a module name (python -m)

- .github/workflows/create_archive_and_notes.sh
The RELEASING.md docs contain the VERSION_NEXT marker string in their docs, so also
have to be ignored by the release script.
> chore: ignore releasing.md for version string check

- .bcr/gazelle/metadata.template.json
- .bcr/metadata.template.json
BCR presubmits require that the list of repositories match where downloads come from
Along the way, also update the URL homepages to bazel-contrib and change the email
to my personal instead of work email.
> chore: update bcr metadata files to specify bazel-contrib

- RELEASING.md
We've done release candidates for the last couple releases and I think it's gone well,
so document how to do them.
> docs: add steps for creating release candidates

- CHANGELOG.md
- python/private/python_repository.bzl
Previously the code would not chmod for the Windows hermetic toolchains
because there is usually no need - Windows does not have chmod and if
you are downloading the Windows repo on a UNIX system, you won't run it,
so it will stay as is.
However, that left a single case where somebody may want to download the
Linux toolchain on a Windows and the main cases are:
* `bazel sync`
* build a docker image on Windows using `rules_oci` or similar.
Fixes #2660
> fix(toolchain): no chmod on windows when downloading hermetic toolchain

- CHANGELOG.md
- MODULE.bazel
- gazelle/deps.bzl
- python/versions.bzl
This patch introduces support for riscv64 linux platform,
which is supported in python-build-standalone since
https://github.com/astral-sh/python-build-standalone/releases/tag/20250115
Because it only gets supported recently, I updated python version maps to match
latest release.
The msvc `-shared` variant is no longer offered after 20250311 release. So I
updated the corresponding msvc builds to the normal variant.
> feat: add riscv64 linux support

- CHANGELOG.md
- python/private/pypi/BUILD.bazel
- python/private/pypi/extension.bzl
- tests/pypi/extension/extension_tests.bzl
This change reduces the number of lines we are going to write to the
MODULE.bazel.lock file by not writing `experimental_target_platforms`
to the lock file that eventually get discarded in the `whl_library` if
the wheel is platform specific [1].
This means that the tests will become more easy to understand, but
technically this is a no-op change, only resulting in a smaller lock
file:
```
$ wc -l MODULE.bazel.lock
6536 MODULE.bazel.lock
$ bazel mod deps --lockfile_mode=refresh
...
$ wc -l MODULE.bazel.lock
6154 MODULE.bazel.lock
```
Work related to #2622
[1]: https://github.com/bazel-contrib/rules_python/blob/09145b9f628d482246eaa70421bf0cbae9acb096/python/private/pypi/whl_library.bzl#L337
> fix(pypi): output only necessary target_platforms

- CHANGELOG.md
It appears to have been copied from the 1.1.0 "Added" section, but I'm not sure whether "fixing" old changelogs is acceptable.
> fix(docs): CHANGELOG "astral" typo

- python/private/python_bootstrap_template.txt
Fixes some f-strings, trailing commas, and out-of-order argument unpacking in the bootstrap template to restore compatibility with Python 3.4.x.
> fix: Fix Python 3.4.x compatibilty with bootstrap (#2709)

- python/private/python_bootstrap_template.txt
The comment in the bootstrap about requiring compatibility with older Python versions
is defunct and outdated.
Python 2 support was dropped years ago. While compatibility with older Python versions is
best effort for the system_python bootstrap, Python 2 doesn't need to be supported
> chore: remove defunct comment about py2 compatibility

- CHANGELOG.md
- docs/environment-variables.md
- python/private/repo_utils.bzl
Allows the logging level to be set to `FAIL`, removing `WARN` logging.
> fix: allow warn logging to be disabled via RULES_PYTHON_REPO_DEBUG_VERBOSITY

- CHANGELOG.md
- python/private/toolchains_repo.bzl
Runs the check on the interpreter in the toolchain repo in isolated mode via `-I`. This ensures it's not influenced by userland environment variables, such as `PYTHONPATH` which will cause issues if it allows this invocation to use into another interpreter versions site-packages.
> fix: run check on interpreter in isolated mode

- python/private/pypi/parse_requirements.bzl
- tests/pypi/extension/extension_tests.bzl
Whilst integrating #2695 I introduced a regression and here I add a test
for that and fix it. The code that was getting the filename from the URL
was too eager and would break if there was a git ref as noted in the
test.
Before this commit and #2695 the code was not handling all of the cases
that are tested now either, so I think now we are in a good place. I am
not sure how we should handle the `git_repository` URLs. Maybe having
`http_archive` and `git_repository` usage would be nice, but I am not sure
how we can introduce it at the moment.
Work towards #2363
> fix(pypi): correctly fallback to pip for git direct URLs

- gazelle/pythonconfig/pythonconfig.go
- gazelle/pythonconfig/pythonconfig_test.go
This just fixes a crash when `generation_mode: update_only` causes `GenerateRules` to not be invoked for 100% of directories.
Fix #2707
> fix: support gazelle generation_mode:update_only

- CHANGELOG.md
- docs/api/rules_python/python/config_settings/index.md
- docs/toolchains.md
- python/private/py_executable.bzl
- sphinxdocs/inventories/bazel_inventory.txt
Fixes a few xrefs in the docs that had typos or missing external bazel links.
> docs: fix a few xrefs

- CHANGELOG.md
- python/private/python_repository.bzl
We've seen cases the temporary versions for the `.pyc` and `.pyo` files are unstable on certain interpreter toolchains. The temp files take for form of `.pyc.NNN`, so the amended glob patten will still match both the `.pyc` and `.pyc.NNN` versions of the file names.
> fix: Ensure temporary .pyc & .pyo files are excluded from the interpreters repository files

- python/private/py_runtime_info.bzl
- python/private/py_runtime_rule.bzl
I think the DEFAULT_BOOTSTRAP_TEMPLATE global was used by something in the original
Bazel impl, but now it's just used in one place. Remove the shared global and just
inline the single usage.
> chore: remove unnecessary DEFAULT_BOOTSTRAP_TEMPLATE global

- python/private/pypi/BUILD.bazel
- python/private/pypi/evaluate_markers.bzl
- python/private/pypi/pep508_env.bzl
- python/private/pypi/pep508_platform.bzl
- python/private/pypi/pep508_requirement.bzl
- tests/pypi/pep508/BUILD.bazel
- tests/pypi/pep508/requirement_tests.bzl
These are just bugfixes to already merged code:
* Fix nested bracket parsing in PEP508 marker parser.
* Fix the sys_platform constants, which I noticed in #2629 but they got
also pointed out in #2766.
* Port some of python tests for requirement parsing and improve the
implementation. Those tests will be removed in #2629.
* Move the platform related code to a separate file.
* Rename `pep508_req.bzl` to `pep508_requirement.bzl` to follow the
convention.
All of the bug fixes have added tests.
Work towards #2423.
> fix(pypi): fixes to the marker evaluation and utils

- CHANGELOG.md
- python/private/pypi/parse_requirements.bzl
- python/private/pypi/pep508_requirement.bzl
- tests/pypi/extension/extension_tests.bzl
- tests/pypi/pep508/requirement_tests.bzl
This change addresses a bug where `pip.parse` selects the wrong requirement entry when multiple extras are listed with platform-specific markers.
In a `requirements.txt` generated by tools like `uv` or `poetry`, it's valid to have multiple entries for the same package, each with different extras and `sys_platform` markers, for example:
```ini
optimum[onnxruntime]==1.17.1 ; sys_platform == 'darwin'
optimum[onnxruntime-gpu]==1.17.1 ; sys_platform == 'linux'
```
The current implementation in [`[parse_requirements.bzl](https://github.com/bazel-contrib/rules_python/blob/032f6aa738a673b13b605dabf55465c6fc1a56eb/python/private/pypi/parse_requirements.bzl#L114-L126)`](https://github.com/bazel-contrib/rules_python/blob/032f6aa738a673b13b605dabf55465c6fc1a56eb/python/private/pypi/parse_requirements. …
> fix: Resolve incorrect platform specific dependency

- CHANGELOG.md
- python/private/py_executable.bzl
- tests/base_rules/py_executable_base_tests.bzl
- tests/support/support.bzl
With this PR we mark the srcs attribute as optional as we can
leverage the `main_module` to just run things from the deps.
This also removes a long-standing `TODO` note.
Fixes #2765
> fix(rules): make the srcs trully optional

- tests/builders/attr_builders_tests.bzl
Strings used to refer to legacy struct providers, which were removed from Bazel.
Legacy struct providers have been deprecated by Bazel. Replacing them with modern providers, will make it possible to simplify and remove legacy handling from Blaze.
The change is a no-op.
More information: https://github.com/bazelbuild/bazel/issues/25836
> fix: replace string with modern providers in tests

- CHANGELOG.md
- docs/toolchains.md
- python/current_py_toolchain.bzl
Using these new make vars in `py_binary` or `py_test` will correctly find the interpreter when setting `--no_legacy_external_runfiles`.
Fixes #2728
> feat(toolchain): Add new make vars for Python interpreter path compliant with `--no_legacy_external_runfiles`

- python/private/pypi/extension.bzl
- python/private/pypi/whl_library.bzl
- tests/pypi/extension/extension_tests.bzl
A simple non-functional cleanup that just removes legacy code paths from
bzlmod PyPI integration.
> refactor(bzlmod): stop using 'repo' attr in whl_library

- docs/support.md
Fixes #2722.
Related #2734, #2276, #1579
> doc: better document supported platform tiers

- CHANGELOG.md
- python/private/util.bzl
This routine already copies `compatible_with`, which is little used, but does not copy `target_compatible_with`, which is broadly used. This seems like an oversight.
I noticed this discrepancy when working on a system that assumes that any `tags` or `target_compatible_with` parameters supplied to a macro will propagate to all rules created by that macro. In rules_python, this already works for `tags`, but not for `target_compatible_with`.
It would be great to get this accepted upstream, so that I can stop patching rules_python.
> fix(rules): copy_propagating_kwargs() now also copies target_compatible_with

- CHANGELOG.md
- RELEASING.md
- python/current_py_toolchain.bzl
- python/features.bzl
- python/local_toolchains/repos.bzl
- python/packaging.bzl
- python/private/py_exec_tools_toolchain.bzl
- python/private/py_info.bzl
- python/private/py_library.bzl
- python/private/pypi/extension.bzl
- python/private/python.bzl
Updates changelog and version markers.
Also updates the release docs with some shell-one liners to copy and paste to make it
a bit more mechanical.
> release: 1.4.0 release prep

- python/private/pypi/whl_repo_name.bzl
- tests/pypi/whl_repo_name/whl_repo_name_tests.bzl
Also escape plus and percent when generating the repo name from the wheel version.
Sometimes they have such characters in them.
Fixes https://github.com/bazel-contrib/rules_python/issues/2799
> fix: escape more invalid repo string characters

- python/private/pypi/whl_metadata.bzl
- tests/pypi/whl_metadata/whl_metadata_tests.bzl
The wheel `METADATA` parsing implemented in 1.4 missed the fact
that whitespace is significant and sometimes License is included
inline in the `METADATA` file itself.
This change ensures that we stop parsing the `METADATA` file only
on first completely empty line.
Fixes https://github.com/bazel-contrib/rules_python/issues/2796
> fix: parsing metadata with inline licenses

- tests/pypi/parse_simpleapi_html/parse_simpleapi_html_tests.bzl
In addition to #2801 I wanted to ensure that we are getting the correct
filename when downloading wheels. It seems that the `%` in the wheel
filename might get through wheels that get referenced via direct URL in
the requirements.txt files.
> test(pypi): add a test case for simpleapi html parsing with %

- CHANGELOG.md
- python/private/python_bootstrap_template.txt
- python/private/stage2_bootstrap_template.py
The Google tensorflow/jax devinfra team reported that Windows 2022 with Python 3.12.8
has a tendency to be flaky when calling the platform.win32 APIs. I'm very certain I
saw similar behavior in the past myself.
To fix, just call the APIs a couple times; it seems to fix itself.
cc @vam-google
> fix: try multiple times to get win32 version to handle flakes

- CHANGELOG.md
- python/private/repo_utils.bzl
While making a local patch to work around #2640, I found that I had a need for running a subprocess (`gcloud auth print-access-token`) via `repo_utils.execute_checked_stdout`. However, doing so would log that access token when debug logging was enabled via `RULES_PYTHON_REPO_DEBUG=1`. This is a security concern for us, so I hacked in an option to allow a particular `execute_(un)checked(_stdout)` call to disable logging stdout, stderr, or both.
I figure this might be useful to others so I thought I'd upstream it.
`execute_(un)checked(_stdout)` now support `log_stdout` and `log_stderr` bools that default to `True` (which is the same behavior as before this PR.
When the subprocess writes to stdout and `log_stdout = False`, the logged message will show:
```
===== stdout start ===== …
```
> refactor: Add log_std(out|err) bools to repo_utils that execute a subprocess

- docs/toolchains.md
This is to make it easier to find the API docs for the rules the docs talk about.
> docs: add xrefs for local toolchains rules

- python/private/pypi/requirements_parser/resolve_target_platforms.py
- python/private/pypi/whl_installer/BUILD.bazel
- python/private/pypi/whl_installer/arguments.py
- python/private/pypi/whl_installer/platform.py
- python/private/pypi/whl_installer/wheel.py
- python/private/pypi/whl_installer/wheel_installer.py
- tests/pypi/whl_installer/BUILD.bazel
- tests/pypi/whl_installer/arguments_test.py
- tests/pypi/whl_installer/platform_test.py
- tests/pypi/whl_installer/wheel_installer_test.py
- tests/pypi/whl_installer/wheel_test.py
This just adds the code back at the original state before the following
PRs have been made to remove them: #2629, #2781. This has not been
hooked up yet in `evaluate_markers` and `whl_library` yet and I'll need
extra PRs to do that.
No CHANGELOG entries for now, will be done once the integration is back.
Work towards #2830
> revert(pypi): bring back Python PEP508 code with tests

- python/private/pypi/whl_installer/platform.py
- python/private/pypi/whl_installer/wheel.py
- tests/pypi/whl_installer/platform_test.py
- tests/pypi/whl_installer/wheel_test.py
Handling of `python_full_version` correctly has been fixed in the Starlark
implementation in #2793 and in this PR I am backporting the changes to handle
the full python version target platform strings so that we can have the same
behaviour for now.
At the same time I have simplified and got rid of the specialization handling
in the Python algorithm just like I did in the starlark, which simplifies the
tests and makes the algorithm more correct.
Summary:
* Handle `cp3x.y_os_arch` strings in the `platform.py`
* Produce correct strings when the `micro_version` is unset. Note, that we use version `0` in evaluating but we use the default version in the config setting. This is to keep compatibility with the current behaviour when the target platform is not fully specified (which would be the …
> fix(pypi) backport python_full_version fix to Python

- python/private/pypi/pep508_evaluate.bzl
- tests/pypi/pep508/evaluate_tests.bzl
Right now, if two strings are compared, it results in an error.
Per spec, strings are suppose to "use the python behavior". Starlark is going
to use Java semantics underneath, but it should behave close enough for the (almost
exclusively) ASCII input that will be used.
Work towards https://github.com/bazel-contrib/rules_python/issues/2826
> feat: implement less/greater operators for string for env marker evaluation

- docs/environment-variables.md
While figuring out an upgrade from an old rules_python version, I had to look up when the
environment variable first became available.
Also note what version it defaulted to 1.
> docs: doc version when RULES_PYTHON_ENABLE_PYSTAR was introduced

- python/private/pypi/parse_requirements.bzl
- tests/pypi/index_sources/index_sources_tests.bzl
- tests/pypi/parse_requirements/parse_requirements_tests.bzl
Summary:
- Better handle git references for sdists.
- Better handle direct whl references.
- Add an extra test that turned out to be not needed in the end, but I
left it to increase the code coverage.
Work towards #2363
Fixes #2828
> fix(pypi): handle more URL patterns for requirement sources

- tests/base_rules/py_executable_base_tests.bzl
- tests/base_rules/py_test/py_test_tests.bzl
This is required as of https://github.com/bazelbuild/bazel/commit/2780393d35ad0607cf5e344ae082b00a5569a964 as tests now require an execution platform that matches their target constraints by default.
Fixes #2850
> fix: add target platform to extra exec platforms in analysis tests

- python/private/attributes.bzl
- python/private/py_executable.bzl
They are run on the test action's execution platform, which is resolved for the `test` exec group, not the default one.
> fix: configure coverage helpers for test exec group

- python/private/pypi/pep508_env.bzl
Fixes:
```
ERROR: /Users/fmeum/git/rules_python/tests/pypi/env_marker_setting/BUILD.bazel:3:30: Illegal ambiguous match on configurable attribute "platform_machine" in //tests/pypi/env_marker_setting:test_expr_python_full_version_lt_negative_subject:
@@platforms//cpu:aarch64
@@platforms//cpu:arm64
Multiple matches are not allowed unless one is unambiguously more specialized or they resolve to the same value. See https://bazel.build/reference/be/functions#select.
```
Work towards #2850.
Work towards #2826.
> fix: fix test analysis error on macOS arm64

- CHANGELOG.md
- python/private/pypi/whl_library.bzl
When given .whl file URLs and no file name, `whl_library` writes the
wheel it downloads to a file with the same file name as the first URL's.
But then at extraction time, it always consults ctx.attr.filename
for that file name, leading to failure when that attribute is None.
This patch should fix that.
Related #2363
> Fix whl_library file path inference

- python/private/toolchains_repo.bzl
The sanitize_platform_name function is unused, so remove it.
> cleanup: remove unused sanitize_platform_name function

- python/private/python.bzl
- python/private/python_register_toolchains.bzl
- tests/python/python_tests.bzl
This is to facilitate eventually allowing overrides to add additional platforms.
Instead of the PLATFORMS global being used, the python bzlmod extension passing the
mapping directly to python_register_toolchains, then receives back the subset of
platforms that had repos defined. That subset is then later used when (re)constructing
the list of repo names for the toolchains.
> refactor: have bzlmod pass platforms to python_register_toolchains

- sphinxdocs/private/proto_to_markdown.py
- sphinxdocs/tests/proto_to_markdown/proto_to_markdown_test.py
When converting the protos for repo rules to markdown, their blocks weren't being
properly closed. To fix, just add the closing colons. Also added a test of the text
generation.
> sphinxdocs: close repo rule directives

- sphinxdocs/src/sphinx_bzl/bzl.py
Apparently, the `object_type` dict controls what object types are recognized from
inventory files. The bazel inventory of terms includes several bzl:obj entries for
things that don't have a more appropriate type. This fixes xrefs for terms like
RBE, config, and some others.
> sphinxdocs: make xrefs to bzl:obj in inventories work

- sphinxdocs/src/sphinx_bzl/bzl.py
- sphinxdocs/tests/sphinx_stardoc/sphinx_output_test.py
- sphinxdocs/tests/sphinx_stardoc/xrefs.md
The role assigned to attributes within the tag class directive were being given the
role `arg`, when they should be `attr`. This caused xrefs using the attr role to
be unable to find them.
To fix, set them to have the correct role, like the repo rule and regular rule
directives do. Also add a test.
> sphinxdocs: make xrefs to tag class attributes using attr role work

- sphinxdocs/src/sphinx_bzl/bzl.py
- sphinxdocs/tests/sphinx_stardoc/sphinx_output_test.py
- sphinxdocs/tests/sphinx_stardoc/xrefs.md
It's common to simply refer to an arg or attribute by its sole name, especially for
ones that are unique.
This fixes about ~20 broken xrefs in our docs. Also add test for this behavior.
> sphinxdocs: allow unqualified arg/attr name for xref

- docs/getting-started.md
- docs/toolchains.md
The "toolchains" xref is ambiguous. Create a unique header for the toolchain configuration
section and link to that name instead.
> docs: fix xref to toolchain docs from getting starting

- sphinxdocs/src/sphinx_bzl/bzl.py
- sphinxdocs/tests/sphinx_stardoc/sphinx_output_test.py
- sphinxdocs/tests/sphinx_stardoc/xrefs.md
This allows files to be specified as xrefs. Also adds a test for the functionality.
> sphinxdocs: allow files to be xref

- docs/devguide.md
- docs/index.md
Having the devguide processed by Sphinx will let us use more powerful markup, which
will help make it possible to create richer documentation.
> docs: move devguide to sphinx for more powerful markup

- sphinxdocs/src/sphinx_bzl/bzl.py
- sphinxdocs/tests/sphinx_stardoc/sphinx_output_test.py
- sphinxdocs/tests/sphinx_stardoc/xrefs.md
This allows using xrefs like `//python/runtime_env_toolchains` and `runtime_env_toolchains`.
> sphinxdocs: make bazel package xrefs work

- CHANGELOG.md
The changelog has a variety of broken xrefs. This fixes most of them.
> docs: fix most broken xrefs in changelog

- tests/bootstrap_impls/BUILD.bazel
- tests/bootstrap_impls/a/b/c/BUILD.bazel
- tests/interpreter/interpreter_tests.bzl
- tests/no_unsafe_paths/BUILD.bazel
- tests/packaging/BUILD.bazel
- tests/repl/BUILD.bazel
- tests/runtime_env_toolchain/BUILD.bazel
- tests/support/py_reconfig.bzl
- tests/support/sh_py_run_test.bzl
- tests/toolchains/defs.bzl
- tests/uv/lock/lock_tests.bzl
- tests/venv_site_packages_libs/BUILD.bazel
The py_reconfig code is pretty large, so move it to its own file. It's also be easier
to find in its own file rather that part of something named after "shell testing".
> tests: move py_reconfig rules to their own file

- DEVELOPING.md
Our test files aren't part of the sphinx docs, so use the gh-path external link hook to
link to the files directly on github.
> docs: fix link to py_reconfig and sh_py_run_test files

- sphinxdocs/src/sphinx_bzl/bzl.py
The "Any" and "object" types are useful in expression starlark types, but aren't actually
real things. Treat them like None and make them no-ops so they aren't treated like
missing xrefs.
> sphinxdocs: make Any and object types no-ops to avoid missing xrefs

- python/private/rule_builders.bzl
- sphinxdocs/inventories/bazel_inventory.txt
Adds a variety of Bazel builtins to the external Bazel inventory.
Along the way, fFixes a couple of bad xrefs in rule_builders.
> docs: correct some xrefs, add various missing Bazel external xrefs

- docs/conf.py
Crossreferencing to py code outside our project isn't setup, so these are just a lot
of warning spam. Disable them for now.
> docs: ignore warnings about missing external py xrefs

- python/private/python.bzl
- python/private/python_register_toolchains.bzl
This makes python_register_toolchains return the repo names it created, which allows
the bzlmod code to be directly aware of the repos that were created instead of having
to rely on assuming the names via the platform keys.
This is to facilitate python_register_toolchains creating a more arbitrary subset
of platform-specific repos.
Work towards https://github.com/bazel-contrib/rules_python/issues/2081
> refactor: make bzlmod directly aware of created toolchain repo names

- python/bin/repl_stub.py
- python/private/repl_template.py
- tests/repl/repl_test.py
With the current `//python/bin:repl` implementation, any variables
defined in `PYTHONSTARTUP` are not actually available in the REPL
itself. I accidentally omitted this in the first patch.
This patch fixes the issue and adds appropriate tests.
> fix: Allow PYTHONSTARTUP to define variables

- python/private/python.bzl
- python/private/python_register_toolchains.bzl
- python/private/toolchains_repo.bzl
This moves the creation of the host_toolchain repos into the bzlmod phase.
This is to facilitate future work to allow for when a a particular version
doesn't provide a host-compatible variant
Work towards https://github.com/bazel-contrib/rules_python/issues/2081
> refactor: make bzlmod create host repos for toolchains

- python/private/pypi/extension.bzl
- python/private/pypi/hub_repository.bzl
The target_platforms attribute is unused. The attribute gets used, but the values it
computes are never used.
> refactor: remove unused target_platforms hub_repository attr

- python/private/attr_builders.bzl
- python/private/py_console_script_binary.bzl
- python/private/pypi/attrs.bzl
More misc xrefs fixes in:
* attr_builders
* py_console_script_binary
* pypi envvar ref
> docs: fix xrefs in 

- docs/BUILD.bazel
- python/api/api.bzl
- python/private/api/api.bzl
- python/private/api/py_common_api.bzl
- python/private/common.bzl
- python/private/py_info.bzl
- python/private/py_package.bzl
- tests/base_rules/py_info/py_info_tests.bzl
I wrote up the docs awhile, but didn't fully wire them through to the doc gen.
Fixes some various issues with the generated docs along the way.
> docs: generate docs for py_common, PyInfoBuilder APIs

- python/private/python.bzl
- python/private/python_register_toolchains.bzl
- python/private/toolchains_repo.bzl
The host_toolchain name is misleading, so rename it to some more accurate.
Work towards https://github.com/bazel-contrib/rules_python/issues/2913
> refactor: rename host_toolchain rule to host_compatible_python_repo

- MODULE.bazel
- docs/api/rules_python/python/bin/index.md
- docs/toolchains.md
- examples/bzlmod/MODULE.bazel
- examples/bzlmod/other_module/MODULE.bazel
- examples/bzlmod_build_file_generation/MODULE.bazel
- examples/multi_python_versions/MODULE.bazel
- python/extensions/python.bzl
- python/private/python.bzl
When there are multiple Python toolchains, there are currently two ways of setting the default version: the `is_default` attribute of the `python.toolchain()` tag class and the `python.defaults()` tag class. The latter is more powerful, since it also supports files and environment variables. This patch updates the examples and the docs to use `python.defaults()`.
Relates to pull request #2588 and issue #2587.
> docs/refactor: Use python.defaults, not is_default

- tests/support/sh_py_run_test.bzl
Just some minor refactoring of the py_reconfig rule so that it's easier to add attributes
that affect transition state. After this, just two spots have to be modified to
add an attribute (map of attrs, map of attr to transition label).
> tests: refactor py_reconfig rules so less boilerplate is needed to add attrs

- python/private/pypi/extension.bzl
- python/private/pypi/parse_requirements.bzl
- python/private/pypi/pip_repository.bzl
- tests/pypi/parse_requirements/parse_requirements_tests.bzl
The modeling of the data structures returned by the `parse_requirements`
function was not optimal and this was because historically there was
more logic in the `extension.bzl` and more things were decided there.
With the recent refactors it is possible to have a harder to misuse data
structure from the `parse_requirements`. For each `package` we will
return a struct which will have a `srcs` field that will contain easy to
consume values.
With this in place we can do the fix that is outlined in the referenced
issue.
Work towards #2648
> refactor(pypi): return a list from parse_requirements

- docs/conf.py
The redirect was going to a non-existent URL when viewed on the deployed docs.
This was happening because the absolute paths `/api/whatever` don't exist in the deployed
site -- it's actually `/en/latest/api/whatever`. This went unnoticed because it works
locally (where there is no /en/latest prefix).
To fix, use a relative url (relative urls are relative to the path that is redirected from)
> docs: fix sphinxdocs mis-redirect

- python/private/pypi/simpleapi_download.bzl
> fix(pypi): Only show index_url_overrides warnings when they are needed

- CHANGELOG.md
- docs/api/rules_python/python/config_settings/index.md
- python/config_settings/BUILD.bazel
Switch the default bootstrap back to system_python, per maintainer discussion.
The main reason is downstream consumers are unlikely to be fully ready for the
usage of raw symlinks (declare_symlink artifacts). APIs to detect them aren't
available until Bazel 8, which makes it difficult for packaging rules, such
as rules_pkg, bazel-lib, or tar rules.
This reverts the core part of commit 9f3512fe0cc6d7229170e45724e22e64be0b8300
> revert: change default bootstrap back to system_python

- python/private/common.bzl
- python/private/py_wheel.bzl
- python/uv/private/uv_toolchain.bzl
- sphinxdocs/private/sphinx.bzl
Required for compatibility with https://github.com/bazelbuild/bazel/issues/20183
> refactor: Add missing uses of DefaultInfo

- docs/toolchains.md
Added missing commas in `local toolchains` instructions
> docs: fix typo in toolchains.md example code

- python/private/pypi/whl_library_targets.bzl
```
ERROR: Traceback (most recent call last):
File ".../rules_python++pip+rules_mypy_pip_312_click/BUILD.bazel", line 5, column 20, in <toplevel>
whl_library_targets(
File ".../rules_python+/python/private/pypi/whl_library_targets.bzl", line 337, column 53, in whl_library_targets
"//conditions:default": create_inits(
File ".../rules_python+/python/private/pypi/namespace_pkgs.bzl", line 72, column 25, in create_inits
for out in get_files(**kwargs):
File ".../rules_python+/python/private/pypi/namespace_pkgs.bzl", line 20, column 5, in get_files
def get_files(*, srcs, ignored_dirnames = [], root = None):
Error: get_files() got unexpected keyword argument: ignore_dirnames (did you mean 'ignored_dirnames'?)
```
> Fix argument name typo

- CHANGELOG.md
- gazelle/python/file_parser.go
- gazelle/python/file_parser_test.go
- gazelle/python/generate.go
- gazelle/python/parser.go
- gazelle/python/resolve.go
- gazelle/python/std_modules.go
- gazelle/python/std_modules_test.go
- gazelle/python/target.go
Export the members of `python.ParserOutput` struct to make it publicly accessible. This allows other `py` extensions to leverage the Python resolver logic for resolving Python imports, instead of have to duplicate the resolving logic.
> refactor(gazelle) Types for exposed members of `python.ParserOutput` are now all public

- CHANGELOG.md
- python/private/pypi/BUILD.bazel
- python/private/pypi/config_settings.bzl
- python/private/pypi/extension.bzl
- python/private/pypi/hub_repository.bzl
- python/private/pypi/render_pkg_aliases.bzl
- tests/pypi/config_settings/config_settings_tests.bzl
- tests/pypi/extension/extension_tests.bzl
- tests/pypi/pkg_aliases/pkg_aliases_test.bzl
- tests/pypi/render_pkg_aliases/render_pkg_aliases_test.bzl
With this PR we can support arbitrary target settings instead of just
plain `constraint_values`. We still have custom logic to ensure that all
of the tests pass. However, the plan is to remove those tests once we
have simplified the wheel selection mechanisms and the `pkg_aliases`
macro. I.e. if we have at most 1 wheel per platform that the `pypi`
bzlmod extension passes to the `pkg_aliases` macro, then we can just
have a simple `selects.with_or` where we list out all of the target
platform values.
This PR may result in us creating more targets but that is the price
that we have to pay if we want to do this incrementally.
Work towards #2747
Work towards #2548
> feat: support arbitrary target_settings in our platforms 3/n

- python/private/pypi/namespace_pkgs.bzl
- tests/pypi/namespace_pkgs/namespace_pkgs_tests.bzl
It seems that the only function that did not have unit tests have bugs and the integration tests did not catch it because we weren't creating namespacepkg `__init__.py` files.
This change fixes the bug, adds a unit test for the remaining untested function.
Fixes #3023
> fix(pypi): namespace_pkgs should pass correct arguments

- python/private/py_library.bzl
There's a bug in the version string parser that doesn't handle local identifiers correctly.
Thankfully, it's only activated in the experimental code path when site packages for
libraries is eanbled. Moving the logic within that block works around it.
Work around for https://github.com/bazel-contrib/rules_python/issues/3030
> fix: work around version parsing by only parsing if site-packages is enabled

- python/private/py_wheel.bzl
- tests/tools/BUILD.bazel
- tests/tools/wheelmaker_test.py
- tools/wheelmaker.py
Include a minor change to `arcname_from` to support cases where
the distribution_prefix is the empty string.
Fixes #3017
> docs,tests: Clarify how py_wheel.strip_path_prefixes works; add test case

- CHANGELOG.md
- python/runfiles/BUILD.bazel
Per the guidance in #2503, this is a quick fix just to restore type-checking for the runfiles package. It does not address or investigate further whether py.typed data dependencies in direct `py_library` dependencies of `py_wheel` should be automatically included as inputs to the wheel. 
Fixes #2503
> fix: add py.typed to runfiles py_wheel so it gets packaged

- CONTRIBUTING.md
A lot of this should go without saying, but I want to have a written reference we
can refer to and so it's clear to potential contributors.
The two basic points it makes is that AI-assisted contributions are allowed, but
they're treated no different than regular contributions, so all the usual expectations
apply.
> docs: doc expectations of ai-assisted contributions

- CHANGELOG.md
- python/private/local_runtime_repo.bzl
Apparently, Macs can mis-report their include directory.
Since includes are only needed if C extensions are built, skip watching the directory
if it doesn't exist.
Work around for https://github.com/bazel-contrib/rules_python/issues/3043
> fix(local-toolchains): don't watch non-existent include directory

- CHANGELOG.md
- python/private/pypi/whl_library_targets.bzl
- tests/pypi/whl_library_targets/whl_library_targets_tests.bzl
The refactoring to move the pkgutil shim generation to build phase inverted
the logic for when it should be activated. When
`enable_implicit_namespace_pkgs=True`, it means to not generate the pkgutil shims
("respect the Python definition of the namespace package").
To fix, just invert the logic that activates it.
A test will be added in a subsequent PR because the necessary helper isn't
in the 1.5 branch.
Fixes https://github.com/bazel-contrib/rules_python/issues/3038
> fix(pypi): only generate namespace package shims if implicit namespaces are disabled

- CHANGELOG.md
- python/private/pypi/BUILD.bazel
- python/private/pypi/evaluate_markers.bzl
- python/private/pypi/extension.bzl
- python/private/pypi/parse_requirements.bzl
- python/private/pypi/pep508_env.bzl
- tests/pypi/extension/extension_tests.bzl
- tests/pypi/pep508/evaluate_tests.bzl
Before it seems that we were relying on particular names in the pipstar
platforms. This ensures that we rely on this less. Whilst at it fix a
few typos and improve the formatting of the code.
Work towards #2949
Work towards #2747
> fix(pypi): correctly handle custom names in pipstar platforms

- python/private/version.bzl
- tests/version/version_test.bzl
When parsing the local identifier segment of `<digit><letter>` the parser would
give an error saying the letter was unexpected.
What was happening was `accept_digits()` consumed up to the first non-digit, and
considered this success, which prevented calling `accept_alnum()` to finish
the parsing.
To fix, only call `accept_alnum()`, then post-process the value to normalize
an all-digit segment.
I'm guessing `accept_digits()` stopping at the first non-digit is WAI because
it expects to parse e.g. "3.14b", where the caller handles subsequent
characters.
Along the way, some minor doc improvements to the parser code.
Fixes https://github.com/bazel-contrib/rules_python/issues/3030
> fix: parsing local version with digit followed by non-digits

- CONTRIBUTING.md
- docs/devguide.md
Mentions the whl_from_dir repository rule in our dev guide.
> docs: add whl_from_dir to dev guide docs

- CHANGELOG.md
- gazelle/python/file_parser.go
- gazelle/python/file_parser_test.go
- gazelle/python/testdata/from_imports/import_nested_var/__init__.py
A python import may be imported as:
```
from foo.bar.application.\
pipeline.model import (
Baz
)
```
However, gazelle fails to resolve this import with the error:
`line 30: "foo.bar.application.pipeline.model\\\n     pipeline.mode.Baz" is an invalid dependency:`
Clean up the imports such that whitespace and \n are removed from the import path.
> fix(gazelle) Update gazelle to properly process multi-line python imports

- docs/pypi/lock.md
- python/private/pypi/pip_compile.bzl
While pyproject.toml is supported by piptools, dependency groups aren't. They can be
emulated by using multiple files. Explain how to do that in the docs and link to
the upstream feature request (https://github.com/jazzband/pip-tools/issues/2062)
Along the way, link to our own feature request for pylock.toml support in pip.parse.
> docs: tell how to emulate dependency groups with pip-compile

- gazelle/manifest/manifest.go
Ideally developers should always re-run the manifest generator, which will update the hash for them.
However I've got clients where the CI system is the only place that all the dependencies can resolve, either because of credentials needed to access the wheelhouse/PyPI, or because of disk exhaustion from massive wheels.
Printing the difference allows a red PR to be greened up just by reading the CI log.
> refactor(gazelle_manifest): print the wrong hash when encountered

- CHANGELOG.md
- python/private/pypi/extension.bzl
- tests/pypi/extension/extension_tests.bzl
Closes #2921
For a single pypi repo with multiple python versions, `all_requirements` fail when a pypi package supports Python version A but not version B. In this case, the pypi package would be included only in requirements lock file for version A, not in one for version B. However, the failure occurs since the package is included in `all_requirements` even for Python version B.
(Minimal reproduction: https://github.com/dotoleeoak/rules-python-2921-repro)
This happens since `packages` parameter for `hub_repository` targets are including all packages across all requirement lock files. Instead of union of packages, intersection of packages for requirement files should be passed to `packages` and exposed to `all_requirements` macro, so that those packages are compatible with all Python …
> fix(pypi): expose pypi packages only common to all python versions

- CHANGELOG.md
- python/private/repl.bzl
- python/private/repl_template.py
When a REPL target is run from an external Bazel module, the `stub_path` can have path components in it (e.g. "/..") which get rejected by the `Rlocation()` function in `runfiles.py` for not being normalized. This commit normalizes the path before it's passed to `Rlocation()`.
Fixes #3101
> fix: normalize stub_path in repl.bzl

- CHANGELOG.md
- python/private/pypi/simpleapi_download.bzl
- tests/pypi/simpleapi_download/simpleapi_download_tests.bzl
Closes #2985
Suppose invalid `experimental_index_url_overrides` in `pip.parse` is set like below.
```bzl
pip.parse(
experimental_index_url = "https://pypi.org/simple",
experimental_index_url_overrides = {"mypy": "https://invalid.com"},
hub_name = "pypi",
requirements_lock = "//:requirements_lock.txt",
)
```
It fails as follows, showing only "pypi.org" as pypi index url, not "invalid.com" for for `mypy` package.
```
Error in fail: Failed to download metadata for ["mypy"] for from urls: ["https://pypi.org/simple"].
If you would like to skip downloading metadata for these packages please add 'simpleapi_skip=["mypy"]' to your 'pip.parse' call.
```
To show overridden url for each package, show url of each package that has been failed to download metadata. The error message with this PR is like …
> fix(pypi): show overridden index urls in pypi download error

- CHANGELOG.md
- gazelle/README.md
- gazelle/python/testdata/relative_imports_package_mode/BUILD.in
- gazelle/python/testdata/relative_imports_package_mode/BUILD.out
- gazelle/python/testdata/sibling_imports_disabled/BUILD.in
- gazelle/python/testdata/sibling_imports_disabled/BUILD.out
- gazelle/python/testdata/sibling_imports_disabled/README.md
- gazelle/python/testdata/sibling_imports_disabled_file_mode/BUILD.in
- gazelle/python/testdata/sibling_imports_disabled_file_mode/BUILD.out
- gazelle/python/testdata/sibling_imports_disabled_file_mode/README.md
- gazelle/pythonconfig/pythonconfig.go
Prefix `experimental_allow_relative_imports` with `python_` to match the rest of the directives.
1.6.0 hasn't been released yet, so this is a non-breaking change.
> fix(gazelle): Rename experimental_allow_relative_imports directive to follow convention

- docs/BUILD.bazel
- docs/README.md
- docs/gazelle.md
- docs/index.md
- gazelle/README.md
- gazelle/docs/BUILD.bazel
- gazelle/docs/index.md
Part of #3082
First of probably 5 PRs.
+ Set up the Bazel config so that the rules_python root docs can reference and use the gazelle/docs directory.
+ Replace the original `docs/gazelle.md` with `gazelle/docs/index.md`
+ Migrate general info from `gazelle/README.md` to `gazelle/docs/index.md`
+ Mechanical updates:
+ Wrap at ~80 chars
+ Use MyST directives and roles.
+ Also a drive-by update to building and running docs _without_ `ibazel`.
> docs(gazelle): Start migrating Gazelle docs to ReadTheDocs, part 1 of ~5

- gazelle/README.md
- gazelle/docs/development.md
- gazelle/docs/index.md
Fixes #3082
6th of 5 PRs.
+ Migrate gazelle development docs from `gazelle/README.md` to `gazelle/docs/development.md`
+ Add information on writing tests
+ Mechanical updates:
+ Wrap at ~80 chars
+ Use MyST directives and roles.
> docs(gazelle): Migrate Gazelle docs to ReadTheDocs, part 6/5: development

- CHANGELOG.md
- python/private/runtime_env_toolchain_interpreter.sh
In some environments, `which` doesn't work correctly under Bazel, while `command -v` does.
I think the difference is that `command` is a shell builtin (and POSIX compliant), whereas `which` is not:
```
$ sh -c 'builtin command -v python3'
/usr/bin/python3
$ sh -c 'builtin which python3'
sh: line 1: builtin: which: not a shell builtin
```
While `command -v` performs fewer checks under the hood, it is more portable.
> fix: use "command -v" to find interpreter in $PATH

- CHANGELOG.md
- gazelle/README.md
- gazelle/docs/annotations.md
- gazelle/docs/directives.md
- gazelle/docs/installation_and_usage.md
Primary updates:
+ Use Definition List
+ Move the annotation/directive description to the definition line
Secondary updates:
+ Add missing directive arguments. For example, `# gazelle:python_extension` becomes `# gazelle:python_extension value`.
+ Address WIP lines for "allowed values"
+ Link things with `{term}`.
Fixes #3142.
> docs(gazelle): Use definition lists instead of bullets for Gazelle docs

- CHANGELOG.md
Fixes #3135
The cherry-picks in the release/1.5 branch already include the fixes
to the changelog, so this PR won't need to be cherry-picked itself.
> doc: changelog cherry-picks for 1.5.2

- CHANGELOG.md
Move the changelog note for the fix to #3043 into the 1.5.3 section, since that's the
version it will be released with.
> docs: move changelog note to 1.5.3 section

- docs/howto/get-python-version.md
Have the example that gets the python version also link to the provider. Also mention
that more than just the version is available.
> docs: link to PyRuntimeInfo and mention it has more than example shows

- python/private/pypi/extension.bzl
- tests/pypi/extension/extension_tests.bzl
Before this PR the configuration for platforms would be built
non-incrementally, making it harder for users to override particular
attributes of the already configured ones.
With this PR the new features introduced in #3058 will be easier to
override.
Work towards #2747
> feat(pypi): incrementally build platform configuration

- python/private/get_local_runtime_info.py
Search directory for libraries should look in the same directory as sys._base_executable. Since sys._base_executable may be unset, fallback to sys.executable
Found this when trying to build using a venv for [tensorstore](https://github.com/google/tensorstore) on Windows:
* Github CI uses nuget to download Python.
* Build sets up a Python venv.
The venv does not include all the lib directories required to link an extension.
Fixes https://github.com/bazel-contrib/rules_python/issues/3172
> fix(local_runtime): Search for libs in sys._base_executable when available.

- CHANGELOG.md
- python/private/pypi/extension.bzl
- tests/pypi/extension/extension_tests.bzl
With this we move closer towards starting playing with the API to fully
replace `pip.parse` with `pip.configure` builder pattern for better
expressiveness.
Work towards #2747
> feat(pypi): builder for netrc and auth_patterns

- CHANGELOG.md
- docs/pypi/use.md
- gazelle/docs/annotations.md
- python/private/pypi/extension.bzl
Doc updates for 1.6 release
Work towards https://github.com/bazel-contrib/rules_python/issues/3188
> docs: update for 1.6 release

- CHANGELOG.md
- python/private/python_bootstrap_template.txt
- python/private/stage1_bootstrap_template.sh
- tests/bootstrap_impls/bin_calls_bin/BUILD.bazel
- tests/bootstrap_impls/bin_calls_bin/inner.py
- tests/bootstrap_impls/bin_calls_bin/outer.py
- tests/bootstrap_impls/bin_calls_bin/verify.sh
- tests/bootstrap_impls/bin_calls_bin/verify_script_python.sh
- tests/bootstrap_impls/bin_calls_bin/verify_system_python.sh
- tests/support/support.bzl
The stage1 bootstrap script had a bug in the find_runfiles_root
function where it would unconditionally use the RUNFILES_DIR et al
environment variables if they were set.
This failed in a particular nested context: an outer binary
calling an inner binary when the inner binary isn't a data
dependency of the outer binary (i.e. the outer doesn't contain
the inner in runfiles). This would cause the inner binary to
incorrectly resolve its runfiles, leading to failures. Such
a case can occur if a genrule calls the outer binary, which has
the inner binary passed as an arg.
This change adds a check to validate that the script's entry point
exists within the inherited RUNFILES_DIR before using it. If the
entry point is not found, it proceeds with other runfiles discovery
methods. This matches the …
> fix(bootstrap): handle when runfiles env vars don't point to current binary's runfiles

- RELEASING.md
- tests/tools/private/release/BUILD.bazel
- tests/tools/private/release/release_test.py
- tools/private/release/BUILD.bazel
- tools/private/release/release.py
Right now, it just updates the changelog and replaces the version placeholders.
> chore: release helper tool

- CHANGELOG.md
- gazelle/docs/directives.md
- gazelle/python/BUILD.bazel
- gazelle/python/python_test.go
Fixes #3209.
Revert the change to `//:gazelle_binary` so that it once again only generates python code. We then create a new, private target `//:_gazelle_binary_with_proto` that gets used by tests.
Update docs accordingly.
Longer term, I'd like to adjust the `test.yaml` file to include a section:
```yaml
config:
gazelle_binary: _gazelle_binary_with_proto
```
So that test cases that need to generate `(py_)proto_library` targets can use the multi-lang Gazelle binary and that tests that do _not_ need to generate proto targets can use the single-lang Gazelle binary.
However, there were some minor roadblocks in doing so and thus I'm doing this quick-to-implement method instead.
> fix(gazelle): Do not build proto targets with default Gazelle

- CHANGELOG.md
- python/private/get_local_runtime_info.py
fix(local_runtime): Search for libs in sys._base_executable when available. (#3178)
Search directory for libraries should look in the same directory as
sys._base_executable. Since sys._base_executable may be unset, fallback
to sys.executable
Found this when trying to build using a venv for
[tensorstore](https://github.com/google/tensorstore) on Windows:
* Github CI uses nuget to download Python.
* Build sets up a Python venv.
The venv does not include all the lib directories required to link an
extension.
Fixes https://github.com/bazel-contrib/rules_python/issues/3172
---------
Co-authored-by: Richard Levasseur <richardlev@gmail.com>
> backport: PR#3178 to 1.5

- CHANGELOG.md
Update the main changelog with 1.5.4 notes from #3217
> docs: Add 1.5.4 release notes to changelog

- AGENTS.md
As I've used agents to do work, I've noticed some recurring advice and behaviors.
Create and AGENTS.md to capture this and make it easier to get starting using them.
> chore: add AGENTS.md to help AI agents work with rules_python

- .github/workflows/release.yml
- RELEASING.md
This makes it possible to manually invoke the release workflow and skip the pypi upload. This is useful if the release workflow was cancelled (or failed) after the pypi upload step.
Work towards https://github.com/bazel-contrib/rules_python/issues/3188
> chore: allow release workflow to be manually run and skip pypi upload

- RELEASING.md
- tests/tools/private/release/BUILD.bazel
- tests/tools/private/release/release_test.py
- tools/private/release/BUILD.bazel
- tools/private/release/release.py
This makes the release tool determine the next version automatically. It does so
by searching for the VERSION_NEXT strings. If VERSION_NEXT_FEATURE is found, then
it increments the minor version. If only patch placeholders are found, then it
increments the patch version.
When the latest version is an RC, an error is raised. This is to protect against
accidentally running it when we're in the middle of the RC phase.
> chore: make release tool auto detect next version

- gazelle/manifest/copy_to_source.py
Replace `os.environ.get("BUILD_WORKSPACE_DIRECTORY")` with `os.environ["BUILD_WORKSPACE_DIRECTORY"]`.
The former may return None if the environment variable is not set, in which case the code will crash with a TypeError when the line is run since the result is concatenated with a `pathlib.Path` object, and is therefore making it impossible to use rules_python_gazelle_plugin along with rules_mypy:
These changes allow rules_mypy users to also use rules_python_gazelle_plugin without having to work around the type error.
Now if the environment variable is not set, the code will still crash, but now with an error that better indicates the failed precondition, namely `KeyError("BUILD_WORKSPACE_DIRECTORY")` rather than `TypeError("unsupported operand type(s) for /: 'PosixPath' and 'NoneType')`.
> refactor(gazelle): report missing BUILD_WORKSPACE_DIRECTORY key more directly

- CHANGELOG.md
- docs/environment-variables.md
- python/private/py_executable.bzl
- python/private/python_bootstrap_template.txt
- python/private/stage2_bootstrap_template.py
- python/private/zip_main_template.py
- tests/base_rules/py_executable_base_tests.bzl
- tests/bootstrap_impls/sys_path_order_test.py
This changes the system_python bootstrap to use a 2-stage process like the script
bootstrap does. Among other things, this means the import paths are written to
a generated file (`bazel_site_init.py`, same as boostrap=script) and sys.path
setup is performed by the Python code in stage 2.
Since the PYTHONPATH environment variable isn't used, this fixes the problem on
Windows where the value is too long.
This also better unifies the system_python and script based bootstraps because the
same stage 2 code and bazel_site_init code is used.
Along the way, several other improvements:
* Fixes path ordering for system_python. The order now matches venv ordering
(stdlib, binary paths, runtime site packages).
* Makes the venv-based solution work when the site module is disabled (`-S`).
* Makes …
> fix(system_python): write import paths to generated file instead of using PYTHONPATH

- docs/conf.py
Doc builds for PR were failing because the readthedocs_ext.external_version_warning
plugin wasn't handling something correctly. Activating it manually was originally
done to get the warning banners to appear, but it looks like RTD now displays a
warning banner without this special plugin being needed.
Since it's now unnecessary, remove the code that can activate it.
> docs: fix pr doc builds by removing external_version_warning plugin

- python/private/py_executable.bzl
Bazel tends to make files executable, even if ctx.actions.write() or ctx.actions.expand_template() is called without is_executable = True. However, in an analysis tool of mine that is a bit more pedantic than Bazel this leads to the issue that py_binary() targets can't be executed due to them not having a +x bit.
Considering that the stage2 bootstrap is marked executable, let's mark is_executable for consistency.
> fix: ensure the stage1 bootstrap is executable

- .bazelci/presubmit.yml
With some core Bazel changes to flags coming that will affect us, and the difficulty it
is to keep the bazel-at-head-and-downstream pipeline green, I figured it'd be a good idea
to add a CI job that uses the weekly Bazel release so we can identify problems sooner
and more obviously.
The CI job only run on Ubuntu to save CI slots and is won't block merges if it has failures.
> tests: add non-blocking ci config for bazel rolling

- python/private/attributes.bzl
- python/private/py_runtime_rule.bzl
Remove `_native_rules_allowlist` attribute as it is no-op
This is needed to allow removing the deprecated flag `--native_rules_allowlist` from bazel.
Work towards: https://github.com/bazel-contrib/rules_python/issues/3252
> build: remove no-op _native_rules_allowlist

- CHANGELOG.md
- python/private/pypi/extension.bzl
This fixes the changelog and manually changes the version updated tag.
The changes have been also cherry-picked to the release branch as I saw
release fail in the [workflow]. Hence this has become a 1.6.3 instead.
[workflow]: https://github.com/bazel-contrib/rules_python/actions/runs/17894155072/job/50878515841
Fixes #3273
> docs: move 1.6.3 related changelog

- python/py_binary.bzl
- python/py_cc_link_params_info.bzl
- python/py_info.bzl
- python/py_library.bzl
- python/py_runtime.bzl
- python/py_runtime_info.bzl
- python/py_runtime_pair.bzl
- python/py_test.bzl
A followup to #3282 to finish up the cleanup and remove the unnecessary
`starlark` usage in naming.
> refactor: rename symbols in re-exports

- CHANGELOG.md
- python/uv/private/lock.bzl
A platform runtime is when the interpreter is provided as an absolute path to Python
instead of bundled in the runfiles. The uv lock rule almost worked, it just didn't
handle the runtime files being empty in such a case.
To fix, use an empty depset to satisfy the subsequent APIs that use it.
> fix(uv): make uv lock rule work with platform python runtime

- docs/BUILD.bazel
- python/private/BUILD.bazel
The original PR omitted the target from the docs, so it was absent.
Along the way, fix some incorrect deps for its target so docs build.
> docs: add config bzlmod extension to docs

- python/versions.bzl
The musl entry got lost as part of a refactoring. Add it back to the platforms
that generate freethreaded variants.
Fixes https://github.com/bazel-contrib/rules_python/issues/3286
> fix(toolchains): add musl list of freethreaded runtimes (workspace)

- python/private/BUILD.bazel
- python/private/py_runtime_rule.bzl
- python/private/version.bzl
- tests/base_rules/py_executable_base_tests.bzl
- tests/base_rules/py_test/py_test_tests.bzl
- tests/config_settings/transition/multi_version_tests.bzl
- tests/exec_toolchain_matching/exec_toolchain_matching_tests.bzl
- tests/pypi/config_settings/config_settings_tests.bzl
- tests/support/BUILD.bazel
- tests/support/platforms/BUILD.bazel
- tests/support/platforms/platforms.bzl
- tests/support/support.bzl
- tests/toolchains/multi_platform_resolution/BUILD.bazel
- tests/toolchains/multi_platform_resolution/resolution_tests.bzl
- tests/uv/uv/uv_tests.bzl
This adds tests that verify toolchains are registered and resolving correctly for
the different variants and platforms for the runtimes.
This also shows that workspace mode isn't registering musl or freethreaded builds
correctly, so use them isn't as easy as simply setting the build flags. For now,
the tests skip those in workspace mode.
Along the way, fix a bug where py_runtime would crash if it got the python version
from the flag, and the version contained more than micro (e.g. "3.14.0rc0")
> tests: add tests to verify toolchain registration

- CHANGELOG.md
- python/private/py_info.bzl
- tests/base_rules/py_info/py_info_tests.bzl
The has_py3_only_sources field was being set to the has_py2_only_sources variable
> fix: wrong value of `has_py3_only_sources` in the PyInfo constructor

- CHANGELOG.md
- MODULE.bazel
Currently, experimental_index_url will trigger network access (by the bzlmod extension
logic) as it figures out the wheels. This is problematic because this network
access always occurs, even if a user isn't using the publish tool. Additionally,
failed network accesses can get Bazel into stuck state requiring `bazel shutdown`
to fix it.
To fix, don't  use experimental_index_url for the publish tool deps.
Once bazelbuild/bazel#24777 is merged, we can roll it back,
but then we may need to check-in the `MODULE.bazel.lock` file into git.
This should be no-op for most users because the publisher is usually run
from with `host == exec`, but there is a small chance that people will
hit #2241.
Work towards #2937
> fix(pip): do not use experimental_index_url for publish_deps

- CHANGELOG.md
- python/private/toolchains_repo.bzl
- tests/toolchains/multi_platform_resolution/resolution_tests.bzl
The musl/freethreaded runtimes weren't being activated when the flags were set. This was
because the toolchains weren't having `target_settings` set, which means extra settings,
such as musl/freethreaded-ness were ignored when matching. The net result is the regular
toolchain, because it's registered earlier, would always match earlier.
To fix, set the target_settings in the toolchain() call. This matches the bzlmod behavior.
Also update the toolchain resolution tests to verify resolution.
Fixes https://github.com/bazel-contrib/rules_python/issues/3262
> fix(toolchains): correctly register musl/freethreaded toolchains for workspace

- CHANGELOG.md
- python/private/flags.bzl
- python/private/py_runtime_pair_rule.bzl
- python/private/py_runtime_rule.bzl
This removes the usages of the disable_py2 fragment attribute. This also makes py2
runtimes rejected (both when set on py_runtime and PyRuntimeInfo)
Because Python 2 support was dropped long ago and other parts of the code reject,
ignore, or don't work with Python 2 already, this is not considered a breaking change.
Work towards: https://github.com/bazel-contrib/rules_python/issues/3252
> chore: reject py2 runtimes and remove usages of ctx.fragments.py.disable_py2

- CHANGELOG.md
- docs/environment-variables.md
- docs/pypi/download.md
Followup to #3225 to add more documentation.
> docs(pipstar): add more docs to make it ready for release
