bazel-contrib/rules_python

rules_python/whl.py

Without this, the metadata.json file is read as bytes instead of a str, and the call
to json.loads() fails with the following error:
```bash
TypeError: the JSON object must be str, not 'bytes'
```

Correctly decode metadata.json into a utf8 str

---

rules_python/piptool.py

The warning is:
You are using pip version 1.5.4, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
In reality, pip is at 9.0.1, but its bundled version of pkg_resources
doesn't know that.
See https://github.com/google/subpar/issues/38

Silence a warning erroneously emitted by pip.

---

README.md

Fixes: https://github.com/bazelbuild/rules_python/issues/24

Note that "{HEAD}" is invalid, not special.

---

WORKSPACE
rules_python/BUILD
rules_python/whl.py
rules_python/whl_test.py

According to https://www.python.org/dev/peps/pep-0427/:
```
{distribution}-{version}.dist-info/METADATA is Metadata version 1.1 or greater format metadata.
```
Currently, rules_python fails when metadata.json is not present. Let's also check for a METADATA file. Tested with `futures==2.2.0` wheel and rules_python can now include that as a requirement, where it couldnt before.

Handle METADATA files in python wheels

---

python/whl.bzl
rules_python/whl.py

When the bazel implementation calls into the wheel python script, it joins the extras arg by commas (https://github.com/bazelbuild/rules_python/blob/3e167dcfb17356c68588715ed324c5e9b76f391d/python/whl.bzl#L27).
When that arg is parsed, it should be split by commas. In the case of multiple args being passed with the same argument name, we should continue to use an Append parser, but with modifications to split by comma.

Split the extras param by comma

---

proposals/2018-11-08-customizing-the-python-stub-template.md
proposals/README.md

This proposal is a response to [bazel #137](https://github.com/bazelbuild/bazel/issues/137) and [bazel #6632](https://github.com/bazelbuild/bazel/pull/6632). It has some open questions that we can take to the discussion bug and mailing lists.

Add proposal for custom stub template

---

python/pip.bzl
python/python.bzl
python/whl.bzl

This reformats the files and applies some automated fixes. This should
help get the repository forward-compatible with Bazel incompatible
changes.
Progress towards #134

Run `buildifier --lint=fix`

---

README.md

Newer versions of Bazel do not contain a native `git_repository` rule so users of `rules_python` are required to load the `git_repository` rule before they can use it to fetch `rules_python`. This PR updates the documentation accordingly.

Add loading of git_repository rule to README

---

proposals/2018-10-25-selecting-between-python-2-and-3.md
proposals/README.md

This splits the syntactic and semantic changes into separate migration flags. The experimental flag for syntax is 100% backwards compatible.
This way, we can flip and eliminate both experimental flags before the incompatible changes are introduced. This allows us to do the incompatible change procedure in a single Bazel release cycle.

Update migration path for py23 proposal

---

proposals/2018-10-25-selecting-between-python-2-and-3.md
proposals/README.md

I don't like the way I was going to add extra provider fields to report better error messages. This updates the doc to say we're not committed to any particular approach. But I think in practice I'll probably do warning messages when a py2-only or py3-only library is depended on by any other py library that's not also py2-only or py3-only respectively. Then when py_binary fails due to version conflicts, it'll direct users to check the log, e.g. by repeating the build with --output_filter.

Py23 proposal: Update plan for py provider fields

---

proposals/2019-02-12-design-for-a-python-toolchain.md
proposals/README.md

This PR adds a design doc on making the native Python rules use the toolchain framework to find their runtimes. Follow bazelbuild/bazel#7375 for discussion and design review.
@katre Please do a quick validation-review that the doc is publishable for review.
Reviewer roles:
- @katre for Bazel team and platform/toolchain domain expertise
- @mrovner for Python rules expertise
- @nlopezgi for remote execution rule logic expertise

Add 'Design for a Python Toolchain' proposal

---

proposals/2019-02-12-design-for-a-python-toolchain.md
proposals/README.md

Ddoc update to reflect what we just discussed. (No detailed review required on your part, but feel free to discuss any issues in bazelbuild/bazel#7375.) Thanks again for the pointer.

Update toolchain proposal to say PyRuntimeInfo is natively defined

---

proposals/2019-02-12-design-for-a-python-toolchain.md
proposals/README.md

I was going to add a boolean field "is_hermetic" to the provider, but the word "hermetic" is problematic and the field really isn't necessary. So instead I clarified some wording and added a short description of the provider constructor.

Update toolchain proposal to clarify wording around platform runtimes

---

WORKSPACE

This lets us build under `--incompatible_remove_old_python_version_api`, and should make us good with https://buildkite.com/bazel/bazelisk-plus-incompatible-flags for Bazel 0.23.

Update subpar dep for incompatible change migrations in Bazel 0.23

---

experimental/BUILD
experimental/examples/wheel/BUILD
experimental/examples/wheel/README.md
experimental/examples/wheel/lib/BUILD
experimental/examples/wheel/lib/module_with_data.py
experimental/examples/wheel/lib/simple_module.py
experimental/examples/wheel/main.py
experimental/examples/wheel/wheel_test.py
experimental/python/BUILD
experimental/python/wheel.bzl
experimental/rules_python/BUILD
experimental/rules_python/wheelmaker.py

Currently only pure python wheels are supported.
This extension builds wheels directly, invoking a simple python script
that creates the zip archive in the desired format instead of using
distutils/setuptools.
This will make building platform-dependent wheels easier in the future,
as bazel will have full control on how extension code is built.
This replaces previous pull request (#128) that had bad merge history.

Add experimental support for building wheels.

---

experimental/python/wheel.bzl

Stop using deprecated depset.union() API - use transitive argument to depset constructor instead.
Also switch to Args api for building the command line instead of flattening the depset.
Fixes #175

Stop using deprecated depset.union API

---

WORKSPACE
examples/extras/BUILD
examples/helloworld/BUILD

Added `python_version = "PY2"` to some examples, and updated subpar dependency.

Update to work with --incompatible_use_python_toolchains

---

experimental/examples/wheel/BUILD
experimental/examples/wheel/wheel_test.py
experimental/python/wheel.bzl
experimental/rules_python/wheelmaker.py

This PR suggests a possible way to address the issues described in https://github.com/bazelbuild/rules_python/issues/199. I added an optional attribute `package_root_path` to the `py_wheel` rule, that specifies the root of the package, relative to the workspace path. 
This patch only fixes the problem for cases in which the entire package is under the same path. If the package bundles dependencies from other paths, those will not be fixed. It would be nice if we could define the prefix on the sources and strip the prefix when we create the final package. Not sure how to do that and will be very happy to hear suggestions, or alternative approaches.
Thanks.
```
py_wheel(
package_root_path = "experimental"
name = ...
distribution = ...
python_tag = ...
version = ...
deps = ...
)
```

added the ability to specify a custom wheel package root

---

examples/boto/requirements.txt

The boto example indirectly requires docutils, but the docutils-0.15.post1
release appears to have a broken wheel: its dist-info directory omits the
`post1` suffix which is part of the version identifier.
We simply prohibit this particular release in requirements.txt.
Fixes #205.

Work around breakage in a dep of the examples

---

tools/update_tools/Dockerfile

Fixes: #208
It looks like you just reference the latest bazel, which means your builds will just break on bazel releases. Instead I suggest pinning to a certain version and then you can walk the version up at your leisure without master sitting there broken.

pin upstream bazel to 0.24

---

README.md
python/BUILD
python/constraints/BUILD
python/defs.bzl
python/private/reexports.bzl
python/python.bzl
python/runfiles/BUILD
python/runfiles/runfiles.py

This series of commits adds exports to `rules_python` for Bazel-packaged Python rule logic. Most importantly, this includes the native rules and providers like `py_binary` and `PyInfo`, but it also includes Starlark-defined constructs that are distributed in `@bazel_tools`.
Work toward bazelbuild/bazel#8893. These exports constitute the new API we wish to migrate users to for that change.
Blocked on:

Add exports for core Python logic that's bundled with Bazel

---

rules_python/piptool.py

Our verification machines were filling up /tmp/ with this temporary
folder.  This patch removes it when piptool exits.

Remove the temporary directory containing cacert.pem when done

---

README.md
docs/BUILD
docs/pip.md
docs/python.md
python/pip.bzl
python/repositories.bzl

Update the README file to explain the difference between the core Python rules
and the packaging rules. Add the py_repositories() hook and recommend that
users add it to their WORKSPACE files.
Background on the py_repositories() hook: I don't know what this might be
useful for at the moment, but I found pip_repositories() to be helpful when I
added a deprecation message for renaming the workspace to @rules_python. So
it's probably a good idea to have this just in case.
Work toward bazelbuild/bazel#9006.

Update README and add py_repositories()

---

WORKSPACE
internal_deps.bzl
internal_setup.bzl

This commit allows rules_python to be a member of the Bazel federation, since it adds the required bzl files related to setup and dependencies.
Moreover, it also changes the WORKSPACE to fetch all non-pip_import dependencies through the federation.
rules_python_internal_setup() in internal_setup.bzl still needs some work since some of the dependencies don't export their proper setup functions yet, which means that the present commit has to work around that particular problem.

Comply with the standards of the Bazel federation

---

experimental/python/wheel.bzl
experimental/rules_python/wheelmaker.py

Change code for handling relative short_paths to fix bug #225.
Fixes #225.

Change code for handling relative short_paths to fix bug #225.

---

packaging/piptool.py

This fixes an issue where if you have bad URLs in your ~/.pip/pip.conf,
pip would pick them up and end up failing bazel. This way we make
pip_import more hermetic and ignore user config.
You can reproduce this issue by adding:
```
[global]
extra-index-url =
https://foo.com/bar
```
To your local `~/.pip/pip.conf`, and executing a `pip_import` rule (it fails faster if your URL returns 500s rather than is just unaccessible)

Pass --isolated to pip

---

README.md
distro/BUILD

We don't have a toolchain method, so don't try to call one in WORKSPACE. Add
optional pip_repositories() call to README and add note that relnotes need
manual editing for this.
+aiuto FYI but force-submitting.

Fix WORKSPACE/distro boilerplate

---

docs/pip.md
docs/whl.md
packaging/piptool.py
python/pip.bzl
python/whl.bzl

This is a rebase of @acumon's #158. It adds a `python_interpreter` attribute to `pip_import` and `whl_library` to allow customizing the command used to launch the Python interpreter. We'll follow this up with creating `pip2_import` and `pip3_import` as wrappers around this feature.
Diffbased against #251, which fixes documentation for these rules.
Work toward #249. Closes #158.

Add python_interpreter attr to pip rules

---

.bazelci/presubmit.yml
python/defs.bzl
tests/load_from_macro/BUILD
tests/load_from_macro/foo.py
tests/load_from_macro/tags.bzl

When adding tags to a native `py_library` rule that is created through a macro we
were not properly considering the case where the tags came from a different
file and therefore were frozen. This caused an error.
Analog of https://github.com/bazelbuild/rules_cc/commit/cfe68f6bc79dea602f2f6a767797f94a5904997f.

Fix immutable frozen set bug in defs.bzl

---

packaging/piptool.py

I ran into this while updating `gvisor` in NixOS (https://github.com/NixOS/nixpkgs/pull/80875); the `requirements.bzl` file generated by `rules_python` isn't reproducible, differing based on the filesystem-order-dependent return from `os.walk`.
This PR is a minimal fix that sorts the repositories in `requirements.bzl` and the return value from `Wheel.extras()`.

packaging/piptool: sort wheels and extras for deterministic output

---

docs/pip.md
python/pip.bzl

The combination of a large `requirements.txt` file and a slow network can
cause the default timeout for `repository_ctx.execute()` to be reached.
This patch exposes that timeout to the `pip_import()` caller so they can
manually specify a longer timeout. E.g.
pip_import(
name = "requirements",
requirements = "//long_list_of_requirements.txt",
timeout = 3600,
)

Add a timeout attribute to pip_import rules.

---

CODEOWNERS
CONTRIBUTING.md
README.md

This adds a more nuanced CODEOWNERS and explains its purpose in CONTRIBUTING.md.
Fixes #291.

Add documentation of community / Bazel team ownership

---

README.md

[`0.0.2`](https://github.com/bazelbuild/rules_python/releases/tag/0.0.2) is out.
Mainly addresses https://github.com/bazelbuild/rules_python/issues/261.
**Related:** https://github.com/bazelbuild/rules_python/pull/303

point README readers to new 0.0.2 release

---

experimental/examples/wheel/BUILD
experimental/python/wheel.bzl

When there are to many file arguments to py_wheel from py_package on Windows 10 I was getting 
this error related to wheelmaker.exe 
```
command is longer than CreateProcessW's limit (32768 characters)
```
Added additional rules to get around this issue.

Fix for when there are so many file arguments it creates the Command To Long error

---

examples/extras/requirements.txt

`bazel build //...` was failing due to "googleapis-common-protos[grpc]"
pip package being unavailable.
It seems to be caused by latest googleapis-common-protos release.
Specify googleapis-common-protos in requirements.txt to be in the previous
version (1.51.0) to fix this.
Fixes #321.

Fix failing build on CI by specifying pip package version

---

docs/pip.md
python/pip.bzl

This allows users to use a custom python interpreter that is built by
another repository rule instead of using a pre-built interpreter binary
that is checked-in.
This tangentially addresses #257 since a common setup is to use the
custom built interpreter in the python toolchain.
For example, see: https://github.com/kku1993/bazel-hermetic-python

Support python interpreter target in pip_import.

---

packaging/whl.py

Addresses https://github.com/bazelbuild/rules_python/issues/289

Ensure deterministic ordering of package dependencies by whl.py

---

packaging/whl.py

Allow py_library sources to be empty.
If --incompatible_disallow_empty_glob is set then generated py_library
targets will fail if there are no .py files.
Examples are pymssql==2.1.4 and cx-Oracle==7.2.3.
Set `allow_empty = True` for glob().
Bazel issue for incompatible_disallow_empty_glob:
https://github.com/bazelbuild/bazel/issues/8195

Fix errors with incompatible_disallow_empty_glob

---

README.md
WORKSPACE
internal_deps.bzl

It's currently a stalled project so it's not useful for us to direct new users there in our README.
Separately it is harder to develop on rules_python since it is currently not self-contained.
For example it's hard to find or adjust the version of rules_pkg without looking/editing in the federation repo.
Tony says this is an okay change: https://github.com/bazelbuild/bazel-federation/commit/63f9746afd4e8564d1033c529ce5065f69d6c7f9#commitcomment-40577834

Remove mention and usage of Bazel Federation

---

.bazelci/presubmit.yml

This will fix recent test breakage in Bazel downstream:
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1588#91ed10dd-2b13-4cee-99cc-88a2e8e58a31
Similar issue and fix:
https://github.com/bazelbuild/bazel/issues/10554
https://github.com/bazelbuild/rules_nodejs/pull/1538

presubmit.yml: Set skip_use_bazel_version_for_test: true

---

experimental/rules_python_external/defs.bzl
experimental/rules_python_external/repositories.bzl

Adding missing docstrings for `experimental/rules_python_external`. Does not add new rules into Stardoc yet. That will be a subsequent pull request.
Our plan is in multiple steps:
- ~bring in the repo to a subdirectory, preserving git history and contributors~
- ~clean up the code, remove mypy, get it functional in that subdirectory~
- ~add an example/integration test proving that it works~
- ~cut a patch release and get some users to test it out~
- communicate our deprecation plan to rules_python users
- **fill in any missing docstrings and include new rules in stardoc** ← **PR is doing part one of this**
- BIG SWITCH: move the rules_python_external implementation to the root, make a legacy/ directory for current impl
- cut a breaking release (a minor, since semver starting with 0. …

rules_python_external: fill missing docstrings

---

README.md
distro/BUILD
examples/pip_install/WORKSPACE
python/repositories.bzl

This adds useless setup code to a users WORKSPACE file.
The idea that we could add some transitive WORKSPACE dependencies is flawed without a working support for this in Bazel. Anything we add in that function later is a breaking change for users, in that they might call our py_repositories() before fetching rules_xx, and we already installed an incompatible rules_xx.
Since adding anything here is a breaking change, we can always put it back later as a breaking change to the rules.
However I would argue strongly that rules_python is too core in the dependency chain for it to *ever* grow transitive dependencies. Like rules_nodejs we should either vendor code we need privately or strip development-only dependencies from our distribution, and never suggest that users call a rules_python …

Remove py_repositories

---

python/pip_install/extract_wheels/lib/bazel.py

Addresses https://github.com/bazelbuild/rules_python/issues/375. 
From looking at the `git blame`, this commentary was introduced when https://github.com/dillon-giacoppo/rules_python_external was still a WIP project. I don't think the commentary reflects any current active intent of the maintainers to remove `all_requirements`. 
cc'ing @dillon-giacoppo to possibly learn original intent of deprecation. 
cc'ing @person142, issue #375 creator. 
-----
Issue Number: https://github.com/bazelbuild/rules_python/issues/375

Remove commentary indicating that 'all_requirements' is deprecated

---

experimental/examples/wheel/BUILD
experimental/examples/wheel/wheel_test.py
experimental/python/wheel.bzl
experimental/tools/wheelmaker.py

This adds support for allowing people to specify which versions
of python a wheel should run on. This was added in PEP 440
This adds support for PEP 440 to wheels
Issue Number: #378
Allows people to specify which versions of python a wheel can support.

Adds the "Requires-Python" metadata support. Fixes #378

---

distro/BUILD

Fix for release related workspace target.
```bash
bazel build //distro:relnotes --sandbox_debug
INFO: Analyzed target //distro:relnotes (2 packages loaded, 14 targets configured).
INFO: Found 1 target...
ERROR: /Users/jonathon/work/rules_python/distro/BUILD:28:16: Executing genrule //distro:relnotes failed (Exit 1) sandbox-exec failed: error executing command
(cd /private/var/tmp/_bazel_jonathon/29bb5d8ab2ff174b67c235f3ce7964dd/sandbox/darwin-sandbox/8/execroot/rules_python && \
exec env - \
PATH=/Users/jonathon/Library/Caches/bazelisk/downloads/bazelbuild/bazel-3.3.1-darwin-x86_64/bin:/Users/jonathon/.nix-profile/bin:/usr/local/opt/scala@2.11/bin:/Users/jonathon/.yarn/bin:/Users/jonath …
```

Upgrading rules_pkg broke //distro:relnotes. Fix target by removing 'setup_file' as it's a no-op now

---

README.md

Partially addresses https://github.com/bazelbuild/rules_python/issues/397, specifically: 
> Then I read the instructions again, tried `pip3_import`, which doesn't exist (under pip.bzl). ...
`pip3_import` is legacy now and not provided in `python/pip.bzl`, so shouldn't be commented as an alternative to `pip_install`. 
cc @dayfine
----

Do not show 'pip3_import' as alternative to 'pip_install' in README

---

python/pip_install/extract_wheels/__init__.py

This fixes the same issue as https://github.com/bazelbuild/rules_python/pull/232 but in another place.
Currently bad user level pip.conf files break pip installations
User level pip.conf files are ignored.
Potentially if people are relying on user local pip.conf files. If they are they should likely be defining that in their build instead though.

Pass --isolated to pip wheel invocation

---

python/pip_install/README.md
python/pip_install/extract_wheels/lib/BUILD
python/pip_install/extract_wheels/lib/bazel.py
python/pip_install/extract_wheels/lib/requirements_bzl_test.py

There isn't an equivalent to `all_requirements` for `whl_requirement`.
A list `all_whl_requirements` is added to `requirements.bzl` which contains all of the wheel targets.
The `all_whl_requirements` list is handy if you want to write a target that takes all of the wheels built by `rules_python` and upload them to a private wheelhouse say.

Add `all_whl_requirements` to match `all_requirements`

---

experimental/examples/wheel/BUILD
experimental/examples/wheel/wheel_test.py
experimental/python/wheel.bzl
experimental/tools/wheelmaker.py

Also allow other Python tag specifiers like cp35, as binary wheels
typically list their required Python versions in the filename.
Was successfully able to upload a binary wheel created with this to PyPI,
and install it with pip.
Currently the code refuses to build a binary wheel.
It accepts platforms other than 'any'.

support binary wheels

---

README.md

Looks like the amended sentence was no longer accurate. See https://github.com/bazelbuild/rules_python/blob/master/python/pip_install/pip_repository.bzl#L85
-------

Remove inaccuracy in README about default py interpreter used by pip_install

---

experimental/examples/wheel/BUILD
experimental/examples/wheel/wheel_test.py
experimental/tools/wheelmaker.py

If in a dependency tree a directory is used as out this is passed as
input_file to wheelmaker which then generates an unhandled error as
it tries to write the directory as a file.

Check if input_file is directory and then add all files within that directory

---

README.md

Issue Number: https://github.com/bazelbuild/rules_python/issues/406

pip_repositories() is deprecated. remove directive to use it from README

---

python/pip_install/repositories.bzl

Updates the vendored version of pip from 20.3.3 to 20.3.4.
Notably, this is slated to be the last version of pip that will support Python 2.
https://github.com/pypa/pip/issues/8936#issuecomment-762080038
It might be prudent to prepare and tag a release of rules_python if this is merged.
I would also suggest that rules_python, at least from the `pip_install` perspective, should target Python 3 only and mention this in the README files. I understand that the Bazel rules_python, in general, will need to support Python 2 until this requirement is removed from Bazel itself (and perhaps internally at Google), but the `pip_install` elements of the rules need not support …

pip: 20.3.3 -> 20.3.4

---

python/pip_install/extract_wheels/lib/bazel.py
python/pip_install/extract_wheels/lib/whl_filegroup_test.py

Using wheels like keyring (https://pypi.org/project/keyring) , `pip_install` fails with an error like
```
File "/private/var/tmp/_bazel_gkorlam/a1f9cb65ef7d02cf04534e97e406c6b9/external/rules_python/python/pip_install/extract_wheels/lib/bazel.py", line 187, in extract_wheel
with open(os.path.join(directory, "BUILD"), "w") as build_file:
IsADirectoryError: [Errno 21] Is a directory: 'pypi__keyring/BUILD'
```
This is because the extracted whl file has a `build` directory in it.
By changing the build file to `BUILD.bazel` it is much less likely to encounter this issue. `pip_install` succeeds in importing the keyring whl after this change.

Use BUILD.bazel file when creating py_library rules of extracted whls

---

.github/PULL_REQUEST_TEMPLATE.md

Currently `CONTRIBUTING.md` links to `/CONTRIBUTING.md`, it's fine for markdown rendering but in the PR, it links to https://github.com/contributing.md instead
- [ x] No

Update PR template link to master CONTRIBUTING.md

---

distro/BUILD

🧹 🧹 ...
Just removing a TODO we don't need anymore. We not longer use a `deps()` function to included dependencies and https://github.com/bazelbuild/rules_pkg/issues/72 shows that it's no longer a desired pattern.
----
----
cc @brandjon

Remove obsolete TODO in //distro

---

distro/BUILD
docs/BUILD
python/pip_install/BUILD

Addressing https://github.com/bazelbuild/rules_python/issues/372
---
> expanding rules_python-0.1.0.tar.gz we see that `/python/pip_install/BUILD` has a load statement from `@bazel_skylib`.
> Users weren't told to depend on that, nor did our WORKSPACE dependencies install such a thing.
Moreover until the new Bazel external deps story is landed, adding such a dependency is a nasty breaking change for users where they may have a hard time getting the right version of bazel_skylib to satisfy rules_python along with anything else that transitively depends on it.
Issue Number: https://github.com/bazelbuild/rules_python/issues/372
`/python/pip_install/BUILD` no longer has a load statement …

Remove bzl_library from python/pip_install/BUILD so that skylib dep is not exposed to end-users

---

.bazelci/presubmit.yml

- [] Refactoring (no functional changes, no api changes)
This TODO was introduced here: https://github.com/brandjon/rules_python/commit/29260b3203fec444a4a8d17038c6ce238de86a7f
I figure this TODO is now well obsolete and we can undo it. CI should still pass, and it does. 
_Note:_ I don't know why it shouldn't just be `//...` instead of `...`. Both work in CI, but `bazel build ...` is invalid when run locally. 
cc @brandjon

Remove TODO: Now past Bazel 0.29 so can go back to using '...' in CI

---

BUILD
python/BUILD
python/pip_install/BUILD

A patch is required to access the required bzl files for docs in external rulesets
Downstream rulesets can depend on `//:bzl` to provide all `.bzl` sources needed to build docs for bzl files that include loads from rules_python
We do a similar approach in rules_nodejs 🙂

feat: add public filegroups containing bzl files to allow downstream rulesets to generate docs

---

README.md

@thekyz helpfully pointed out this issue in the README. Ref: https://github.com/bazelbuild/rules_python/issues/439
Doing `requirement("foo[bar]")` to specify extras is only supported/required in `pip_import`. 
This functionality was introduced here: https://github.com/bazelbuild/rules_python/issues/439
----

README fix: You only need to specify extras in the requirement macro if using legacy pip_import

---

.github/workflows/stale.yml

Ideally we would have the resources to address and resolve all issues, and review and merge all pull requests. But we don't.
Rather than leave these open indefinitely, it's better to set user expectations that these will just age out.

Add configuration for stale bot

---

python/pip_install/pip_repository.bzl

Closes https://github.com/bazelbuild/rules_python/issues/440
The build file in the repository roots generated by `pip_repository` is still `BUILD` and not `BUILD.bazel`. Since `pip_parse` has only one layer of directories, the external repository then ends up with a `BUILD` and a `BUILD.bazel`.
It's now called `BUILD.bazel`, which means `pip_parse` later overwrites it with the final `BUILD.bazel`.
This prevents a regression of https://github.com/bazelbuild/rules_python/pull/427 with `pip_parse`.

Also name the BUILD file in external repository roots BUILD.bazel

---

python/pip_install/extract_wheels/lib/bazel.py
python/pip_install/extract_wheels/lib/whl_filegroup_test.py

Wheel targets are broken with `pip_parse`. This is because currently `pip_parse` extracts the wheel into the repository root, but then deletes it here:
https://github.com/bazelbuild/rules_python/blob/master/python/pip_install/extract_wheels/lib/bazel.py#L251
This doesn't happen for `pip_install` because it copies the wheel into the relevant subdirectory:
https://github.com/bazelbuild/rules_python/blob/master/python/pip_install/extract_wheels/lib/bazel.py#L212
Instead of deleting the wheel unconditionally, only do it for the non-incremental case.
None

Don't delete wheels from external repos with pip_parse

---

python/pip_install/pip_repository.bzl

I have a `.bzl` file which loads the `requirements.bzl` file of a [pip_repository](https://github.com/bazelbuild/rules_python/blob/017eb4ffb87b97a66be968df33391ef36ba474cb/python/pip_install/pip_repository.bzl#L170-L212) and I want to use [stardoc](https://github.com/bazelbuild/stardoc) to generate documentation it. However, I'm not able to access `requirements.bzl` because it's not publicly visible outside of the repository.
The change in this PR exports the file so it can be used for generating documentation.

`requirements.bzl` is now visible outside `pip_repository`s

---

python/pip_install/extract_wheels/lib/bazel.py

An error message for `pip_install` still references `pip_install_incremental` instead of `pip_parse`.
Refer to `pip_parse` instead.
None

Replace old pip_install_incremental reference

---

python/pip_install/requirements.bzl

* The `requirements_in` arg cannot be popped from `**kwargs` because it is a named argument. So the arg value is always: `name + ".in"`
* The `requirements_txt` arg is actually set by passing `requirements_locked` to the macro. If you pass the latter, you can set the former. If you just pass the former, the arg value is always `name + ".txt"`, similar to the above.
The result is that the `.in` file must always be `${name}.in` and you have to set the lock file name via an undocumented kwarg.
**Both args are given `None` defaults which the macro body will immediately detect and replace with the `name + ".in"` and `name + ".txt"` value if needed.**
With this change the following macro instantiation now works as expected: 
```python
compile_pip_requirements(
name = "requirements_annotated", …
```

compile_pip_requirements: Fix defaulted macro args behaviour

---

examples/pip_install/requirements.txt
python/pip_install/pip_compile.py

The `compile_pip_requirements` rule will list the requirements as coming from `./requirements.in`.
Issue Number: closes https://github.com/bazelbuild/rules_python/issues/470
It will be attributed to `requirements.in`, which lets it work out-of-the-box with tools like dependabot.
None

Remove leading ./ in compile_pip_requirements

---

python/pip_install/pip_compile.py

This way if users have bazel wrappers the error message can be correct
Currently the output recommendation is always `bazel run TARGET`
If users add `env = {"CUSTOM_COMPILE_COMMAND": "foo"}` the output recommendation will be `foo`
We might prefer an attribute over an env var override here, happy to go down either path

Allow overriding CUSTOM_COMPILE_COMMAND

---

python/pip_install/extract_wheels/lib/namespace_pkgs.py

See https://github.com/dillon-giacoppo/rules_python_external/pull/54/files for change that removed usage of `wheel` module.

Remove unnecessary import in namespace_pkgs.py

---

docs/BUILD
docs/packaging.md
docs/pip.md
docs/python.md
docs/whl.md
internal_deps.bzl
update_docs.sh

Using https://github.com/bazelbuild/stardoc/releases/tag/0.4.0
> First release of Stardoc under the new repository location bazelbuild/stardoc. Please use this repository for future Stardoc releases instead of its old location.
Begins addressing https://github.com/bazelbuild/rules_python/issues/255. We can close that issue once we've removed needless `<code>` tags in docs, and instead use backticks.

Migrate from bazelbuild/skydoc to bazelbuild/stardoc

---

python/pip_install/extract_wheels/lib/purelib.py

Fixing https://github.com/bazelbuild/rules_python/issues/435
Issue Number: https://github.com/bazelbuild/rules_python/issues/435
`pip_install` can't install `catboost <= 2.25.0` because it doesn't specify 'Root-Is-Purelib' at all.
Absence of `'Root-Is-Purelib'` in wheel metadata means the value is assumed false.

pip_install: avoid assuming 'Root-Is-Purelib' is provided in all WHEEL files

---

python/pip_install/extract_wheels/lib/namespace_pkgs.py

Noticed this a couple of week ago. How did it survive this long 😓. 
----

Remove reference to 'rules_python_external'

---

python/pip_install/requirements.bzl

The `py_test` target created by `compile_pip_requirements` can receive tags via `**kwargs` but the `py_binary` target (.update) cannot. 
Both targets created by the `compile_pip_requirements` macro can receive tags.

Ensure pip_compile_requirements' py_binary target can recieve 'tags'

---

README.md

Should really include this step in the release, and it's not complicated to do that because the README isn't distributed and thus doesn't influence the sha256.
**0.3.0 ->** https://github.com/bazelbuild/rules_python/releases
----

Update README to point at latest release, 0.3.0.

---

README.md

On re-reading this part of the README, I thought the "central repo" and "knows about" wording could be improved.
<a href="https://github.com/bazelbuild/rules_python/blob/jonathon--improve-README-code-cmmnt-june2021/README.md" target="_blank" rel="noopener noreferrer"><strong>🖱 Click me to preview README changes</strong></a>

Improve README documentation of pip_install rule [tiny]

---

DEVELOPING.md

Change directly related to #500 
As far as I can see these are the only relevant `master` refs in the codebase.
----

Terminology update 'master' to 'main' in DEVELOPING.md

---

README.md
python/pip_install/extract_wheels/lib/bazel.py
python/pip_install/extract_wheels/lib/namespace_pkgs.py
python/pip_install/extract_wheels/lib/namespace_pkgs_test.py
python/pip_install/extract_wheels/lib/whl_filegroup_test.py
python/pip_install/parse_requirements_to_bzl/__init__.py

fixes #499 
Pathlib.Path normalizes path names, which caused lookups of relative
paths using the special '.' directory path to fail to find parents of
standard packages.
Drive-by change fixes passing quiet argument to child repos.
pip_parse fails to find implicit namespace packages.
Issue Number: #499 
pip_parse can find implicit namespace packages.

Fix regression in pip parse for finding implicit namespace packages.

---

python/pip_install/parse_requirements_to_bzl/extract_single_wheel/__init__.py

On Windows, when using pip_parse, pip would fail with following error:
Could not open requirements file: [Errno 13] Permission denied: ...
This is due to Python holding a handle to the temporary file preventing
pip, which is run as a sub-process, from reading it. For more
information, see: https://bugs.python.org/issue14243
Closing the requirements file before running pip solves the problem.
---
`pip_parse` works on Windows.

Fix extract_single_wheel for Windows

---

README.md

Missing this required update after doing the `master` -> `main` switch.
----

Replace obsolete 'master' branch refs in README

---

python/pip_install/extract_wheels/lib/bazel.py
python/pip_install/parse_requirements_to_bzl/__init__.py

A wheel is [documented](https://www.python.org/dev/peps/pep-0491/#file-contents) to contain both `.dist-info` and `.data` directories which contain additional metadata for a particular package. However, even though the pip repository rules extract wheel contents into the repository directory, data in these directories are not exposed. In order to access this, the `:whl` target must be consumed and unzipped again, even though this information already lives in the pip repository generated by Bazel. Something should be done to expose this data so users don't have to write additional parsers.
This pull request exposes files in `.data` and `.dist-info` in individual …

Added targets for data and dist-info to pip generated targets

---

examples/wheel/BUILD
examples/wheel/wheel_test.py
python/packaging.bzl
tools/wheelmaker.py

Escape characters in the wheel filename.
Note the implementation is buggy, it replaces non-ascii (unicode) letters in the filename. Unfortunately, starlark isalnum function returns wrong result here, and regexp support is not available yet.
Fixes #517.
Issue Number: #517

Escape characters in the wheel filename.

---

python/pip_install/extract_wheels/lib/bazel.py

This is a python convention that wheels are shipped to pypi including their tests.
These shouldn't be used in user code.
We have observed these files expose modules which collide with first-party targets.

py_library generated from wheel shouldn't include tests/ folder

---

python/pip_install/parse_requirements_to_bzl/__init__.py
python/pip_install/parse_requirements_to_bzl/parse_requirements_to_bzl_test.py
python/pip_install/pip_repository.bzl

When using `pip_parse` with a python wrapper script in `python_interpreter` or `python_interpreter_target`, the declared `whl_library` do not use the wrapper script but directly the underlying python interpreter given by `sys.executable`.
We use a portable python distribution that needs some environment adaptation in the `PATH` and `LD_LIBRARY_PRELOAD` variables to run properly. Calling directly the python interpreter binary fails, so `pip_parse` itself is successful but the wheels cannot be retrieved.
- `pip_parse` now transmits `python_interpreter` and `python_interpreter_target` attributes to the `whl_library` targets
- `whl_library` now takes …

pip_parse: Fix when using a python wrapper script

---

python/pip_install/extract_wheels/lib/wheel.py

Dependencies which have a potentially invalid `entry_points.txt` file will currently cause parsing dependencies to fail, rendering your code unbuildable.
The `entry_points` functionality should at this point never result in a fatal error when parsing dependencies. This allows dependencies to continue to be generated as they did before in the event that `entry_points.txt` is malformed.

Fix regression in parsing requirements due to invalid entry points config.

---

docs/BUILD
docs/pip.md
examples/pip_install/BUILD
examples/pip_parse/BUILD
python/pip.bzl
python/pip_install/BUILD
python/pip_install/requirements.bzl

`compile_pip_requirements` is not currently in the docs and seems to otherwise be hidden as a result. This PR fixes that.
`compile_pip_requirements` can now be loaded via `@rules_python//python:pip.bzl` which is also used to populate `docs/pip.md` with the appropriate docs for the rule.

Exposed docs for `compile_pip_requirements`

---

python/pip_install/pip_compile.py

Addresses #507
Issue Number: #507

Fix #507 - Always run from WORKSPACE root in compile_pip_requirements update exe

---

python/packaging.bzl

Currently stable stamps do not make their way into wheels, this is the result of a copy/paste error in https://github.com/bazelbuild/rules_python/pull/554
This change correctly wires up stable status stamp files for stamping `py_wheel` targets.

Fixed stable stamping of wheels

---

python/pip_install/extract_wheels/lib/bazel.py
python/pip_install/extract_wheels/lib/bazel_test.py

Only floating-point objects have an is_integer
method (cf. https://docs.python.org/3.10/library/stdtypes.html#typesnumeric),
so this will actually raise an AttributeError whenever the main function
returns an integer or None.  sys.exit works just fine with any argument type,
so there’s no need to check anything.  The example at
https://packaging.python.org/specifications/entry-points/#use-for-scripts also
doesn’t contain a type check.

Remove return code type check.

---

python/pip_install/extract_wheels/lib/bazel.py

I noticed in some of my builds were getting a bunch of unexpected cache misses and found that some pypi dependencies were including some `__pycache__` contents and left-over `*.pyc` files. I don't believe these are needed or should ever be used by the Bazel rules.
This PR prevents these files from being included in the `pip_parse` and `pip_install` generated `py_library` targets.

Ignore `__pycache__` contents and `*.pyc` files in external dependencies

---

gazelle/configure.go

SUMMARY
Include the file path so it's easier to find the manifest that's causing issues
TEST PLAN
Break a manifest file locally, run gazelle, enjoy the improved message:
```
$ bazel run //:update_build_files
INFO: Invocation ID: e38c7bfb-1566-4f58-9485-efe66594e0d5
INFO: Analyzed target //:update_build_files (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:update_build_files up-to-date:
.bazel/bin/update_build_files-runner.bash
.bazel/bin/update_build_files
INFO: Elapsed time: 0.323s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
gazelle: failed to load Gazelle manifest at /my-project/gazelle_python.yaml: failed to decode manifest file: EOF
```

fix(gazelle): include file path in manifest parsing error message

---

docs/pip.md
examples/pip_parse/BUILD
examples/pip_parse/WORKSPACE
examples/pip_parse/pip_parse_test.py
python/pip.bzl
python/pip_install/extract_wheels/__init__.py
python/pip_install/extract_wheels/lib/arguments.py
python/pip_install/extract_wheels/lib/arguments_test.py
python/pip_install/extract_wheels/lib/bazel.py
python/pip_install/extract_wheels/lib/whl_filegroup_test.py
python/pip_install/parse_requirements_to_bzl/__init__.py
python/pip_install/parse_requirements_to_bzl/extract_single_wheel/__init__.py
python/pip_install/parse_requirements_to_bzl/parse_requirements_to_bzl_test.py
python/pip_install/pip_repository.bzl

Issue Number:
- https://github.com/bazelbuild/rules_python/issues/414
- Closes https://github.com/bazelbuild/rules_python/issues/450
Currently the prefix added to the generated repos for `pip_parse` is hard-coded to `<pip-parse-name>_pypi__` and the prefix added to the generated packages for `pip_install` is hard-coded to `pypi__`.
Allow the user to control the prefix. You still need some prefix to avoid https://github.com/bazelbuild/rules_python/issues/414#issuecomment-789416360, but for `pip_parse` in particular you can make the external repository names more memorable:
```
$ cat requirements.txt
attrs==20.3.0
$ cat WORKSPACE
local_repository(
name = "rules_python",
path = …
```

Allow controlling the prefix added to repos/packages

---

python/pip_install/extract_wheels/lib/BUILD
python/pip_install/extract_wheels/lib/purelib.py
python/pip_install/extract_wheels/lib/purelib_test.py

Merge purelib dir into toplevel even if purelib and toplevel have
subdirs with the same name. See tensorflow-io for an example of
a package which was not installed correctly by rules_python before this
change.
In pip_install and pip_parse rule if you try to install a wheel which has Root-Is-Purelib: false (tensorflow-io is an example), python sources in the .data/purelib dir will not be merged into the root because we skip children of the purelib which have the same basename as a directory in the top level of the wheel.
What rules_python does currently: https://gist.github.com/hrfuller/ccc0420cd5b72b38f6151fa1b5c811e0
After running the example open up the created repo in the bazel …

Make spread_purelib_into_root behave like the wheel was installed by pip

---

python/pip_install/extract_wheels/lib/wheel.py

The zipfile module always uses forward slashes, so we shouldn't use
os.path.join here.
Entry points aren't found on Windows
Entry points should be found on Windows (haven't fully tested it though)

Fix entry point discovery on Windows.

---

.bazelci/presubmit.yml
.bazelrc
docs/BUILD
examples/wheel/wheel_test.py
python/pip_install/extract_wheels/__init__.py
python/pip_install/extract_wheels/lib/BUILD
python/pip_install/extract_wheels/lib/bazel.py
python/pip_install/extract_wheels/lib/wheel.py
python/pip_install/extract_wheels/lib/whl_filegroup_test.py
python/pip_install/parse_requirements_to_bzl/parse_requirements_to_bzl_test.py
python/pip_install/pip_repository.bzl
tools/bazel_integration_test/test_runner.py

This change includes all the necessary fixes and updates to support enabling CI for windows platforms.
Issue Number: https://github.com/bazelbuild/rules_python/issues/2
I don't know if this closes https://github.com/bazelbuild/rules_python/issues/2 but seems related
Updated rules and tests to support windows platforms.
closes https://github.com/bazelbuild/rules_python/pull/572

Enabled CI for Windows

---

README.md

Issue Number: https://github.com/bazelbuild/rules_python/issues/414
Currently the documentation recommends only using `requirement()` to access the `py_library` targets generated by `pip_install` and `pip_parse`.
Update the documentation to specify that using `requirement()` is optional, and that accessing the labels directly is ok.

Update README to say that using `requirement()` is optional

---

python/pip_install/extract_wheels/lib/purelib.py

Follow up for #581 fixing undefined name.

Fix undefined name in purelib.py

---

docs/BUILD
python/BUILD
python/pip_install/BUILD
python/pip_install/extract_wheels/BUILD
python/pip_install/extract_wheels/lib/BUILD
python/pip_install/parse_requirements_to_bzl/BUILD
python/pip_install/parse_requirements_to_bzl/extract_single_wheel/BUILD
python/pip_install/pip_repository.bzl
python/pip_install/private/BUILD
python/pip_install/private/pip_install_utils.bzl
python/pip_install/private/srcs.bzl
python/pip_install/private/test/BUILD

`pip_repository` rules currently only track the root of `rules_python` in order to determine the location of the necessary python files for rendering BUILD files for python packages. Because only the BUILD file is tracked, the repository rule is never made aware of the python sources. This results in situations where the `@rules_python//python/pip_install` source code may be changed but existing `pip_repository` rules will not be updated. 
This change generates a list of source files and passes them to the `pip_repository` rules so it can react to changes made. Now if a change is made to the python code, the repository rule will correctly be re-triggerd.

changes to pip_repository source files now re-trigger the repo rule

---

examples/pip_repository_annotations/WORKSPACE
examples/pip_repository_annotations/requirements.in
examples/pip_repository_annotations/requirements.txt
python/pip_install/parse_requirements_to_bzl/__init__.py
python/pip_install/parse_requirements_to_bzl/parse_requirements_to_bzl_test.py

I ran into an issue where `pip_repository` rules would fail whenever flags were added to `requirements.txt` (or `requirements_lock`). With the diff below, the following exception occurs when running `bazel test //...` in any workspace (here I just happen to have chosen an example at random).
```diff
diff --git a/examples/pip_repository_annotations/requirements.txt b/examples/pip_repository_annotations/requirements.txt
index 51d1dfc..db762cb 100644
--- a/examples/pip_repository_annotations/requirements.txt
+++ b/examples/pip_repository_annotations/requirements.txt
@@ -4,6 +4,8 @@
#
#
+--extra-index-url https://pypi.python.org/simple/
+
wheel==0.37.1 \ …
```

Fixed extra_pip_arg parsing error in pip_repository rules.

---

examples/pip_install/BUILD
examples/pip_install/WORKSPACE
examples/pip_install/pip_install_test.py
examples/pip_parse/BUILD
examples/pip_parse/WORKSPACE
examples/pip_parse/pip_parse_test.py
examples/pip_repository_annotations/BUILD
examples/pip_repository_annotations/pip_repository_annotations_test.py

https://github.com/bazelbuild/rules_python/pull/598 is too big to review so this PR breaks out a component of it.
This updates tests and examples to use a cross platform way of accessing runfiles. This is required to fix tests on windows.

Use `@rules_python//python/runfiles` for examples and tests

---

python/BUILD

With the introduction of the `gazelle` stuff, I can no longer generate docs in my projects. All I really want is the python `bzl_library` target and think it'd make sense to allow it to be public.
This change fixes the use of `stardoc` for generating documentation in external repositories that uses `rules_python` and *does not* use `bazel_gazelle`.

Make python only `bzl_library` target publicly visible

---

python/pip_install/BUILD

Reviewd #601 after it merged. Thanks for fixing this long outstanding annoyance 🙂  @UebelAndre 
If I understand this code correctly the filegroup is only consumed by `//python/pip_install/private:srcs_module` and so you don't need public visibility on the target.

restrict visibility on filegroup target only consumed in 1 place

---

tools/bazel_integration_test/test_runner.py

Currently the integration test runner does not report errors for windows.
The test runner has been fixed and the examples/tests updated to be compatible with windows.
This PR includes the following which are both required to get passing windows builds.
- https://github.com/bazelbuild/rules_python/pull/597
- https://github.com/bazelbuild/rules_python/pull/595

Fix false positive tests in CI for Windows

---

python/pip_install/pip_compile.py
python/pip_install/requirements.bzl

If a `compile_pip_requirements` target is setup in a separate package than where the `requirements_in` file is located, then an incorrect custom compile command is written into the `requirements_txt` file.
This change fixes that so no matter where the `compile_pip_requirements` target is defined, it will always correctly be reflected in the generated files when running the `*.update` target.

Fixed incorrect custom compile commands from `compile_pip_requirements`

---

python/pip_install/extract_wheels/lib/annotation.py

For every use of `pip_repository`, a warning log will be printed about unused `package_annotations` when there aren't any (prints an empty list). There's no reason to print an empty list
A warning will only be printed about unsued annotations if there are actually some that are unused.

conditionally log unused annotations

---

python/pip_install/extract_wheels/lib/bazel.py

This is a followup from https://github.com/bazelbuild/rules_python/pull/626 but allows a few files through

Updated pip_repository data ignore patterns

---

python/pip_install/extract_wheels/lib/bazel.py

This is another followup to https://github.com/bazelbuild/rules_python/pull/632
`WHEEL` files should be deterministic and could be used by certain packages.

Allow `*.dist-info/WHEEL` files into `pip_repository` generated targets

---

python/private/tests/toolchains/versions_test.bzl
python/private/versions.bzl
python/repositories.bzl

This gives us more python patch versions

Allow previous indygreg releases

---

examples/pip_repository_annotations/WORKSPACE
examples/pip_repository_annotations/pip_repository_annotations_test.py
python/pip_install/extract_wheels/lib/bazel.py

Currently `*.dist-info/METADATA` files are excluded in `pip_repository` generated targets. This is incorrect as it's consumed by https://docs.python.org/3/library/importlib.metadata.html
This change allows `METADATA` files to be included in `pip_repository` generated targets, enabling the use of https://docs.python.org/3/library/importlib.metadata.html.

Allow METADATA files in pip_repository generated targets

---

.bazelrc
python/repositories.bzl
python/tests/toolchains/defs.bzl
python/tests/toolchains/run_acceptance_test.py

Fix windows acceptance tests

---

python/versions.bzl

The checksums were being evaluated on `bazel build` instead of `bazel run`.

fix: lazy fetch checksums for toolchains

---

python/repositories.bzl
python/versions.bzl

Allows setting the `TOOL_VERSIONS` and `base_url` from the repo rule.

feat: allow overriding tool versions and base url for predefined Python interpreters

---

.github/workflows/workspace_snippet.sh

Required per https://github.com/bazel-contrib/SIG-rules-authors/issues/11

chore: update GitHub archive url to produce stable SHA

---

.github/workflows/workspace_snippet.sh

We don't put a 'v' prefix on tags, so we shouldn't trim a character from the tag
Also #650 had an incorrect url for stable SHAs :sweat:

release: Fix release snippet

---

python/repositories.bzl

If you define your own `python_register_toolchains.tool_versions` for a version that is not a built in version, then the repository rule rejects it.
This change allows users to define custom python versions that are not already registered in `@rules_python//python:versions.bzl`.

Allow for custom python versions in `python_register_toolchains`

---

.github/CODEOWNERS

Finally getting around to taking @andyscott off auto-enrolment in reviews. 
Others should probably replace him, but that can be managed in a follow-up. For now, this saves me manually removing him from reviewers lists on new PRs.

Update CODEOWNERS. remove andy scott as maintainer

---

python/pip_install/extract_wheels/lib/BUILD
python/pip_install/extract_wheels/lib/annotations_test.py

Currently this test fails on windows systems that don't support symlinks and use `\r\n` as the newline character for checkouts.
This change updates `//python/pip_install/extract_wheels/lib:annotations_test` to work on these windows platforms by sanitizing some of the test inputs and using the `@rules_python//python/runfiles` library to locate test data.

Fix annotations_test on windows systems that don't support symlinks

---

python/repositories.bzl
python/versions.bzl

Not all toolchains are packaged the same. Even older releases of https://github.com/indygreg/python-build-standalone have different archive structures which are incompatible with how toolchains are currently setup.
This change allows for a `strip_prefix` key to be added to `python_register_toolchains.tool_versions` so that users can use reasonably different archive layouts.

Added support for custom `strip_prefix` args in toolchains

---

examples/wheel/BUILD
examples/wheel/wheel_test.py
tools/wheelmaker.py

Fix a bug where path prefix could be stripped from the distinfo directory name.
Fixes bug #682
strip_prefixes was wrongly applied to files in .distinfo directory
Issue Number: 682

Fix issue #682

---

python/repositories.bzl

I have workspace A which uses uses these toolchains and want to load things from workspace A in workspace B. Workspace B does not use the new toolchains. Unfortunately, I'm not able to continue loading workspace A since I need the toolchain repositories defined or I'll fail to be able to load some `*.bzl` files. This change allows me to define the toolchain repositories without registering them so.
Users can now set `register_toolchains = False` on `python_register_toolchains` to define the toolchain repositories but not register them.

Allow toolchain registration to be optional

---

examples/wheel/BUILD
examples/wheel/wheel_test.py
python/versions.bzl

On linux arm64, rules_python using the precompiled python toolchain fails:
```
(11:19:15) ERROR: An error occurred during the fetch of repository 'python3':
Traceback (most recent call last):
File "/home/builder/.cache/bazel/_bazel_laz/99bd544777c52d5a0d8a66ea3b05626a/external/rules_python/python/private/toolchains_repo.bzl", line 81, column 13, in _resolved_interpreter_os_alias_impl
fail("No platform declared for host OS {} on arch {}".format(os_name, arch))
Error in fail: No platform declared for host OS linux on arch aarch64
```
It works on Linux arm64 now. `rules_python` tests pass on an m1 macbook pro in both OSX and Linux.
Some tests on linux-arm64 fail because …

linux-arm64 python binary support

---

gazelle/modules_mapping/def.bzl
python/packaging.bzl

Something changed on Bazel CI (probably the version of buildifier) such that this suddenly broke on the latest nightly master despite us not changing anything.
See https://buildkite.com/bazel/rules-python-python/builds/2694#d430bd0c-f1cb-496c-81ae-6a9eae413f21

Replace host cfg with exec

---

.gitattributes
docs/BUILD
docs/pip.md
docs/pip_repository.md
python/pip.bzl
python/pip_install/pip_repository.bzl

As a common example, we need a compiled requirements file for linux that differs from mac os

Allow for requirements files to differ per platform

---

python/pip_install/extract_wheels/lib/bazel.py

Duplicate method invocation. 
https://github.com/bazelbuild/rules_python/issues/675 introduced the return code handling. 
https://github.com/bazelbuild/rules_python/pull/573/files#diff-cd80d344159f5c70b91dfc2caee848739096387abeda9152d53f601c812b41eaR38 removed the unnecessary type-check but intro'd the 🐛.
Issue Number: https://github.com/bazelbuild/rules_python/issues/675
Only execute the method once.

Remove duplicate method invocation in entry_point generation

---

python/pip_install/extract_wheels/lib/bazel.py

There are some entry_points in the wild that end with a `.py` suffix. This is an extreme edge-case, but this clashes with the native Python rules in Bazel that forbids `py_binary` to end with `.py`.
An example entry_point in the wild that ends with `.py` https://github.com/jupyterhub/jupyterhub-idle-culler/blob/9dba16033485f3c70352edd3255bb0c5905f16ce/setup.py#L15

Handle entry_points that end with .py

---

python/pip_install/extract_wheels/lib/BUILD
python/pip_install/extract_wheels/lib/bazel.py
python/pip_install/extract_wheels/lib/wheel.py
python/pip_install/repositories.bzl

The `Wheel` related parsing / unpacking / installation is using custom written code and the [pkginfo](https://pypi.org/project/pkginfo/) package to parse metadata. This logic is complex and fragile because of the many Python Packaging PEPs it relates to.
Issue Number: https://github.com/bazelbuild/rules_python/issues/671
This PR introduces a modern, PEP standards-compliant library called [installer](https://pypi.org/project/installer/). This package is maintained in the [Python Packaging Authority](https://www.pypa.io/en/latest/) and is written by a few of the current maintainers of `pip`. It is therefore more likely to be processing Wheel files correctly.
This PR is only using …

Init: pypa/installer

---

third_party/github.com/bazelbuild/bazel-skylib/lib/versions.bzl

I ran into a sitation that triggered this failure. I have version 5.0.0 installed, so it was confusing to see a message telling me my version was lower than 0.2.1.
Error message clarification.
I received the following output from a build:
```
File "/private/var/tmp/_bazel_jdob/300f9ff46946083ee2e5c32c9a7995b7/external/rules_python/third_party/github.com/bazelbuild/bazel-skyli
b/lib/versions.bzl", line 92, column 17, in _check_bazel_version
fail("Current Bazel version is lower than 0.2.1; expected at least {}".format(
Error in fail: Current Bazel version is lower than 0.2.1; expected at least 4.0.0
```
Running Bazel shows I have a higher version than 0.2.1:
```
$ bazel …
```

Made version failure message better reflect the issue

---

README.md
docs/python.md
python/BUILD
python/defs.bzl
tests/load_from_macro/BUILD

This PR introduces the current_py_toolchain rule, exposing the
PYTHON2 and PYTHON3 "make" variables in bazel rules, analagous to
@bazel_tools//tools/cpp:current_cc_toolchain.
This is useful when building 3rd party libraries which require python via rules_foreign_cc.
See
https://docs.bazel.build/versions/main/be/make-variables.html#custom_variables
Bazel rules can refer to the python interpreter via "Make" Variables.

Provide current_py_toolchain

---

python/repositories.bzl

Using Bazel CLI option [incompatible_disallow_empty_glob](https://bazel.build/reference/command-line-reference#flag--incompatible_disallow_empty_glob) is not compatible with using a hermetic interpreter offered by rules_python.
It causes the error (exemplary for a Linux host):
```
ERROR: Traceback (most recent call last):
File "<path_to_bazel_out>/external/python3_10_x86_64-unknown-linux-gnu/BUILD.bazel", line 9, column 16, in <toplevel>
srcs = glob(
Error in glob: glob pattern '*.exe' didn't match anything, but allow_empty is set to False (the default value of allow_empty can be set with --incompatible_disallow_empty_glob).
```
A [single …

Make hermetic interpreters compatible to disallow_empty_glob

---

gazelle/README.md
gazelle/generate.go

filepath.WalkDir lets us avoid calling stat on each file.
N/A
Avoid a stat call for each file and slightly cleaner error handling

[gazelle] Use filepath.WalkDir instead of filepath.Walk

---

python/repositories.bzl

Build artifacts by `bazel build` with the `--build_python_zip` option are unnecessary big. The size of the artifacts is at least 90MB (e.g., a zipped python binary which just prints "hello, world"). This is not great when build artifacts are included to docker images. The cause of this size issue is that the hermetic Python toolchain include the static libraries of the Python toolchain and tests for the standard libraries even though majority of users of rules_python don't need them. These files occupy 47MB (52% of an artifact of size 90MB).
`WORKSPACE`:
```starlark
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
name = …
```

Exclude static libraries and tests to reduce zipped Python executables

---

python/repositories.bzl

We have seen folks excluding the `.pyc` files due to cache misses. See:
- https://github.com/bazelbuild/rules_python/pull/713
- https://github.com/bazelbuild/rules_python/pull/748
This PR adds a check under Linux and macOS that fails if running as root. For those who want to still ignore it, I added a new attribute.

fix: fail if the user is root

---

MODULE.bazel

Under bazel 5 this unused entry is okay, but with Bazel 6 you get an error
ERROR: Analysis of target '//:bzlmod' failed; build aborted: module extension "pip_install" from "@@rules_python~override//python:extensions.bzl" does not generate repository "pypi__pkginfo", yet it is imported as "pypi__pkginfo" in the usage at rules_python@_/MODULE.bazel:7:28
This was detected on BCR which runs against latest bazel, so I had to
make this change there already:
https://github.com/bazelbuild/bazel-central-registry/commit/6e1bf0e63008fff663da70ae96cf1425c568fa31#diff-d133485c86e1650c9910643274be2051f2c714042c59de22b4c3fd6e546bd93c

chore: remove pkginfo from bzlmod file

---

python/repositories.bzl

#758 reduced the size of artifacts built by the `bazel build` command with the `--build_python_zip` option, but there is still room for improvement. The size of the artifacts is at least 43MB (e.g., a zipped python binary which just prints "hello, world"). This is still not great when build artifacts are included to docker images. It turned out that the --build_python_zip option includes the two identical shared libraries (not symlinks), `libpython{python_version}.so` and `libpython{python_version}.so.1.0` into the zip files, but rules_python doesn't use `libpython{python_version}.so`.
`libpython{python_version}.so` occupies 16MB (37% of the total size of the artifact …

Exclude unused libpython{python_version}.so to reduce the size of zipped Python executables

---

python/versions.bzl

Updates the Python toolchain versions for 3.8.13, 3.9, and 3.10. Adds 3.9.13 and 3.10.6. The `install_only` archives of 3.8.13, 3.9.13, and 3.10.6 are smaller than before, because the static libpython libraries and tests for the stdlib itself are removed from the archives. This is essentially equivalent to what we do in #758, but now in the python-build-standalone side. We can remove our own filtering introduced in #758 once the support of earlier versions than 3.8.13, 3.9.13, and 3.10.6 is dropped.
For details of the toolchain side changes, see https://github.com/indygreg/python-build-standalone/releases/tag/20220802.
For 3.9, 3.9.12 is installed.
For 3.10, 3.10.4 is …

Update Python minor toolchain versions to allow smaller Python binaries

---

python/pip_install/repositories.bzl
python/pip_install/requirements.bzl

You cannot run the `compile_pip_requirements.update` target with a Python interpreter at a version < 3.8 - it will fail on importing `importlib_metadata` in the `build` package
You can run the `compile_pip_requirements.update` target with a Python interpreter at a version < 3.8 
I could see a scenario where part of the setup instructions involve telling the user to produce a lockfile for `pip-compile` from their local env, but it's probably just easier to package up all the reqs for any version.

Added importlib + reqs to pip-compile for python < 3.8

---

gazelle/manifest/defs.bzl

Provides a somewhat useful target as the "default" target for the macro, that is, the target that is the actual name of the macro. 
Having this is incredibly useful when attempting to do static analysis of BUILD files to determine targets, but where those targets are macros and don't expand to a target with the given name it causes issues with any further bazel processing of that target (as it doesn't exist!). 
While there are workarounds, it seems sane and good practice to simply provide a target with that name.

feat(gazelle_python_manifest): provide a target with the given name

---

gazelle/modules_mapping/generator.py

Wheels can contain their package within the `.data` directory, inside the `purelib` or `platlib` directories, which is then unpacked into the correct `site-packages` folder.
Previously these directories were ignored, but this causes issues with packages such as `semgrep` that don't set `Root-Is-Purelib: true` and instead have the `purelib` directory under the `.data` package.
This is the same as setting `Root-Is-Purelib: true` and having all the files at the root, so I'm unsure of the reasons to do it this way :shrug:
This results in the package being missing from the gazelle_python manifest files, and therefore causing issues with resolving dependencies.

fix(gazelle): handle purelib and platlib packages that don't set 'Root-Is-Purelib: true'

---

gazelle/manifest/defs.bzl

Fixes https://github.com/bazelbuild/rules_python/issues/802
I think this doesn't apply here, but LMK if there's something you want me to do.
Ditto
Manifest test timeout is not set. Whatever it defaults to is too long, at least for my manifests, and bazel complains.
Issue Number: https://github.com/bazelbuild/rules_python/issues/802
manifest test timeout is set to "short"
In theory if someone's manifest test takes too long to run, this could break them.
In practice this seems very unlikely.
LMK if you want me to make this an option instead.

specify timeout for gazelle manifest test

---

python/pip_install/pip_compile.py

Linux's requirement file is not found by pip_compile select_golden_requirements_file function. Common requirement.txt is used as default causing test to fail. 
By fixing select_golden_requirements_file arguments order at invocation, the configuration file is found.

fix pip_compile pip_compile select_golden_requirements_file invocation arguments

---

BUILD
version.bzl

Asserts that the expected Bazel version is in sync between `.bazelversion` and `version.bzl`.

fix: assert expected bazel version

---

gazelle/README.md

I had a client yesterday who tripped on this since their requirements were in some unrelated location, so Gazelle wasn't finding the modules manifest.

doc: clarify location of gazelle_python.yaml

---

.bazelci/presubmit.yml

I noticed that Ubuntu 18.04 on CI is running Python 3.6 in the host, which is EOL already. Since Ubuntu 22.04 is the current LTS, I judged that using the previous LTS (20.04 - still under support) is the best option.

bump: ubuntu version on CI

---

CONTRIBUTING.md

I ran into the problem where I did not have python installed, and I did not want to install it.  Hey I use bazel! When you do not have python installed you cannot use pre-submit to configure running buildifier.  It took me forever to figure out how to run it, so I included the command in the CONTRIBUTING.md.

Updating docs

---

.github/CODEOWNERS

* Remove brandjon, lberki, thundergolfer; they're no longer active in the repo.
* Add rickeylev as replacement owner.

Remove defunct owners, add new owners

---

.github/CODEOWNERS

In chat, @hrfuller said he was willing to be set as a code owner of it.

Add hrfuller as code owner for pip_parse

---

README.md

`pip_install` is deprecated and will be removed in a future release. The example has already been updated to `pip_parse`, but the caption has not been updated yet.

Update `pip_install` to `pip_parse` in README.md

---

python/pip_install/repositories.bzl

We install some pip packages to bootstrap the pip_install/pip_parse rules, and these were allowing .pyc files as data deps. In some clients I observe that pip install is creating these with non-determinism and busting the python action caches. We already had a correct solution for user-installed packages, so we just need to include those entries for the built-ins.

fix(determinism): copy two missing entries from data_excludes

---

gazelle/generate.go
gazelle/target.go
gazelle/testdata/simple_test_with_conftest/BUILD.in
gazelle/testdata/simple_test_with_conftest/BUILD.out
gazelle/testdata/simple_test_with_conftest/README.md
gazelle/testdata/simple_test_with_conftest/WORKSPACE
gazelle/testdata/simple_test_with_conftest/__init__.py
gazelle/testdata/simple_test_with_conftest/__test__.py
gazelle/testdata/simple_test_with_conftest/foo.py
gazelle/testdata/simple_test_with_conftest/test.yaml

`conftest.py` is a special file that should be used only with tests, so we create a `py_library` for it and add it as a dependency to `py_test`. By special-casing it, we take advantage of all the dependency resolution Gazelle offers. In contrast, when adding it to a `py_test` with `# keep` and excluding it from Gazelle, we also have to manage its dependencies manually.

fix: make conftest.py special with gazelle

---

CONTRIBUTING.md

This is based on my experience getting stated myself, where I have only minimal experience with GitHub, git, and many of the tools.

Document how to get started working on rules_python

---

python/pip_install/extract_wheels/bazel.py

Issue Number: #895 
`rpyc` dependency generates separate `py_binary` rules.

fix: #895 append _py if ending with .py

---

python/config_settings/transition.bzl

After we introduced multi-toolchain support, the release failed because `RunEnvironmentInfo` is only available on Bazel 5.3.0+ and there was a bug in how we checked for the existence of this provider. Apparently, there's no way to check for this provider, so I reverted to the deprecated `testing.TestEnvironment`. Once we are okay with not supporting Bazel < 5.3.0, we can move to `RunEnvironmentInfo`.

fix: missing RunEnvironmentInfo

---

BUILD
examples/BUILD
gazelle/BUILD.bazel
gazelle/manifest/BUILD.bazel
gazelle/manifest/generate/BUILD.bazel
gazelle/manifest/test/BUILD.bazel
gazelle/modules_mapping/BUILD.bazel
gazelle/pythonconfig/BUILD.bazel

Fixes #912
Currently the build_file_generation example is not executed when running `bazel test //...`.
This PR adds the `filegroup` targets for the `gazelle` subtree and allows us to run the `gazelle` test on Linux locally. I am creating this PR in order to see if it fails on other platforms.

Add gazelle distribution and enable build_file_generation test

---

.github/workflows/ci.bazelrc
.github/workflows/release.yml

The tags that are released already have a more comprehensive test run attached to them, so we don't need to spend a lot of time re-testing on GitHub Actions during release.

fix: don't test on release

---

gazelle/parser.go
gazelle/testdata/ignored_invalid_imported_module/__init__.py
gazelle/testdata/invalid_annotation/README.md
gazelle/testdata/invalid_annotation/WORKSPACE
gazelle/testdata/invalid_annotation/__init__.py
gazelle/testdata/invalid_annotation/test.yaml

If `# gazelle:ignore` line exists  gazelle panics. 
commit hash  6434e34fb0b7f527d3f4451b702086a2d396b021 (added new test line)
//gazelle:gazelle_test failes 
```go
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //gazelle:gazelle_test
-----------------------------------------------------------------------------
--- FAIL: TestGazelleBinary (12.00s)
--- FAIL: TestGazelleBinary/ignored_invalid_imported_module (0.38s)
python_test.go:188: expected gazelle exit code: 0
got: 2
python_test.go:188: expected gazelle stderr: 
got: panic: runtime error: index out of range [1] with length 1
goroutine 1 [running]:
github.com/bazelbuild/rules_python/gazelle.(*comment).asAnnotation(0x …
```

fix: gazelle panics when "# gazelle:ignore" doesn't have a value

---

python/pip_install/extract_wheels/wheel.py

Disables bytecode optimization when wheels are installed.
I've noticed some occasional failures in CI, which involve `__pycache__`. I believe this could be coming from bytecode compilation of third-party wheels. I think disabling this behaviour until there is a better understanding of the desired behaviour is a good idea.
The `installer` library is able to compile bytecode upon installation. https://buildkite.com/bazel/rules-python-python/builds/3864#01854d9d-9c71-4587-a8f4-86e6718c38e7 By default, level 0 is used (generates .pyc).

Disable bytecode optimization during wheel installation

---

python/config_settings/transition.bzl

This was only introduced very
recently (https://github.com/bazelbuild/bazel/pull/14849/commits/98b064bddc80da95e46df7cd2ec7073108e62946#diff-be59c30c90e1bc4760029739db3469d256d7784e7e7335bf3180fde39b0bcd5b) and isn’t available in most Bazel versions.
When building a `py_binary` target that comes from a hermetic toolchain (as described in https://github.com/bazelbuild/rules_python#toolchain-registration) under e.g. Bazel 5.1, the build will fail with an error such as
```
ERROR: […]/BUILD:51:10: in _transition_py_binary rule //[…]: 
Traceback (most recent call last):
File "[…]/external/rules_python/python/config_settings/transition.bzl", line 65, column 32, in _transition_py_impl …
```

Don’t use keyword argument for TestEnvironment.

---

examples/bzlmod/BUILD.bazel
examples/bzlmod/requirements.in
examples/bzlmod/requirements_lock.txt
examples/bzlmod/requirements_windows.txt
python/pip_install/pip_repository.bzl

This fixes a issue with the repository generation function where it was missing a _clean_pkg_name() for the second reference to the requirement name.
Fixes #952
Issue Number: #952 
`requirement("dependency")` didn't work if the dependency had any number of hyphens in its name (for example `requirement("google-cloud-storage")`  did not work in a BUILD.bazel file.
The error encountered was, for example:
```
bazel:106:6: no such package '@[unknown repo 'pip_typing-extensions' requested from 
@rules_python~0.16.1~pip~pip]//': The repository '@[unknown repo 'pip_python-dateutil' requested from 
@rules_python~0.16.1~pip~pip]' could not be resolved: No repository visible 
as …
```

Fix hyphen in requirement didn't work with bzlmod (#952)

---

gazelle/manifest/manifest_test.go
gazelle/python_test.go

We are currently using `ioutil.ReadFile` in `gazelle` tests even though it has been deprecated since `1.16` as per [official docs](https://golang.google.cn/pkg/io/ioutil/#ReadFile).
Use `os.ReadFile` instead as the package suggests.

Use 'os' instead of 'ioutil' in gazelle tests

---

python/runfiles/runfiles.py
tests/runfiles/BUILD.bazel
tests/runfiles/runfiles_test.py

rules_python's runfiles library is affected by https://github.com/bazelbuild/bazel/issues/14336, which has been fixed upstream.
rules_python's version of the runfiles library contains https://github.com/bazelbuild/bazel/commit/486d153d1981c3f47129f675de20189667667fa7
Also adds the tests contained in the Bazel repo.

Update runfiles lib

---

MODULE.bazel
README.md
internal_deps.bzl
internal_setup.bzl
python/private/BUILD.bazel
python/private/proto/BUILD
python/private/proto/py_proto_library.bzl
python/proto.bzl

`py_proto_library` was tested manually on Bazel repository using Bazel 6.0.0 with and without using bzlmod.
Extend README.md to mention also `py_proto_library`.
With bzlmod `py_proto_library` just works. Users without bzlmod, need to import `rules_proto` and `protobuf` repositories into their `WORKSPACE` file. 
`py_proto_library` is compatible with Bazel `>=5.4.0` and `>=6.0.0`.

Implement py_proto_library

---

python/runfiles/runfiles.py

Docs reference `bazel_tools` and import instructions fail with Bzlmod.
The canonical location for the runfiles library going forward will be the rules_python repo, so users should load from it. Since repository names are essentially dynamic with Bzlmod, they should not be used in import statements.

runfiles: Fix usage instructions

---

python/pip_install/pip_repository.bzl

When `rctx.which` can not find a program for the specified name, it returns `None`.
We should not override the original `python_interpreter` in this case, otherwise we'll see a misleading error message like ``Error in fail: python interpreter `None` not found in PATH``

Fix misleading error message

---

examples/bzlmod/MODULE.bazel
examples/bzlmod/other_module/other_module/pkg/lib.py
examples/bzlmod/runfiles/BUILD.bazel
examples/bzlmod/runfiles/runfiles_test.py
python/runfiles/runfiles.py
tests/runfiles/runfiles_test.py

The Python runfiles library fails to find runfiles specified with apparent repository names when Bzlmod is enabled.
When a repo mapping manifest is available in runfiles, it is parsed and used to map apparent repository names to canonical ones in paths passed to Rlocation. The current repository, which is required to know which part of the mapping to apply, is either determined using `CurrentRepository` or can be passed in explicitly.
With this commit, runfiles lookups should succeed with Bzlmod without code changes.

runfiles: Apply repo mapping to Rlocation path

---

.github/workflows/workspace_snippet.sh
MODULE.bazel
examples/multi_python_versions/WORKSPACE
examples/pip_install/WORKSPACE
examples/pip_parse/WORKSPACE
examples/pip_parse_vendored/WORKSPACE
examples/pip_repository_annotations/WORKSPACE
python/repositories.bzl
tests/pip_repository_entry_points/WORKSPACE

#846 introduced this dependency, and solved the broken examples by installing the dependency only for our own code. However, this was an unintentional breaking change for users, who may not have had bazel_skylib installed in their workspace.
(Note for reviewers, any change to the examples is an indication that it will be breaking to users, as it represents changes required for using the rules)
This effectively reverts #370. At that time we didn't want any dependencies, because managing them under Bazel's WORKSPACE semantics is so difficult for users. Now that bzlmod has reached General Availability in Bazel 6, such dependencies can be managed more easily.
This also allows us to introduce bzl_library calls in our BUILD files, making it less brittle to ensure that users can generate docs …

fix(deps): declare our dependency on bazel_skylib

---

.github/workflows/release.yml
python/runfiles/BUILD.bazel
python/runfiles/README.md
python/runfiles/__init__.py
python/runfiles/runfiles.py
tests/runfiles/runfiles_wheel_integration_test.sh

Wire it up to GH actions so it is published for each release.
Tested locally with:
```
$ bazel build python/runfiles:wheel --embed_label=1.0.2 --stamp
$ PYTHONPATH=bazel-bin/python/runfiles/bazel_runfiles-_BUILD_EMBED_LABEL_-py3-none-any.whl python
>>> import runfiles
>>> runfiles.Create()
```
Note, I would have liked to call the package bazel-runfiles, but this isn't possible without either refactoring the paths in this repo, or doing some fancy starlark to copy files around to create a folder that we turn into the wheel. There is no project https://pypi.org/project/runfiles though there is a https://pypi.org/project/runfile
We could try harder to get the name we prefer.

chore: publish a runfiles library as a wheel

---

python/repositories.bzl
python/versions.bzl

Allows patching the unpacked interpreter, supports supplying a list of patches per platform.
(`07-unpacked_interpreter_patches.patch`)

feat: allow patching the interpreter fetched via toolchains

---

gazelle/std_modules.go
gazelle/std_modules.py

Fixes https://github.com/bazelbuild/rules_python/issues/1006
Also, set PYTHONNOUSERSITE so that the script doesn't even look in site packages when checking modules.
Fix typo with capitilize.
Issue Number: #1006 
```echo "pygame" | bazel run //gazelle:std_modules
false
```
No extraneous output.

Redirect stdout when checking imports.

---

gazelle/BUILD.bazel

Gazelle extension uses [std_modules](https://github.com/bazelbuild/rules_python/blob/1487a0c416be8bb5d1033b3815fb662527c99197/gazelle/std_modules.go#L29) and [parser](https://github.com/bazelbuild/rules_python/blob/1487a0c416be8bb5d1033b3815fb662527c99197/gazelle/parser.go#L28) without declaring them as runtime dependencies, causing errors like: 
```
2023/01/18 16:08:23 failed to initialize std_modules: Runfile gazelle/std_modules: could not locate file
```
Adding them to the `data` attribute of Gazelle extension

Add runtime dependencies to gazelle extension

---

python/repositories.bzl

Currently `bazel` will error out if one does not specify a `strip_prefix` in a custom `tool_versions` dict. But if a user retrieves interpreter archives from another source, the `strip_prefix` might not be necessary.
A workaround is `'strip_prefix': ''`.
Omitting the `strip_prefix` in `tool_versions` is allowed.

fix: allow omitting the `strip_prefix` in `tool_versions`

---

python/repositories.bzl

A user might use `python_headers` to build an extension module that does not itself pull in the python shared library. On Windows, this needs to expose the `*.lib` interface file to compile correctly.
Currently a user on Windows can not compile a native extension module and build against `python_headers`.
It is fixed.

fix: windows `*.lib` interface in `python_headers`

---

python/repositories.bzl

After the first time the python_repository is used, files are created in
`__pycache__` directories. These invalidate the configured target for
the python_repository target, and cause spurious rebuilds.
Here's an example of the set of pycache files I've seen in one
repository.
```
lib/python3.8/distutils/__pycache__/__init__.cpython-38.pyc
lib/python3.8/distutils/__pycache__/archive_util.cpython-38.pyc
lib/python3.8/distutils/__pycache__/cmd.cpython-38.pyc
lib/python3.8/distutils/__pycache__/config.cpython-38.pyc
lib/python3.8/distutils/__pycache__/core.cpython-38.pyc
lib/python3.8/distutils/__pycache__/debug.cpython-38.pyc
lib/python3.8/distutils/__pycache__/dep_util.cpython-38.pyc
lib/python3.8/distutils/__pycache__/dir_util.cpython-38.pyc …
```

python_repository: Exclude pycache files

---

python/pip_install/private/test/requirements_parser_tests.bzl
python/pip_install/requirements_parser.bzl

Bazel build fails when requirements.txt contains `--extra-index-url https://foo.bar/` with the following error
```
Usage:   
/home/tgeng/.pyenv/versions/3.10.7/bin/python3 -m pip wheel [options] <requirement specifier> ...
/home/tgeng/.pyenv/versions/3.10.7/bin/python3 -m pip wheel [options] -r <requirements file> ...
/home/tgeng/.pyenv/versions/3.10.7/bin/python3 -m pip wheel [options] [-e] <vcs project url> ...
/home/tgeng/.pyenv/versions/3.10.7/bin/python3 -m pip wheel [options] [-e] <local project path> ...
/home/tgeng/.pyenv/versions/3.10.7/bin/python3 -m pip wheel [options] <archive url/path> ...
no such option: --extra-index-url https://foo.bar/
Traceback (most recent call …
```

Fix requirement parser

---

docs/packaging.md
python/packaging.bzl
python/private/py_wheel.bzl

Pure refactoring that should have no user-visible effect.
This gives us the place to insert other targets produced by it, such as a publishing target.
Note: due to stardoc limitation, we have to expose two different symbols to the user in the docs.
I've linked them together and not tried to "hide" the fact that there's both a macro and a rule.
This way we don't have to duplicate all the docs for the attributes into the single docstring of the macro,
and declare all the matching parameters and remember to pass them through to the rule.
See docs preview: https://github.com/bazelbuild/rules_python/blob/bc38c7e28a5684fecd0d7dd38fffc00b763f6ad2/docs/packaging.md#py_wheel
Part of #99

refactor: py_wheel now a macro

---

python/repositories.bzl

Fixes the logspew I introduced in #1004
Before:
```
DEBUG: Rule 'python3_8_x86_64-unknown-linux-gnu' indicated that a canonical reproducible form can be obtained by dropping arguments ["patches"]
DEBUG: Repository python3_8_x86_64-unknown-linux-gnu instantiated at:
/cache/repo/WORKSPACE:344:27: in <toplevel>
/cache/bazel/6fadd30f776596320f945376fa05bc65/external/rules_python/python/repositories.bzl:300:26: in python_register_toolchains
Repository rule python_repository defined at:
/cache/bazel/6fadd30f776596320f945376fa05bc65/external/rules_python/python/repositories.bzl:204:36: in <toplevel>
```
After:
```
```

fix: ensure 'patches' attr is included for the canonical representation of the toolchain

---

.github/workflows/release.yml
docs/packaging.md
python/packaging.bzl
python/private/py_wheel.bzl
python/runfiles/BUILD.bazel

Fixes #741 
Also unblocks the stuck 0.17.0 release, which publishes a wheel for the first time.
This is a less ambitious attempt to solve our release problem than introducing `twine` in #1015

feat: produce publishable distribution archives

---

python/versions.bzl

> could not find any to adapt / not sure how/where to introduce them
> did not find relevant docs
`python_register_toolchains()` allows to pass in `tool_version`. But the given `url` are appended to the `base_url` even if they are already an absolute `url`. 
With the new behavior, a user can load `TOOL_VERSIONS` from `@rules_python` and extend the dictionary with custom versions  pulled from custom locations while still using the defaults `@rules_python` provides. More importantly, this allows to pull artifacts for different python versions from different hosts.

feat: allow absolute urls in `tool_versions`

---

.github/workflows/release.yml

our 0.17 release is stuck on this step.
Partially reverts #995
We can try again after #1021 lands

chore: revert publish wheel on releases

---

gazelle/go.mod
gazelle/go.sum
gazelle/python/BUILD.bazel
gazelle/python/generate.go

Gazelle plugin generates a UUID for each `py_library` target for `py_binary` and `py_test` in the same package to refer to. However, creating another identifier such as UUID is not necessary because Bazel already has id for each target, which is its label.
Furthermore, in some large monorepos where it's too slow for Gazelle to index the whole repo, we turn off the indexing with `bazel run //:gazelle -- -index=false` and rely on [CrossResolver](https://github.com/bazelbuild/bazel-gazelle/blob/77e0f34c43a9f5e95f6af93485a4bd83942ed3c6/resolve/index.go#L66) to resolve dependencies based on paths conventions. The UUID makes it impossible to resolve dependencies without indexing the whole …

Using label as id for py targets

---

gazelle/python/generate.go
gazelle/python/target.go
gazelle/python/testdata/subdir_sources/one/two/README.md
gazelle/python/testdata/subdir_sources/one/two/__init__.py
gazelle/python/testdata/with_third_party_requirements/BUILD.out
gazelle/python/testdata/with_third_party_requirements/README.md

When a Python module imports another one in the same package, it can use the file name without the directory names. When Gazelle generate the targets, they are either in the same target or in sibling targets already depending on each other. However, Gazelle still tries to resolve them, even though no dependency resolution is needed
Identify imports in sibling modules and ignore them.

Handling imports from sibling modules

---

docs/pip.md
python/pip_install/requirements.bzl

I was hitting a problem when running pip-compile on a requirements.in file and being able to pass extra dependencies solved my problem, so this may be helpful to everyone.

feat: allow extra dependencies to be passed to pip-compile

---

python/pip_install/tools/lock_file_generator/lock_file_generator.py

The annotations are written into the `repo` workspace (as in, where the `requirements.bzl` file is) rather than where the packages are. 
These may well be the same if not setting `repo_prefix` (hence that `rstrip`), but if the user has set `repo_prefix`, then we no longer want to read annotations from the package path, but rather the repo workspace, which is just `repo`.
(11-repo_prefix_on_annotations.patch)

fix: use 'repo' as prefix when constructing annotations label

---

gazelle/python/generate.go

@f0rmiga I think this is a better fix for the bug you ran into. It would prevent similar bugs from happening when importing other Python modules (e.g., `__init__.py` etc) in the same package.

Collect all py file names in the same package

---

python/pip_install/pip_repository.bzl

Bugfix
When using a layer of indirection to refer to a hermetic toolchain, python deps that compile local code fail to properly set the path to the local XCode install, causing compilation to fail (eg. when compiling `lxml`'s deps)
The CPP_FLAGS are set properly, and `lxml` will install from a repository rule cleanly
No
I'm not entirely sure how to reproduce this with a test in this repo. It only showed up when we had some particularly gnarly setup with a repo at work.

Pass cpp flags through in all cases to repository rule compilations

---

python/pip_install/tools/dependency_resolver/dependency_resolver.py
python/private/BUILD.bazel
python/private/coverage.patch
python/private/coverage_deps.bzl

When we run tests for the locked requirements files, pip-compile will import pip internally, and eventually, it tries to import `html.entries`, which is part of the standard library. Since the `coverage` package provides an `html.py` file, it ends up being picked up by pip if the `coverage` package is early on the `sys.path`.
This patch presents a generic fix for the problem with coverage by moving its own directory to the end of `sys.path`.

fix: move coverage pkg to end of sys.path to avoid collisions

---

gazelle/python/configure.go
gazelle/python/generate.go
gazelle/python/python_test.go
gazelle/python/testdata/monorepo/a/BUILD.in
gazelle/python/testdata/monorepo/a/BUILD.out
gazelle/python/testdata/monorepo/a/README.md

`gazelle:exclude` patterns in one directory may cause Python files getting excluded in a totally unrelated directory
* making sure that the exclusions are limited to the directories that they are targeting
* also improve the test a bit the error message would point to the actual lines failing

Making exclusions more strict

---

python/tests/toolchains/run_acceptance_test.py.tmpl

The latest Bazel build continous integration testing pipeline sets several flags and environment variables that end up interfering with each other:
* `--sandbox_tmpfs_path=/tmp`
* `--test_env=USE_BAZEL_VERSION`
* `USE_BAZEL_VERSION=/tmp/<something>`
* And Bazelisk is used to run Bazel
What happens is `USE_BAZEL_VERSION` points to Bazel in /tmp, but then the `--sandbox_tmpfs_path` flag prevents it from being readable. Later, when a test wants to run Bazel, Bazelisk is invoked. It is able to see that it should use a custom Bazel binary because of `--test_env`, but then can't read the file because of `--sandbox_tmpfs_path`, so then fails.
To fix, make the test runner that will run `bazel` unset `USE_BAZEL_VERSION` so Bazelisk doesn't try to use it.
This also exposed an issue with Bazelisk …

Make toolchain acceptance tests work with latest Bazel build CI pipeline

---

python/repositories.bzl

Unreleased Bazel versions don't set `native.bazel_version`, which was causing the version detection logic to error. To fix, just check it's non-empty. Treat a missing version as a sufficient version.

Allow building with unreleased Bazel versions.

---

docs/packaging.md
python/packaging.bzl
python/runfiles/BUILD.bazel

Tested manually with:
```
$ cd examples/wheel
$ bazel run --stamp --embed_label=1.2.3 -- :customized.publish --repository testpypi
```
The result was published here: https://test.pypi.org/project/example-customized/1.2.3/

feat: wheel publishing

---

docs/BUILD.bazel
examples/wheel/BUILD.bazel
python/packaging.bzl
python/private/BUILD.bazel
python/private/util.bzl

The `.dist` target depends on the wheel, so it must copy the `testonly` setting as well as some others.
* Also adds a utility function to do this, since the multi-version rules also do this copying.
Fixes #1057

fix: Propagate testonly et al for wheel `.dist` targets

---

docs/coverage.md

This is to replace the docs on bazel.build that talk about coverage support for Python.

Add some docs about how to configure coverage.

---

python/BUILD.bazel

This makes modifying it with buildozer easier. When the empty line is present, Buildozer gets confused and adds loads() before the intended doc string.

Remove empty line between copyright and build file docstring.

---

BUILD.bazel
python/private/BUILD.bazel
tools/BUILD.bazel

The `# License type` comments are no longer required. Removing it makes it easier to import the source into Google.

cleanup: Remove license type comment; they're no longer required

---

.bcr/source.template.json

This is to prevent the issue where the checksum of the auto-generated archive files may change due to GitHub internal changes.
Fixes #1072

fix: Use GitHub download URL for BCR URL instead of archive URL.

---

.pre-commit-config.yaml
CONTRIBUTING.md

Having a standard format for commit messages makes it easier to understand what general behaviors and functionality are being affected. This makes it easier to easier to generate changelog information for releases and quickly skim PRs.
The default commitizen style is used, which is Conventional Commits. Docs are updated to give a brief description of the format and common types.
This isn't enforced using pre-commit hooks because PRs squash commits and use the PR description for the merged commit message, which makes linting intermediate commits rather moot.

docs: doc that the Conventional Commit style should be used for merged commits and PRs

---

.github/workflows/create_archive_and_notes.sh
README.md
examples/build_file_generation/WORKSPACE
gazelle/README.md

This was pointed out in a thread on bazel-discuss@googlegroups.com

chore: fix some lingering GH archive URLs

---

docs/pip.md
python/pip_install/requirements.bzl

Currently we render:
```
validate with bazel test &lt;name&gt;_test
update with bazel run &lt;name&gt;.update
```

chore: fix syntax that stardoc misunderstands as HTML

---

gazelle/pythonconfig/BUILD.bazel
gazelle/pythonconfig/pythonconfig.go
gazelle/pythonconfig/pythonconfig_test.go

Some packages (ex: [github3.py](https://pypi.org/project/github3.py/)) have a dot (`.`) character in their name.
`pip_parse` will replace the dot (`.`) with an underscore (`_`) when generating the target name.
`gazelle` however keeps the the dot (`.`) in the name when generating the target dependency name.
This discrepancy means that after a gazelle pass, the repo does not build.
ex:
```
ERROR: <snip>/BUILD.bazel:3:11: no such package
'@python_deps_github3.py//': The repository '@python_deps_github3.py'
could not be resolved: Repository '@python_deps_github3.py' is not
defined and referenced by '<snip>'
```
This PR brings `gazelle` dependency target name generation in line with `pip_parse`.
What kind of change does this PR …

fix: update gazelle to properly handle dot in package name.

---

python/BUILD.bazel
python/private/BUILD.bazel

This is so that the transitive dependencies of defs.bzl can be easily found and validated; some Google internal tooling does this validation.
The old comment indicated bzl_library wasn't used to avoid a dependency on skylib, however, we've since added a dependency on skylib.

feat: add bzl_library for defs.bzl and its dependencies

---

python/extensions.bzl

PR Instructions/requirements
Exposes one of the many args that used to be exposed via pre-module functions.
----
Q: Was there a reason that a limited argument set was made available with the module api?

fix: docs for ignore_root_user_error at the module level

---

examples/wheel/BUILD.bazel
examples/wheel/private/wheel_utils.bzl
python/private/py_wheel.bzl

As the title states - expands make variable substitution to abi and python tags.
See the example for usage.
NB: It allows variables to be passed in via toolchains (in which case it appears under `ctx.var`) or via `deps` (in which case it appears under `dep[].variables`)

feat: make variable substitution for py_wheel abi, python_tag args

---

python/BUILD.bazel
python/private/proto/BUILD

This is mostly so Google internal tooling can find the complete deps, but also as a best practice for consumption by other rules and tools.

feat: add bzl_library for proto.bzl

---

python/private/proto/BUILD

The license comments aren't necessary anymore.

cleanup: Remove license comment in proto build file

---

python/private/proto/BUILD

This is to prevent accidentally leaking targets that shouldn't be accessible. The `:python_toolchain` target is public because it's an implicit dependency of `py_proto_library`.

fix: restrict proto package visibility to private

---

docs/BUILD.bazel
python/BUILD.bazel
python/current_py_toolchain.bzl
python/defs.bzl
python/private/BUILD.bazel
python/py_binary.bzl
python/py_import.bzl
python/py_info.bzl
python/py_library.bzl
python/py_runtime.bzl
python/py_runtime_info.bzl
python/py_runtime_pair.bzl
python/py_test.bzl
tests/BUILD.bazel

This is basically a performance optimization. Bazel can only see that a bzl file changed, not the particular contents. This means that any downstream bzl file loading it is invalidated, even if it doesn't load any of the affected code. As an example, if a package only loads `py_library.bzl`, then changing `py_test.bzl` doesn't need to invalidate all libraries.
* Also removes some more extraneous license comments

feat: bzl file per rule/provider

---

tests/BUILD.bazel

cleanup: fix typo: libraries, not libaries

---

python/BUILD.bazel
python/py_cc_link_params_info.bzl
tests/BUILD.bazel

This provides a public entry point for loading the underlying `PyCcLinkParamsProvider` provider that is built into Bazel. This provider isn't yet usable from Bazel, but adding a loadable way for it to migrate off the built-in rules is the first step.

feat: add public entry point for PyCcLinkParamsInfo

---

gazelle/python/parse.py

If the import scanner stumbles across a file with a syntax error, gazelle dies with a message that fails to specify what file it choked on.  Fix that.
Before: 
```
File "<unknown>", line 28
class FilesystemDatasetProvider:
IndentationError: expected an indented block
"""
```
After:
```
File "libs/remote/python/filesystem_dataset.py", line 28
class FilesystemDatasetProvider:
IndentationError: expected an indented block
"""
```

fix: Include filename when parsing imports for gazelle

---

python/pip_install/repositories.bzl

Fixes https://github.com/bazelbuild/rules_python/issues/1121.

fix: bump installer to handle windows better

---

python/BUILD.bazel
python/pip_install/BUILD.bazel

We have some changes with buildifier 6.1.0, and this commit fixes two files to allow ci to pass.

build: Fixing buildifier

---

README.md
gazelle/README.md

- Updated primary README.md to include documentation for using bzlmod or a WORKSPACE file.
- Updated gazelle/README.md to include documentation for only using bzlmod and provided a link to the older docs.
- Included other general updates for the gazelle documentation.

docs: Updating documentation for bzlmod

---

.bazelci/presubmit.yml

The CI may be broken because it is using the latest version of buildifier (`6.1.0`) and the pre-commit hooks are using `6.0.0`. `6.1.0` added extra sorting, so it is now not enough to just run `pre-commit run -a buildifier` to fix the errors. I have submitted a PR to update the pre-commit hooks in https://github.com/keith/pre-commit-buildifier/pull/14 and until it is merged and a new version is tagged we should use an older version of the buildifier to ensure the build is green.

fix: use a consistent buildifier version for CI and pre-commit

---

.bazelci/presubmit.yml
.pre-commit-config.yaml

Bump the buildifier to the latest version in pre-commit and CI at the same time.
Tested by:
```
git revert 64684ae0498576ad2a09fa528fed07afa5e7307d
pre-commit run -a buildifier
```
Related to #1148 and #1151.

chore: bump buildifier to 6.1.0

---

examples/build_file_generation/WORKSPACE.bzlmod
python/pip_install/pip_repository.bzl

This apparently was not working to begin with, but the CI running the
example did not catch it because we did not have an empty `WORKSPACE.bzlmod`
file.
Tested with the CI and with a clean cache on the local laptop.

fix: correct the labels returned by all_requirements lists

---

gazelle/python/kinds.go
gazelle/python/testdata/multiple_tests/BUILD.in
gazelle/python/testdata/multiple_tests/BUILD.out
gazelle/python/testdata/multiple_tests/README.md
gazelle/python/testdata/multiple_tests/WORKSPACE
gazelle/python/testdata/multiple_tests/bar_test.py
gazelle/python/testdata/multiple_tests/foo_test.py
gazelle/python/testdata/multiple_tests/test.yaml

Since https://github.com/bazelbuild/rules_python/pull/999, gazelle can generate multiple `py_test` rules in a single package (when it finds multiple `*_test.py` or `test_*.py` files and no `__test__.py` file). In this case, adding new test files to a package with pre-existing `py_test` rules is not handled properly due to the `MatchAny` property on the `py_test` kind - it will match the existing `py_test` rule and edit it instead of adding a new test rule. This PR disables the matching so that new `py_test` rules are properly generated.

fix: gazelle correctly adds new py_test rules

---

gazelle/python/generate.go
gazelle/python/testdata/respect_kind_mapping/BUILD.in
gazelle/python/testdata/respect_kind_mapping/BUILD.out
gazelle/python/testdata/respect_kind_mapping/README.md
gazelle/python/testdata/respect_kind_mapping/WORKSPACE
gazelle/python/testdata/respect_kind_mapping/__init__.py
gazelle/python/testdata/respect_kind_mapping/__test__.py
gazelle/python/testdata/respect_kind_mapping/foo.py
gazelle/python/testdata/respect_kind_mapping/test.yaml

When using the kind `gazelle:map_kind` directive, `gazelle` will correctly generate the buildfile on the first pass (or if no target of that type / name are present). 
However, when running gazelle a second time (or if a target of the mapped kind with the same name is present), `gazelle` will error out saying that it kind create a target of the original kind because a target of mapped kind is present and has the same name. 
Ex:
Given the directive `# gazelle:map_kind py_test py_pytest_test //src/bazel/rules/python:py_pytest_test.bzl`, `gazelle` will correctly generate a `py_pytest_test` target where it would have generated a `py_test` target. 
But on a second invocation of `gazelle` (and subsequent invocations) it will error our with:
```
gazelle: ERROR: failed to generate target …
```

fix: respect kind mapping

---

gazelle/python/python_test.go

Whilst iterating on the gazelle plugin I noticed that the
tests are taking a really long time to complete (`17s` on
my Linux laptop) and running them in parallel reduces that
time to less than `5s`, which becomes fast enough for the
time being.
Summary:
- refactor: define `inputs` and `goldens` on the same line
- refactor: reduce indentation by early returns
- feat: run tests in parallel and use t.Cleanup

test: cleanup gazelle tests and run them in parallel

---

docs/coverage.md

The docs explains that for activating coverage support we use `register_coverage_tool = True` inside the rule `register_python_toolchains`. There is no such rule, the actual rule name is `python_register_toolchains`
Signed-off-by: Andrés Felipe Barco Santa <andres@engflow.com>

[docs] Fixing rule name in coverage.md docs

---

docs/BUILD.bazel

The file was removed in Bazel@HEAD in https://github.com/bazelbuild/bazel/pull/17545
This fixes failures when using rules_python with Bazel@HEAD.
Addresses: https://github.com/bazelbuild/bazel/issues/17874

fix: remove reference to @bazel_tools//tools/python/private:defs.bzl

---

tools/build_defs/python/tests/py_test/py_test_tests.bzl

This makes the test pass on Bazel built from head. The failure appears due to not forcing the test to a Mac platform, so the underlying logic in `py_test` to detect the Mac platform fails and doesn't add the ExecutionInfo with the necessary info.
Work towards bazelbuild/bazel/issues/18170

test: Set mac platform for test_mac_requires_darwin_for_execution

---

BUILD.bazel

The latest versions of Bazel have removed the `@bazel_tools//tools/python:private/defs.bzl` file, so it can no longer be referenced.
Work towards bazelbuild/bazel/issues/18170

fix: Don't reference deleted private bazel_tools bzl file

---

internal_deps.bzl

This just keeps it at a recent version, which makes errors easier to grok. rules_testing recently underwent a large refactor, so it's confusing when errors reference lines that no longer exist in recent versions.

tests: Upgrade rules_testing to 0.0.5

---

python/pip_install/pip_repository.bzl
python/pip_install/pip_repository_requirements_bzlmod.bzl.tmpl

It seems that the macros for specifying the requirements break when the
user starts using `incompatible_generate_aliases=True`. This PR fixes
this.
Testing done:
1. Modify the example:
```
$ git diff
diff --git a/examples/bzlmod/MODULE.bazel b/examples/bzlmod/MODULE.bazel
index ce91228..1750210 100644
--- a/examples/bzlmod/MODULE.bazel
+++ b/examples/bzlmod/MODULE.bazel
@@ -26,6 +26,7 @@ register_toolchains(
pip = use_extension("@rules_python//python:extensions.bzl", "pip")
pip.parse(
name = "pip",
+    incompatible_generate_aliases=True,
requirements_lock = "//:requirements_lock.txt",
requirements_windows = "//:requirements_windows.txt",
)
```
2. Run `bazel build ...` and check that it is still working.
I noticed this when working on #1189 and creating a separate PR for easier …

fix(bzlmod): correctly template repository macros for requirements, etc

---

docs/BUILD.bazel
python/private/BUILD.bazel
python/private/util.bzl
tools/build_defs/python/tests/base_tests.bzl

Starlark rules allow giving the tags as a tuple. The helper function that added the special migration tag assumed tags was always a list, resulting in an error when it tried to concatenate a list and tuple.
To fix, check if tags is a tuple and concatenate a tuple if so. The input type of the tags attribute is preserved so that a test verifying tags can be passed to the underlying rule can be implemented (this test is to verify there isn't a regression during the rewrite to Starlark).

fix: Allow passing a tuple to the `tags` attribute.

---

python/packaging.bzl

py_wheel does not propagate "visibility" attribute to the "publish" rule.  The visibility attribute on py_wheel target is not propagated to the auto-generated "publish" target. This commit adds the visibility attribute.
Closes: https://github.com/bazelbuild/rules_python/issues/1192

feat: propagate visibility attribute for py_wheel publishing

---

tools/build_defs/python/tests/py_test/py_test_tests.bzl

When a string label is passed to the `@rules_testing` analysis_test functions, the strings are evaluated within the context of @rules_testing because that is where the actual rule invocation happens. Without bzlmod, this just requires qualifying the labels with the repo name (which is what was being done) because there's just a flat global namespace of repos.
With bzlmod enabled, repo mapping happens, so rules_testing tries to resolve those repo names using its repo mapping, which doesn't work because rules_testing's mapping doesn't include every repo using it.

tests: Force analysis test labels to resolve within @rules_python context

---

tools/bazel_integration_test/update_deleted_packages.sh

This correctly handles the integration tests and examples that are a part of
the `rules_python` workspace and should not be included in the deleted packages
list.
This brings the changes made to the `.bazelrc` very close to what is in `main`,
but I would like to update this later once #1155 and #1205 are merged.
Fixes #919.

fix(update_deleted_packages.sh): wheels example should not be included in .bazelrc

---

.bazelignore

Normally, Bazel will ignore its convenience symlinks, so putting them in the .bazelignore file isn't necessary. However, when `--output_user_root` is set, which is beneficial to set when using different Bazel versions (it preserves the analysis cache between versions), the symlinks aren't ignored. Putting them in the bazelignore file fixes this.

fix: manually ignore bazel-* directories to make using custom Bazel builds easier

---

tools/bazel_integration_test/test_runner.py

Previously we would depend on the value of .bazelrc and this
change ensures that we are explicitly enable bzlmod via CLI
args. It seems that the `py_proto_library` integration tests
defined in the `//examples:BUILD.bazel` file were not running
using `bzlmod` before hand, however, they were correctly
executed in the CI.
Work towards #958.

test(bzlmod): explicitly enable bzlmod in the test harness

---

BZLMOD_SUPPORT.md
README.md

This markdown file maintains the current status of our bzlmod implementation. Created section in README and linked to the bzlmod doc.

Adding bzlmod support document

---

examples/bzlmod/test.py

Whilst it is for documentation purposes for maintainers it is also a regression
test for #1045. Also add a test to ensure that the `html` module is not
shadowed when running under `coverage`.
Fixes #1196.

test(coverage): add a test to check the sys.path under bzlmod

---

python/repositories.bzl

Fixes the incorrect debug statement when downloading the toolchain for the first
time asking users to replace "urls" with "url" in the toolchain definition which
we maintain:
```
$ bazel build ...
... indicated that a canonical reproducible form can be obtained by modifying ...
```
Even though this is seen only once by the user, it may confuse them.
Summary of changes:
- refactor(toolchain): rename a local variable url -> urls
- fix(toolchain): set url return attrs correctly

fix(toolchain): set correct return attrs to remove non-hermeticity warning

---

python/pip_install/private/test/requirements_parser_tests.bzl
python/pip_install/requirements_parser.bzl

This commit addresses issue #1194 (see issue for details).
It brings the `comment` detection of `requirements_parser.bzl` closer to the spec described here:
- https://pip.pypa.io/en/stable/reference/requirements-file-format/#comments
1. Lines that begin with `#` are comments.
2. Content after (and including) ` #` is a comment.
Prior to this commit, a dependency like this would result in invalid `pip wheel` arguments:
```
requests @ https://github.com/psf/requests/releases/download/v2.29.0/requests-2.29.0.tar.gz#sha1=3897c249b51a1a405d615a8c9cb92e5fdbf0dd49
```

fix: allow url fragments in requirements file

---

python/runfiles/BUILD.bazel

Because `--experimental_python_import_all_repositories` defaults to true, every repository's directory is added to `sys.path`, which makes `import python.runfiles` work.
However, we shouldn't rely on that behavior for a couple reasons:
* We recommend disabling it for fewer sys.path entries (even non-Python related
repos get added to the path).
* Some users _must_ disable it because the resulting PYTHONPATH is too long.
To fix, set the `imports` attribute on `//python/runfiles:runfiles` so that `import python.runfiles` works. The net result is the `rules_python` repo directory is added
to sys.path even if `--experimental_python_import_all_repositories=false`.
Fixes #1241

fix: make `import python.runfiles` work with `--experimental_python_import_all_repositories=false`

---

python/private/toolchains_repo.bzl

The generated toolchain BUILD file is confusing to read because it relies on a ternary expression in the BUILD file to set the `target_settings` attribute. This makes debugging harder because, upon first look, all the toolchains appear to have the version constraint set. It's only upon closer inspection that you can see the 1-character difference of "False" vs "True" embedded into the middle of a line amongst other similar looking lines.
Also:
* Adds a bit of validation logic for the `set_python_version_constraint` argument
because it's conceptually a boolean, but is passed as a string, so is prone to
having an incorrect value passed.
* Documents the `set_python_version_constraint` arg, since it has a particular range
of values it accepts.

cleanup: Set toolchain target_setting directly instead of via inline ternary

---

MODULE.bazel
examples/bzlmod/test.py
python/private/coverage.patch
python/private/coverage_deps.bzl

Fixes #1196.
Currently the `coverage.py` module does not work if updated to the latest
version with the following error:
```
ImportError: cannot import name 'MappingProxyType' from partially
initialized module 'types' (most likely due to a circular import)
...~pypi__coverage_cp39_x86_64-unknown-linux-gnu/coverage/types.py)
```
Where the `MappingProxyType` actually exists in Python's std lib. To fix,
modify sys.path before the first import of coverage.
Summary:
- chore(coverage): bump coverage.py to 7.2.7
- fix(coverage): patch sys.path before importing anything from coverage
- test(coverage): add extra assertions about the module names

fix(coverage): bump to latest coverage.py and fix import shadowing

---

python/versions.bzl

This is being added in order to once again be able to build envoyproxy on the `ppc64le` architecture. 
Little Endian Power support was added to release https://github.com/indygreg/python-build-standalone/releases/tag/20230507.

feat: add ppc64le releases and update to 3.10.11, 3.11.3 for python-build-standalone

---

python/pip_install/tools/wheel_installer/wheel_installer.py

[`wheel_installer` assumes that if the pip command succeeded, there must be at least one `*.whl` file](https://github.com/lpulley/rules_python/blob/fdec44120aa45d748ab804f1d019002c6949b449/python/pip_install/tools/wheel_installer/wheel_installer.py#L439), but this is not currently true when `download_only` is enabled and the package provides no wheel; a `.tar.gz` will happily be downloaded, pip will succeed, and the `next(iter(glob.glob("*.whl")))` call will fail, producing a mysterious `StopIteration`:
```
Saved ./artifactory-0.1.17.tar.gz
Successfully downloaded artifactory
(Traceback (most recent call last):
File "[redacted]/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "[redacted]/lib/python3.8/runpy.py", line 87, in …
```

fix: use `only-binary` for `download_only` `pip download`

---

.bcr/gazelle/presubmit.yml

The bzlmod-compatible build_file_generation example was moved to the bzlmod_build_file_generation example.
This should fix the automatic build/release of the gazelle BCR module.

fix(bzlmod+gazelle): update BCR release presubmit to use correct example

---

python/pip_install/repositories.bzl
python/pip_install/tools/wheel_installer/wheel_installer.py
python/repositories.bzl

We ignore pyc files most everywhere (because they aren't deterministic), but part of the pyc creation process involves creating temporary files named `*.pyc.NNN`. Though these are supposed to be temporary files nobody sees, they seem to get picked up by a glob somewhere, somehow. I'm unable to figure out how that is happening, but ignoring them in the glob expressions should also suffice.
Fixes #1261

fix: Ignore tempoary pyc.NNN files in wheels

---

python/pip_install/pip_repository.bzl

When using Windows you cannot run the symlink directly.
Because of how symlinks work in Windows we need to path realpath resolve the link.
Unlike Linux and OSX we cannot execute the Python symlink directly. Windows throws an error "-1073741515", when we execute the symlink directory.  This error means that the Python binary cannot find dlls. This is because the symlink that we create is not in the same folder as the dlls.

fix(bzlmod): Fixing Windows Python Interpreter symlink issues

---

docs/packaging.md
python/packaging.bzl

Also fix missing runfiles on the py_wheel.dist target.
Fixes #1130
Fixes #1270

fix(py_wheel.publish): allow twine tags and args

---

python/private/py_wheel.bzl
tests/py_wheel/BUILD.bazel
tests/py_wheel/py_wheel_tests.bzl

This adds some basic analysis tests of py_wheel to cover the functionality it's recently introduced.

test: basic analysis tests for py_wheel

---

python/private/proto/py_proto_library.bzl

plugin_output was wrong in case multiple repositories are involved and/or _virtual_imports. 
The code is taken from `cc_proto_library` and has been verified in practice.

fix: plugin_output in py_proto_library rule

---

examples/build_file_generation/WORKSPACE
internal_deps.bzl

Upgrading to the latest version of gazelle and rules_go.  This should address `--incompatible_config_setting_private_default_visibility` flag.

feat: Upgrading gazelle and rules_go

---

tools/build_defs/python/tests/BUILD.bazel
tools/build_defs/python/tests/py_test/py_test_tests.bzl

The analysis tests transition to different platforms to test some platform-specific logic.
When cc toolchain registration is enabled, this also requires that a more complete
toolchain be defined and available.

tests: make analysis tests support --incompatible_enable_cc_toolchain_resolution

---

MODULE.bazel
examples/bzlmod/description.md
examples/bzlmod/test.py
python/extensions/private/internal_deps.bzl
python/private/coverage_deps.bzl
python/repositories.bzl
tools/update_coverage_deps.py

Before this PR the `coverage_tool` automatically registered by `rules_python`
was visible outside the toolchain repository. This fixes it to be consistent
with `non-bzlmod` setups and ensures that the default `coverage_tool` is not
visible outside the toolchain repos.
This means that the `MODULE.bazel` file can be cleaned-up at the expense of
relaxing the `coverage_tool` attribute for the `python_repository` to be a
simple string as the label would be evaluated within the context of
`rules_python` which may not necessarily resolve correctly without the
`use_repo` statement in our `MODULE.bazel`.

fix(toolchain): restrict coverage tool visibility under bzlmod

---

python/repositories.bzl

Currently, Python toolchain `:files` and `:py3_runtime` include some unnecessary files. This is because these globs result in literally `lib/libpython{python_version}.so` etc., which do not match anything. The formatting needs to be applied here since it will not be applied later.
I believe this was introduced by a47c6cd681b34b1ad990ed40dcc01ab5f024406a.

fix: add `format()` calls to `glob_exclude` templates

---

examples/build_file_generation/BUILD.bazel
examples/bzlmod_build_file_generation/BUILD.bazel
examples/bzlmod_build_file_generation/gazelle_python.yaml
gazelle/manifest/defs.bzl

For certain workflows it is useful to calculate the integrity hash of
the manifest file based on a number of requirements files. The
requirements locking is usually done by executing a script on each
platform and having gazelle manifest generator be aware that more than
one requirements file may affect the outcome (e.g. the wheels that get
passed to modules map may come from multi_pip_parse rule) is generally
useful.
This change modifies the generation macro to concatenate the requirements
files into one before passing it to the manifest generator.

feat(gazelle): support multiple requirements files in manifest generation

---

python/cc/BUILD.bazel
python/pip.bzl
python/pip_install/pip_repository.bzl
python/private/bzlmod_enabled.bzl
python/private/util.bzl
python/repositories.bzl

Various parts of the codebase detect whether bzlmod is enabled or not. Most of them copy/paste the same if @ in Label(..) trick and use a comment to explain what they're doing.
Rather than copy/paste that everywhere, this commit uses a constant defined that does this once and reuses the constant value to determine if bzlmod is enabled.
Closes: https://github.com/bazelbuild/rules_python/issues/1295

feat(bzlmod): Use a common constant for detecting bzlmod being enabled

---

examples/bzlmod/BUILD.bazel
examples/bzlmod/MODULE.bazel
examples/bzlmod/tests/BUILD.bazel
python/extensions/python.bzl

I think this name is more informative for a public API. The functionality it exposes are rules/macros that use a specific Python version to be used. These aren't really aliases.
This commit renames "python_aliases" to "python_versions". This isn't technically a breaking
change because bzlmod support is still beta, but we'll flag it as such just in case.
BREAKING CHANGE:
* The `python_aliases` repo is renamed to `python_versions`. You will need to either
update references from `@python_aliases` to `@python_versions`, or use repo-remapping
to alias the old name (`use_repo(python, python_aliases="python_versions")`)
Closes #1273

fix(bzlmod)!: Changing repository name "python_aliases" to "python_versions"

---

examples/bzlmod/MODULE.bazel
python/extensions/pip.bzl

This commit defaults `the pip.parse` `python_version` attribute to the default version of
Python, as configured by the `python.toolchain` extension. This allows a user to use the
Python version set by rules_python or the root module. Also, this makes setting the
attribute optional (as it has a default) and we automatically select the interpreter.
Closes #1267

feat(bzlmod): Allow bzlmod pip.parse to reference the default python toolchain and interpreter

---

examples/bzlmod/BUILD.bazel
examples/pip_parse_vendored/requirements.bzl
python/pip_install/pip_hub_repository_requirements_bzlmod.bzl.tmpl
python/pip_install/pip_repository.bzl
python/pip_install/pip_repository_requirements.bzl.tmpl
python/pip_install/pip_repository_requirements_bzlmod.bzl.tmpl

Minor change.
I am creating a Python virtualenv with Bazel, and having `all_data_requirements` for data dependencies just like `all_requirements` would be very helpful.

feat: Create `all_data_requirements` alias

---

internal_deps.bzl

This uses the 0.4.0 release of rules_python, which has several features we can make use of
* Various internal APIs have been made public
* target_compatible_with can be set to skip tests by platform
* Unit tests are easier to write
Also adds rules_license 0.0.7, which is a dependency of rules_testing.
Work towards #1297

chore: Bump rules_testing to 0.4.0 from 0.0.5

---

.github/workflows/create_archive_and_notes.sh

Also add a note that bzlmod support is still beta.

docs: Use correct pip extension path in generated release notes

---

BZLMOD_SUPPORT.md

The project name was misspelled as "rule_python"; corrected to "rules_python"

doc: correct name of rules_python in bzlmod support doc

---

python/defs.bzl

This just adds a no-op comment to defs.bzl to make patching its load statements easier.
Rather than looking for the last load (or the conveniently loaded "# Export ..." comment),
just have an explicit comment for it.

cleanup: Add placeholder comment to defs.bzl to make patching loads easier

---

examples/multi_python_versions/tests/BUILD.bazel
python/config_settings/private/py_args.bzl
python/config_settings/transition.bzl
tests/config_settings/transition/BUILD.bazel
tests/config_settings/transition/py_args_tests.bzl

This fixes a bug where the version-aware rules required `main` to always be explicitly
specified. This was necessary because the main file is named after the outer target
(e.g. "foo"), but usage of the main file is done by the inner target ("_foo"). The net
effect is the inner target looks for "_foo.py", while only "foo.py" is in srcs.
To fix, the wrappers set main, if it isn't already set, to their name + ".py"
Work towards #1262

fix(multi-versions): correctly default 'main' arg for transition rules

---

python/extensions/pip.bzl
python/pip_install/pip_repository.bzl
python/pip_install/tools/lib/bazel.py
python/private/normalize_name.bzl
tests/pip_hub_repository/normalize_name/BUILD.bazel
tests/pip_hub_repository/normalize_name/normalize_name_tests.bzl

Before this PR there were at least 2 places where such a helper function
existed and it made it very easy to make another copy. This PR introduces a
hardened version, that follows conventions from upstream PyPI and tests have
been added.
Split from #1294, work towards #1262.

refactor: have a single function for normalized PyPI package names

---

python/extensions/pip.bzl
python/private/coverage_deps.bzl
python/private/version_label.bzl
tests/version_label/BUILD.bazel
tests/version_label/version_label_test.bzl

Before this PR there would be at least a few places where we would be
converting a `X.Y.Z` version string to a shortened `X_Y` or `XY` string segment
to be used in repository rule labels. This PR adds a small utility function
that helps making things consistent.
Work towards #1262, split from #1294.

refactor: add a version label function for consistent labels

---

examples/bzlmod/MODULE.bazel
python/extensions/pip.bzl

Reverts bazelbuild/rules_python#1303
The main issue is that `pip.parse()` accepts a locked requirements file -- this means
the requirements are specific to a particular Python version[1]. Because the default Python
version can arbitrarily change, the lock file may not be valid for the Python version
that is used at runtime. The net result is a module will use dependencies for e.g. Python
3.8, but will use 3.9 at runtime. Additionally, the dependencies resolved for 3.8 will
be created under names such as `@foo_39` (because that's the python_version pip.parse sees),
which is just more confusing.
BREAKING CHANGE:
* pip.parse() must have `python_version` explicitly set. Set it to the Python version
used to resolve the requirements file.
[1] Lock files aren't necessarily version specific, but …

revert(bzlmod)!: allow bzlmod pip.parse to implicitly use default python version

---

gazelle/python/target.go
gazelle/python/testdata/dependency_resolution_order/bar/BUILD.out
gazelle/python/testdata/dependency_resolution_order/baz/BUILD.out
gazelle/python/testdata/dependency_resolution_order/foo/BUILD.out
gazelle/python/testdata/dependency_resolution_order/somewhere/bar/BUILD.out
gazelle/python/testdata/first_party_file_and_directory_modules/foo/BUILD.out
gazelle/python/testdata/first_party_file_and_directory_modules/one/BUILD.out
gazelle/python/testdata/from_imports/foo/BUILD.out
gazelle/python/testdata/from_imports/import_from_init_py/BUILD.out
gazelle/python/testdata/from_imports/import_from_multiple/BUILD.out
gazelle/python/testdata/from_imports/import_nested_file/BUILD.out
gazelle/python/testdata/from_imports/import_nested_module/BUILD.out
gazelle/python/testdata/from_imports/import_nested_var/BUILD.out
gazelle/python/testdata/from_imports/import_top_level_var/BUILD.out
gazelle/python/testdata/from_imports/std_module/BUILD.out
gazelle/python/testdata/naming_convention/dont_rename/BUILD.out
gazelle/python/testdata/naming_convention/resolve_conflict/BUILD.out
gazelle/python/testdata/python_ignore_files_directive/bar/BUILD.out
gazelle/python/testdata/relative_imports/package2/BUILD.out
gazelle/python/testdata/sibling_imports/pkg/BUILD.out
gazelle/python/testdata/simple_library_without_init/foo/BUILD.out
gazelle/python/testdata/simple_test_with_conftest/bar/BUILD.out
gazelle/python/testdata/subdir_sources/foo/BUILD.out
gazelle/python/testdata/subdir_sources/foo/has_build/BUILD.out
gazelle/python/testdata/subdir_sources/foo/has_init/BUILD.out
gazelle/python/testdata/subdir_sources/foo/has_main/BUILD.out
gazelle/python/testdata/subdir_sources/foo/has_test/BUILD.out
gazelle/python/testdata/subdir_sources/one/BUILD.out
gazelle/python/testdata/subdir_sources/one/two/BUILD.out

When gazelle:python_root is not set or is at the root of the repo, we don't need to set imports for python rules, because that's the Bazel's default. This would reduce unnecessary verbosity.

feat: stop generating imports when not necessary

---

README.md
python/extensions/pip.bzl
python/extensions/python.bzl

This explains the different ways to register toolchains and how to use them.
Also fixes python_aliases -> python_versions repo name

docs: Better explain when and how to use toolchains for bzlmod

---

python/pip.bzl
python/pip_install/pip_repository.bzl
python/private/render_pkg_aliases.bzl
python/private/text_util.bzl
tests/pip_hub_repository/render_pkg_aliases/BUILD.bazel
tests/pip_hub_repository/render_pkg_aliases/render_pkg_aliases_test.bzl

Before this PR the only way to render aliases for PyPI package repos
using the version-aware toolchain was to use the `whl_library_alias` repo.
However, we have code that is creating aliases for packages within the hub repo
and it is natural to merge the two approaches to keep the number of layers of
indirection to minimum.
- feat: support alias rendering for python aware toolchain targets.
- refactor: use render_pkg_aliases everywhere.
- refactor: move the function to a private `.bzl` file.
- test: add unit tests for rendering of the aliases.
Split from #1294 and work towards #1262 with ideas taken from #1320.

refactor: support rendering pkg aliases without whl_library_alias

---

python/extensions/pip.bzl
python/extensions/private/internal_deps.bzl

Updated two files that used 'load("@rules_python' instead of 'load("//python'.
Closes: https://github.com/bazelbuild/rules_python/issues/1296

Feat: Using repo-relative labels

---

python/versions.bzl

Include s390x in release and update python-build-standalone to 3.9.17, 3.10.12, 3.11.4.
[Latest python-build-standalone release](https://github.com/indygreg/python-build-standalone/releases/tag/20230726) has s390x support added.
These changes are needed to build TensorFlow on s390x, which is currently blocked due to missing support.

feat: Add s390x release

---

tests/cc/BUILD.bazel

Newer Bazel versions default to not exporting files by default; this explicitly exports the file so it can be referenced.

tests: Expose test's fake_header.h so py_cc_toolchain tests can use it.

---

.bcr/config.yml

Fixes https://github.com/bazelbuild/bazel-central-registry/pull/863.
The aspect email is no longer associated with the github user, so the CLA bot but doesn't
think think the CLA is signed. To fix, change the email the BCR PRs are published under
to an address that is associated with the github user (and thus the CLA).

fix: bcr releaser email

---

CHANGELOG.md
python/pip_install/pip_repository.bzl
python/repositories.bzl

Put the `PYTHONPATH` entries used in wheel building as a default value to a
private attribute of the `whl_library` repository rule and use resolved path of
the interpreter target in creating execution environment to avoid repository
rule restarts when fetching external dependencies.
The extra private attribute on the `whl_library` removes all but one restart
and the extra refactor removes the last restart observed when running, which
also reduces the total execution time from around 50s to 43s on my machine:
```console
$ cd examples/bzlmod
$ bazel clean --expunge --async && bazel build //entry_points:yamllint
```
Fixes #1399

fix(whl_library): avoid unnecessary repository rule restarts

---

python/config_settings/BUILD.bazel
python/config_settings/private/BUILD.bazel

I'm working on adding a new pip package download rule to the repo
called `pypi_install`. For that, I set up a new
`examples/pypi_install` directory. When I imported `rules_python` via
a `local_repository`, however, the build complained about missing
files. This patch aims to fix that issue by making the missing files
available.
I tried copying the other `distribution` targets when creating this
one.

refactor: add missing `//python/config_settings/private:distribution` target

---

CHANGELOG.md
python/config_settings/transition.bzl

This makes the version-aware transition rule compatible with an upcoming Bazel change that
disallows setting unknown attributes to None (the `distribs` attribute, in this case).
The `distribs` attribute was common to all rules, but it has been long deprecated and
it won't be part of every rule in upcoming Bazel versions. The previous implementation
resulted in setting `distribs = None` on the target. Bazel won't support setting
undefined attributes to None.
Addresses: https://github.com/bazelbuild/bazel/issues/19403

fix: don't set distribs in version transitioning rule

---

CHANGELOG.md
examples/build_file_generation/WORKSPACE
gazelle/MODULE.bazel
gazelle/WORKSPACE
internal_deps.bzl

This makes rules_python's usage of Go work with upcoming Bazel versions. The
`_whitelist_function_transition` attribute in the Go rules is being removed, per
https://github.com/bazelbuild/bazel/issues/19493. Newer Go rule releases are compatible
with the upcoming Bazel versions.
Fixes : [1409](https://github.com/bazelbuild/rules_python/issues/1409)

fix(gazelle): upgrade rules_go: 0.39.1 -> 0.41.0 to work with upcoming Bazel versions

---

gazelle/MODULE.bazel
gazelle/go.mod
gazelle/go.sum
gazelle/python/BUILD.bazel
gazelle/python/parser.go
gazelle/python/std_modules.go

`bazel.Runfiles` is a deprecated way to look up runfiles that can result in non-hermetic lookups. `github.com/bazelbuild/rules_go/go/runfiles` is the recommended package for this.

fix: gazelle: Fix non-hermetic runfiles lookup

---

python/private/common/attributes.bzl
python/private/common/attributes_bazel.bzl
python/private/common/common.bzl
python/private/common/common_bazel.bzl
python/private/common/providers.bzl
python/private/common/py_binary_bazel.bzl
python/private/common/py_binary_macro.bzl
python/private/common/py_executable.bzl
python/private/common/py_executable_bazel.bzl
python/private/common/py_library.bzl
python/private/common/py_library_bazel.bzl
python/private/common/py_library_macro.bzl
python/private/common/py_runtime_macro.bzl
python/private/common/py_runtime_rule.bzl
python/private/common/py_test_bazel.bzl
python/private/common/py_test_macro.bzl
python/private/common/semantics.bzl

This is a copy of the Starlark implementation of the Python rules from Bazel. This code isn't
loaded and won't work as-is. Modifications to make it work will be made in
subsequent changes. It's almost pristine; changes are made to satisfy the
buildifier check.

internal: copy Starlark rule implementation from Bazel

---

python/private/common/BUILD.bazel
python/private/common/attributes.bzl
python/private/common/cc_helper.bzl
python/private/common/common.bzl
python/private/common/common_bazel.bzl
python/private/common/providers.bzl
python/private/common/py_binary_macro_bazel.bzl
python/private/common/py_binary_rule_bazel.bzl
python/private/common/py_executable.bzl
python/private/common/py_executable_bazel.bzl
python/private/common/py_internal.bzl
python/private/common/py_library.bzl
python/private/common/py_library_macro_bazel.bzl
python/private/common/py_library_rule_bazel.bzl
python/private/common/py_runtime_rule.bzl
python/private/common/py_test_macro_bazel.bzl
python/private/common/py_test_rule_bazel.bzl
tools/build_defs/python/private/BUILD.bazel
tools/build_defs/python/private/py_internal_renamed.bzl

This just makes the files able to get passed the loading stage under Bazel 7+.
This mostly involves fixing load statements, but also exposed a couple places where
py_internal needs some small changes.
* Also renames files to better distinguish rule vs macro vs Bazel-specific. This makes it easier to patch them within Google and more clear about which file is doing what.

internal(pystar): make starlark impl (mostly) loadable

---

CHANGELOG.md
python/repositories.bzl

This change introduces support for `netrc` and `auth_patterns` attributes in `python_repository` (and by extension, `python_register_toolchains`). This allows consuming projects to fetch custom Python toolchain binaries from a private/authenticated HTTP host when specified directly by URL in `python_register_toolchains`.
The implementation proposed here mirrors that of `http_archive`: https://github.com/bazelbuild/bazel/blob/1cf392ff3918386858b8c038f82c013b1e04be98/tools/build_defs/repo/http.bzl#L116
Fixes #1215.

feat: Support netrc-based authentication for python_repository rule

---

CHANGELOG.md
gazelle/python/parser.go
gazelle/python/std_modules.go

Pass the environment generated by the `runfiles` helper so that the
Python launcher can find the runfiles correctly as implemented in
bazelbuild/bazel#14740.
Fixes #1426

fix(gazelle): runfiles discovery

---

.bazelignore
CHANGELOG.md
docs/BUILD.bazel
python/BUILD.bazel
python/packaging.bzl
python/private/BUILD.bazel
python/private/common/py_executable.bzl

Changed `py_wheel` to load `py_binary` instead of using `native.py_binary`. This caused the doc generation to fail because of the additional loads(), so the doc libraries were refactored to represent the additional loads. This adds `//python:packaging_bzl`
as a public target.
Docs were failing to build because Stardoc wasn't able to process the value `cc_helper.use_cpp_toolchains()` returned. For some reason, under Stardoc, the value is some mocked out value that it can't handle. This is easily fixed by just using the regular way for referencing an optional toolchain; the labels the two use are the same.

feat, refactor(pystar): bzl_library for packaging.bzl; fix pystar doc building and py_wheel

---

python/extensions/private/pythons_hub.bzl
python/pip.bzl
python/private/full_version.bzl
python/repositories.bzl

Before this PR in numerous places we would check the MINOR_MAPPING dict.
This PR adds a function that also fails if the X.Y format is not in the
MINOR_MAPPING dict making the code more robust.
Split from #1340 to unblock #1364.

refactor(toolchain): use a helper method to convert an X.Y version to X.Y.Z

---

python/extensions/python.bzl

If the python version is explicitly provided by the root module, they should not be warned for choosing the same version that rules_python provides as default.

fix: Skip printing unneccesary warning.

---

CHANGELOG.md
MODULE.bazel
python/extensions/pip.bzl

This ensures that under bzlmod with `--lockfile-mode=update` we
would generate an entry per os/arch, which is needed because the
hermetic toolchain interpreter path is os/arch dependent.
Summary:
- add bazel_features dep
- mark the pip extension as arch/os dependent
Related: bazelbuild/bazel#19154

feat(bzlmod): mark pip extension as os/arch dependent

---

.bazelci/presubmit.yml
docs/BUILD.bazel

Since Bazel 7 isn't yet available, and we need a couple recent commits in Bazel, the
last_green release is used. This will eventually be changed to "rolling" once the
necessary commits are available in the next rolling release.
Because we're at the limit of 80 test jobs, some existing jobs have to be removed
and only a limited number of cases can be currently covered. I opted to remove
the pip_install tests, since they're redundant with the pip_parse tests, which
frees up 4 slots. Two test configs are added: one using workspace, the other using
bzlmod; both run the default tests on Ubuntu. This will provide some basic coverage;
more slots will free up when Bazel 5.4 support is dropped and Bazel 7 is released.
Work toward #1069

tests(pystar): CI configs that uses Starlark implementation of rules

---

python/private/autodetecting_toolchain.bzl
python/private/py_runtime_pair.bzl
python/private/python_bootstrap_template.txt

This copies the useful pieces from @bazel_tools//tools/python into rules_python. They're copied in relatively as-is, and not yet used. Subsequent commits will make them usable.
These pieces are:
* Bootstrap template (python_bootstrap_template.txt)
* The py_runtime_pair rule (split from toolchain.bzl)
* Autodetecting toolchain setup (split from toolchain.bzl)

internal(pystar): Copy @bazel_tools//tools/python files to rules_python

---

python/private/BUILD.bazel
python/private/autodetecting_toolchain.bzl
python/private/autodetecting_toolchain_interpreter.sh
python/private/py_runtime_pair_macro.bzl
python/private/py_runtime_pair_rule.bzl

They aren't quite usable yet. This mostly fixes references and adds
surrounding infrastructure to make this mostly loadable and somewhat runnable.
Note that the "autodetecting" name is misleading: it doesn't really
autodetect anything. But it's the established name and part of the
public API.
The autodetecting toolchain is trimmed down from what Bazel does. The
Bazel version has a Python 2 variant and a "non strict" mode to support
that. With Python 2 no longer supported, that code is removed.
* Also alphabetically sorts the bzl_libraries in //python/private

internal(pystar): Make py_runtime_pair and autodetecting toolchain mostly loadable.

---

python/BUILD.bazel
python/private/BUILD.bazel
python/py_runtime_pair.bzl
tests/py_runtime/BUILD.bazel
tests/py_runtime/py_runtime_tests.bzl
tests/py_runtime_info_subject.bzl
tests/py_runtime_pair/BUILD.bazel
tests/py_runtime_pair/py_runtime_pair_tests.bzl

These analysis tests verify that `py_runtime` and `py_runtime_pair` are working as intended
for both the native Bazel and Starlark implementations.

tests(pystar): py_runtime_pair and py_runtime analysis tests

---

python/private/common/py_executable.bzl
python/private/common/py_executable_bazel.bzl

These are restricted use APIs, so they have to go through py_internal.
They aren't caught by CI because tests don't currently cover their code paths; fixing that will
be done in a separate change.

fix(pystar): Use py_internal for runfiles_enabled, declare_shareable_artifact, share_native_deps

---

python/private/BUILD.bazel

This allows depending on just e.g. `//python:defs_bzl` without having to also depend on our internal //docs targets or manually including the extra bazel_tools files.
The missing files were hidden by the doc tests because those tests manually include the extra files. Under the hood, it goes:
* defs.bzl ->
* py_runtime_pair.bzl -> 
* @bazel_tools//tools/python:toolchain.bzl ->
* @bazel_tools//tools/python:private/defs.bzl -> 
(Note the relationshps within @bazel_tools are Bazel-version specific)
Unfortunately, there isn't a public target for just the subset of files we need from @bazel_tools, so we have to use the larger glob of all of `@bazel_tools//tools`.

fix: add missing `@bazel_tools` files to bzl_library dependencies.

---

BUILD.bazel
docs/BUILD.bazel
python/BUILD.bazel
python/pip_install/BUILD.bazel
python/pip_install/private/BUILD.bazel
python/private/BUILD.bazel

This moves the dependency management of what transitive files are needed to generate docs for a .bzl file out of the docs directory and into the respective bzl file's directory. This ensures that the bzl_library targets we expose to users contain all the necessary dependencies.
Because there are some projects using the bzl_library targets in //docs, some compatiblity aliases are added to make their migration path easier. Those targets only public for historical reasons and shouldn't be used.
Work towards #1458

docs: move dependency management into respective bzl packages

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

This largely covers how to introduce a breaking change.
It also attempts to clarify what is or isn't a breaking change.
Closes #1424
Work towards #1361

docs: document a breaking changes policy

---

python/BUILD.bazel
python/private/BUILD.bazel
python/private/register_extension_info.bzl
python/py_binary.bzl
python/py_library.bzl
python/py_test.bzl

Within Google, we have to patch some files so some additional tooling can capture some metadata. To make patching easier, call some no-opt stubs, which makes the patches smaller and more likely to apply without issues.

internal: add stub register_extension_name to make patching easier

---

tests/base_rules/base_tests.bzl

Within Google, for historical reasons, the filegroup rule type is allowed in deps, which means `test_requires_pyinfo` test fails. This can be easily worked around by using a custom rule that doesn't have the same name.

test: use a custom rule instead of native.filegroup for testing that PyInfo is a required provider.

---

examples/wheel/BUILD.bazel
examples/wheel/wheel_test.py
python/tests/toolchains/run_acceptance_test.py.tmpl
tests/runfiles/BUILD.bazel
tests/runfiles/runfiles_test.py

A few tests weren't compatible with bzlmod, so would fail when it was enabled. The various causes and fixes are:
* Under bzlmod, `runfiles.CurrentRepository()` returns the empty string for the main repository. To fix, an environment variable is used to tell the test whether bzlmod is enabled or not.
* Accessing data files through `TEST_SRCDIR` directly is error-prone under bzlmod because the directory name within runfiles changes from the workspace name to `_main`. To fix, use the runfiles libraries, which know how to map apparent repo names to the actual directory name. In the integration tests, the runfiles library isn't available, so just check for the `_main` directory instead.
Work towards #1469

test(bzlmod): Make some tests bzlmod compatible with Bazel@HEAD

---

.gitattributes
docs/BUILD.bazel
docs/packaging.md
docs/pip.md
docs/pip_repository.md
docs/py_cc_toolchain.md
docs/py_cc_toolchain_info.md
docs/py_console_script_binary.md
docs/python.md
python/entry_points/py_console_script_binary.bzl

Before this PR the documentation used to be next to the source. With
the adjustment of how we generate the markdown files, we can keep user
friendly documentation in markdown and leave the API docs in the `.bzl`
source code. This improve the maintainability of the docs as editors
have better support for editing markdown in markdown files as opposed to
docstrings within `.bzl` files.
NOTE: This is implemented via a genrule in order to not expose a macro as an
consumable API.
Summary:
- chore: mark the documentation files as non-generated
- chore: chmod -x markdown files
- feat: adjust doc generation to retain headers and modify the header
- refactor: move the docs from .bzl and improve them
Work towards #1332

docs: allow manual edits to generated docs

---

.bazelci/presubmit.yml

This PR changes the specific version that is used to test starlark
rules_python rules implementation, which broke in recent bazelbuild/bazel
commits. Once the following issue is fixed, this can be reverted.
Towards #1496
Related bazelbuild/bazel#19838

ci: pin pystar bazel version

---

CHANGELOG.md
examples/wheel/wheel_test.py
tools/wheelmaker.py

Current implementation does not produce deterministic output because:
- `ZipFile.writestr()` leaks current date and time
- `ZipFile.write()` leaks the source file's mtime and mode bits (permissions) into the resulting zip archive.
By manually creating our own `ZipInfo` objects we can explicitly set date and time fields to `Jan 1, 1980, 00:00` (minimum value allowed by the zip file standard), and ensure that other file attributes are uniform across all entries in a zip file.

fix(py_wheel): produce deterministic wheel files

---

python/pip_install/pip_repository.bzl
python/pip_install/private/generate_whl_library_build_bazel.bzl
python/pip_install/tools/wheel_installer/arguments.py
python/pip_install/tools/wheel_installer/wheel_installer.py
tests/pip_install/whl_library/generate_build_bazel_tests.bzl

Before the PR the downloading/building of the wheel and the extraction
would be done as a single step, which meant that for patching of the
wheel to happen, we would need to do it within the python script. In
order to have more flexibility in the approach, this PR splits the
process to two separate invocations of the wheel_installer, which
incidentally also helps in a case where the downloading of the wheel
file can happen separately via http_file.
Related issues #1076, #1357

refactor(whl_library): split wheel downloading and extraction into separate executions

---

CHANGELOG.md
examples/wheel/wheel_test.py
tools/wheelmaker.py

This class is for being able to more easily recreate a wheel file after
extracting it. This is not intended for usage outside the rules_python
project. Also stop sorting the entries when writing a RECORD file making
the order of the RECORD file to be the same as the order the files to
the zip file are added.
Towards #1076

feat(whlmaker): introduce an internal _WhlFile class and stop sorting RECORD

---

CHANGELOG.md
examples/bzlmod/test.py
examples/bzlmod_build_file_generation/__test__.py
examples/wheel/wheel_test.py

`TestCase.assertEquals` is an alias for `TestCase.assertEqual`.
[This method is deprecated since Python 3.2 and was removed in Python 3.12](https://docs.python.org/3/whatsnew/3.12.html#id3).

test: remove usage of deprecated method `TestCase.assertEquals`

---

CHANGELOG.md
python/pip.bzl
python/pip_install/pip_repository.bzl
python/pip_install/repositories.bzl
python/repositories.bzl

This brings back the generated documentation for the pip_parse
attributes making switches to default values more prominent.
Towards #1496.

refactor!: do not use a wrapper macro for pip_parse

---

python/py_cc_link_params_info.bzl

The PyCcLinkParamsInfo export wasn't respecting the `config.enable_pystar` setting. This
would cause the Starlark implementation to look up the wrong provider symbol and result
in an error later.

internal(pystar): use rules_python PyCcLinkParamsProvider if pystar is enabled

---

.readthedocs.yml
docs/sphinx/conf.py
docs/sphinx/readthedocs_build.sh
sphinxdocs/BUILD.bazel
sphinxdocs/private/sphinx.bzl

This fixes a few issues with the RTD doc building:
* Warning banner is now shown for PR requests
* Pages now link to the github source
* The footer now shows the git commit they were built at
This works by passing the RTD environment variables to the sphinx build process, which allows the conf.py file to get their values. Env vars are passed by a new flag, `--//sphinxdocs:extra_env`, which allows passing arbitrary environment variable values into the sphinx build process. To make future usage of the RTD env vars easier, the build process passes along all the `READTHEDOCS*` environment variables.
Fixes #1516

docs: show PR warning banner and fix links doc source pages

---

examples/multi_python_versions/MODULE.bazel
examples/multi_python_versions/tests/my_lib_test.py

Bazel is enabling bzlmod by default, which means the examples need to be updated to be bzlmod compatible.

tests: make multi_python_verions example bzlmod compatible

---

tests/compile_pip_requirements/MODULE.bazel

Bazel at head has bzlmod enabled by default, so the example needs to be updated to work with bzlmod enabled.

test: make compile_pip_requirements work with bzlmod enabled

---

tests/pip_repository_entry_points/.bazelrc

Bazel at head enables bzlmod by default, but the requirements.bzl entry_point functions aren't supported under bzlmod. Until workspace support is entirely dropped, explicitly disable bzlmod for the pip_repository_entry_points test.
Work towards #1590

tests: explicitly disable bzlmod for pip_repository_entry_points test

---

examples/pip_parse_vendored/.bazelrc
examples/pip_parse_vendored/WORKSPACE
examples/pip_parse_vendored/requirements.bzl

Bazel at head enables bzlmod by default, but the pip_parse_vendored example doesn't work
under bzlmod.
To fix, explicitly disable bzlmod because vendoring requirements.bzl files isn't necessary
under bzlmod. This is because the pip bzlmod extension handles creating repos directly
from the locked requirements file (which is the output of the pip dependency resolution
process).
While we're here, also enable `incompatible_generate_aliases = True`, in preparation for
that being switched.

tests: explicitly disable bzlmod for pip_parse_vendored example

---

.bazelci/presubmit.yml
tests/compile_pip_requirements/.bazelignore
tests/compile_pip_requirements_test_from_external_workspace/MODULE.bazel
tests/compile_pip_requirements_test_from_external_workspace/WORKSPACE

Bazel at head enables bzlmod by default, so the tests must also be
updated to be bzlmod compatible.
Also makes compile_pip_requirements ignore its convenience symlinks.
This allows locally running the "from external" workspace test even if
the compile_pip_requirements workspace previously had convenience
symlinks in it from other builds.

test: make compile_pip_requirements_test_from_external_workspace work with bzlmod

---

examples/pip_parse/BUILD.bazel
examples/pip_parse/MODULE.bazel
examples/pip_parse/WORKSPACE
examples/pip_parse/pip_parse_test.py

Bazel is enabling bzlmod by default, which means the examples need to be updated to be bzlmod compatible.

tests: make pip_parse example work with bzlmod enabled

---

python/pip_install/requirements.bzl
python/pip_install/tools/dependency_resolver/dependency_resolver.py

Using click makes it easier to parse arguments. Many args are now named arguments
(options), and the need for using positional args with stub `"None"` values isn't
necessary anymore.
There is already a dependency on click via piptools, so this doesn't introduce a new
dependency.
Relates to #1067

refactor: use click in dependency_resolver.py

---

python/private/common/attributes.bzl
python/private/common/common.bzl
python/private/common/providers.bzl
python/private/common/py_binary_rule_bazel.bzl
python/private/common/py_executable.bzl
python/private/common/py_executable_bazel.bzl
python/private/common/py_test_rule_bazel.bzl
python/private/common/semantics.bzl

The location of the `@bazel_tools` and `@platforms` repositories were originally part of the semantics.bzl config because performing rewrites on the code as part of the Bazel code export process was too difficult.
With the direction being reversed (imported instead of exported), and the scope of the codebase being reduced (just rules_python instead of the entire Bazel codebase), it's easier to perform copybara rewrites.
In particular, the `"//` strings are problematic to rewrite because they look like intra-repo references instead of parts of a larger expression.

cleanup(pystar): inline @bazel_tools and @platforms references

---

python/pip_install/BUILD.bazel
python/pip_install/pip_repository.bzl

The non-bzlmod pip_repository code loads the bzlmod pip_repository code for some reason,
but nothing else uses that reference. A comment indicates it was only done to make
merge conflicts easier to manage for PR #1476.

cleanup: delete defunct load of bzlmod pip_repository

---

CHANGELOG.md
examples/pip_parse_vendored/requirements.bzl
python/pip_install/pip_repository.bzl
python/pip_install/pip_repository_requirements.bzl.tmpl
python/private/bzlmod/pip_repository.bzl
python/private/bzlmod/requirements.bzl.tmpl

Currently a BUILD file can load `all_whl_requirements` but then can't determine which one is associated with a given package installed by the user.
This makes it impossible to build rules where the user can choose a given package and then override the wheel used, for example. @mattem and I are working at a client where we need this ability.
This PR makes a small, non-breaking refactoring to the generated `requirements.bzl` file so that this information is available in a new `all_whl_requirements_by_package` symbol.
Users can then do something like this:
```
load("@pip//:requirements.bzl", "all_whl_requirements_by_package")
some_rule(
wheels = dict(all_whl_requirements_by_package, **{
"charset-normalizer": "@charset_1_2_3//:file"
}),
)
```

feat(pip): provide pypi -> whl target mapping in requirements.bzl

---

CHANGELOG.md
docs/sphinx/BUILD.bazel
docs/sphinx/pyproject.toml
docs/sphinx/requirements.in
docs/sphinx/requirements_darwin.txt
docs/sphinx/requirements_linux.txt
examples/build_file_generation/BUILD.bazel
examples/bzlmod/BUILD.bazel
examples/bzlmod/other_module/BUILD.bazel
examples/bzlmod_build_file_generation/BUILD.bazel
examples/multi_python_versions/requirements/BUILD.bazel
examples/pip_parse/BUILD.bazel
examples/pip_parse_vendored/BUILD.bazel
examples/pip_repository_annotations/BUILD.bazel
python/pip_install/requirements.bzl
tests/compile_pip_requirements/BUILD.bazel
tests/pip_repository_entry_points/BUILD.bazel
tools/publish/BUILD.bazel

With this PR we can also use `pyproject.toml` in addition
to `requirements.in` which helps in making the requirements
in a more structured form. For example, we could parse the
toml itself and create aliases in the hub repos only for the
packages outlined in the `pyproject.toml` file. The same for
`gazelle`, we could restrict `gazelle_python.yaml` contents
to only the dependencies listed in `pyproject.toml`.
Examples can be migrated once we agree on the interface.
Summary:
- feat: support pyproject.toml in compile_pip_requirements
- chore: use pyproject.toml for sphinx doc requirements

feat: support pyproject.toml in compile_pip_requirements

---

examples/pip_parse/pip_parse_test.py

I forget to remove a commented out line before merging a PR; just cleaning that up.

cleanup: delete commented out line forgottenly left in

---

CHANGELOG.md
gazelle/python/generate.go
gazelle/python/testdata/monorepo/coarse_grained/BUILD.out

With a recent change to generate a single test target per python file
we introduced a regression for projects using
`# gazelle:python_generation_mode project` configuration directive
if there are multiple files with the same filenames but under different
directories within the source tree. This PR fixes the behaviour so that
we just generate a single target containing all test files as there is
no sure way to denormalize the paths so that they never clash.
Fixes #1442.

fix(gazelle): generate a single `py_test` for coarse_grained setups

---

examples/pip_repository_annotations/.bazelrc

The pip_repository_annoations example is workspace-only. Its equivalent functionality is demonstrated in examples/bzlmod with the whl_mods feature.

tests: disable bzlmod for workspace-only pip_repository_annotations example

---

examples/build_file_generation/.bazelrc

The build_file_generation example only supports workspace style builds. The bzlmod equivalent is in `examples/bzlmod_build_file_generation`

tests: disable bzlmod for workspace-only build_file_generation example

---

python/repositories.bzl

Part of the pyc compilation process is to create a temporary file named `<name>.pyc.NNNN`, where `NNNN` is a timestamp. Once the pyc is entirely written, this file is renamed to the regular pyc file name. These files only exist for brief periods of time, but its possible for different threads/processes to see the temporary files when computing the glob() values. Later, since the file is gone, an error is raised about the file missing.
PR #1266 mostly fixed this issue, except that the exclude for the `.pyc.NNNN` files for an
interpreter runtime's files was behind the `ignore_root_user_error` flag, which meant it
wasn't always applied. This changes it to always be applied, which should eliminate the
failures due to the missing NNNN files.
Fixes #1261

fix: always ignore `.pyc.NNNN` files from the hermetic runtime tree

---

CHANGELOG.md
tools/wheelmaker.py

Python2 has been EOL for a while so this is just a small cleanup.

chore(wheelmaker): drop Python 2 support

---

.bazelci/presubmit.yml
tests/base_rules/py_executable_base_tests.bzl

This is to have better test coverage. Only workspace for them is used because of limited CI slots.
This also fixes the test_basic_windows test. The `--build_python_zip` flag built into Bazel has a different default depending on the host OS (not target platform): true for windows, and false otherwise. Updated the test to force the flag value for reliable behavior between platforms.

test(pystar): run pystar under Windows and Mac

---

gazelle/python/BUILD.bazel
gazelle/python/gazelle_test.bzl

This provides better caching and it allows us to have better
developer velocity whilst iterating on a single test case and
it also solves some of the `timeout` errors I was seeing locally
because now each `gazelle` invocation is run at a lower
parallelism that `bazel` decides itself.

test(gazelle): have a go_test target for each gazelle test

---

CHANGELOG.md
gazelle/python/resolve.go
gazelle/python/testdata/relative_imports/BUILD.in
gazelle/python/testdata/relative_imports/BUILD.out
gazelle/python/testdata/relative_imports/package2/BUILD.out
gazelle/python/testdata/relative_imports/package2/module3.py

Modify the Gazelle plugin so that when it adds a `dep` because of a `resolve` directive it makes it a relative import if possible.
The first commit adds a test for the existing behavior, where inside of `//package2` the dependency `//package2:resolved_package` is added. The second commit updates the test and the behavior so inside of `//package2` we add `: resolved_package` instead.

feat(gazelle): use relative paths for resolved imports

---

python/private/proto/py_proto_library.bzl

Only append the `[proto_root]` to PYTHONPATH when it's actually necessary, i.e. when the generated Python modules are under _virtual_imports. Do no append it in the general case, when `[proto_root]` is just the repository root.
This makes it much less likely that adding a transitive dep on a `py_proto_library` will reorder the `PYTHONPATH`. Such reordering is undesirable because it may lead to import errors.
Fixes #1551

fix: py_proto_library: append to PYTHONPATH less

---

CHANGELOG.md
python/private/render_pkg_aliases.bzl
tests/pip_hub_repository/render_pkg_aliases/render_pkg_aliases_test.bzl

This fixes the cases where the 'default_version' is passed to the
'render_pkg_aliases' utility but the 'default_version' is not present
for the wheels. This usually happens when a sub-module is using the
'pip.parse' extension and the default_version can only be set by the
root module.
Previously, such a case would generate a `select()` expression that mapped
the default condition to a non-existent target (because the sub-module didn't
call `pip.parse()` with that version). This would either result in errors
due the target not existing, or silently using a target intended for a
different Python version (which may work, but isn't correct to so).
Now, it results in a error via `select.no_match_error`.
Fixes #1548.

fix(bzlmod pip): ensure that sub-modules do not have invalid repos

---

CHANGELOG.md
gazelle/python/generate.go
gazelle/python/testdata/per_file/BUILD.out
gazelle/python/testdata/per_file_subdirs/bar/BUILD.out
gazelle/python/testdata/per_file_subdirs/test_target/BUILD.in
gazelle/python/testdata/per_file_subdirs/test_target/BUILD.out

Previously the per-file target generation only worked for py_library targets. This change makes it so that this feature works for py_test targets as well.
The change is careful to not affect any existing tests, so I'm not sure if it should count as a breaking change. New tests have been added to check the new functionality.

feat(gazelle): allow per-file py_test generation

---

CHANGELOG.md
python/repositories.bzl

closes #1544 
The tcl subdirectory of the interpreter Windows build needs to be kept otherwise packages such as matplotlib will break.

fix(toolchains): include tcl/** files in Windows interpreter

---

python/defs.bzl
python/private/BUILD.bazel
python/private/common/BUILD.bazel
python/private/common/attributes.bzl
python/private/common/common.bzl
python/private/common/py_executable.bzl
python/private/common/py_library.bzl
python/private/reexports.bzl
python/py_info.bzl
tests/base_rules/base_tests.bzl
tests/base_rules/py_info_subject.bzl

This makes the rules_python Starlark implementation accept and return the builtin providers. This allows depending on, and being depended on by, the builtin rules, which enables the two rule sets to interoperate better.

pystar: support builtin providers for compatibility

---

CHANGELOG.md
python/BUILD.bazel
python/private/common/BUILD.bazel
python/private/common/providers.bzl
python/private/common/py_runtime_rule.bzl
python/private/py_runtime_pair_rule.bzl
python/private/reexports.bzl
python/private/util.bzl
python/py_runtime.bzl
python/py_runtime_info.bzl
python/py_runtime_pair.bzl
tests/base_rules/util.bzl
tests/py_runtime/py_runtime_tests.bzl
tests/py_runtime_pair/py_runtime_pair_tests.bzl

This switches over to using the rules_python implementation of `py_runtime`,
`py_runtime_pair`, and `PyRuntimeInfo` for Bazel 6 and higher. Bazel 5 lacks features
(specifically provider ctors) to allow enabling it on that version.
This is possible because the rules don't directly use the PyRuntimeInfo provider
(mostly, see below), they only care about the structure of it as exposed from the
ToolchainInfo provider.
Switching the toolchain providers and rules over early allows some development of
the toolchain prior to Bazel 7 and the rest of the rules_python Starlark implementation
being enabled.
The builtin PyRuntimeInfo is still returned and accepted for two reasons:
* Better compatibility with the builtin rules to make transitioning easier
* `py_binary` has an old, possibly defunct (not …

feat: use rules_python implemented py_runtime, py_runtime_pair, PyRuntimeInfo

---

CHANGELOG.md
docs/sphinx/pypi-dependencies.md

This PR updates the docs for https://github.com/bazelbuild/rules_python/pull/1166 since there were some inconsistencies about the naming (`experimental_requirement_cycles` vs `requirement_cycles`). Also moved the entry in the changelog from `0.27` to `Unreleased` since it missed `0.27`. Can't wait for this feature to land!

docs(pip_parse): Update docs about `experimental_requirement_cycles`

---

examples/py_proto_library/MODULE.bazel
examples/py_proto_library/example.com/proto/BUILD.bazel
examples/py_proto_library/example.com/proto/pricetag.proto
examples/py_proto_library/test.py

This behaviour should be in the latest release (0.27.0), so just
documenting it for the future.
Fixes #1005

doc: add a py_proto_library example with well-known-types

---

examples/pip_parse/MODULE.bazel

When the pip_parse example was updated to use sphinx to demonstrate circular deps, its MODULE.bazel config was forgotten to also be updated to use the requirement_cycles feature to break the circular deps.
Fixes #1595

examples(pip_parse): fix circular deps with sphinx by breaking cycles

---

examples/pip_parse/MODULE.bazel

With bazel 7 released, this example started failing on regular PRs.

ci(example): provide a specific requirements.txt on windows

---

CHANGELOG.md
examples/bzlmod/MODULE.bazel
examples/pip_parse/MODULE.bazel
python/pip_install/pip_repository.bzl
python/pip_install/private/generate_whl_library_build_bazel.bzl
python/pip_install/tools/wheel_installer/BUILD.bazel
python/pip_install/tools/wheel_installer/arguments.py
python/pip_install/tools/wheel_installer/arguments_test.py
python/pip_install/tools/wheel_installer/wheel.py
python/pip_install/tools/wheel_installer/wheel_installer.py
python/pip_install/tools/wheel_installer/wheel_installer_test.py
python/pip_install/tools/wheel_installer/wheel_test.py
python/private/bzlmod/pip.bzl
python/private/text_util.bzl
tests/pip_install/whl_library/generate_build_bazel_tests.bzl

Before this change, the dependency closures would be influenced by the
host-python interpreter, this removes the influence by detecting the
platforms against which the `Requires-Dist` wheel metadata is evaluated.
This functionality can be enabled via `experimental_target_platforms`
attribute to the `pip.parse` extension and is showcased in the `bzlmod`
example. The same attribute is also supported on the legacy `pip_parse`
repository rule.
The detection works in the following way:
- Check if the python wheel is platform specific or cross-platform
(i.e., ends with `any.whl`), if it is then platform-specific
dependencies are generated, which will go through a `select`
statement.
- If it is platform specific, then parse the platform_tag and evaluate
the `Requires-Dist` markers assuming the …

feat(whl_library): generate platform-specific dependency closures

---

gazelle/python/generate.go
gazelle/python/testdata/binary_without_entrypoint/BUILD.out

Unlike Go, the main module of Python can still be imported by other modules. We should keep them in the `py_library` target to allow such imports.

feat: keep main module in py_library

---

python/private/BUILD.bazel
python/private/py_runtime_pair_rule.bzl
tests/py_runtime_pair/py_runtime_pair_tests.bzl

This fixes two bugs from https://github.com/bazelbuild/rules_python/pull/1574:
* Bazel 6's py_binary rejects the rules_python Starlark implemented PyRuntimeInfo.
* python_bootstrap_template.txt isn't public; this prevents py_runtime from being
used outside rules_python itself (e.g. in the python toolchain repos)
With Bazel 6, the `py_binary` rule performs a type check of the PyRuntimeInfo value it gets from the toolchain to verify it is an instance of the Java-implemented PyRuntimeInfo class. This type check fails when the provider is implemented in rules_python in Starlark.
To fix, make the `py_runtime_info` prefer the builtin PyRuntimeInfo provider when running under Bazel 6. The two providers are (currently) the same, so are mostly interchangable. This satisfies the type check that …

fix(py_runtime): make py_runtime_pair return builtin PyRuntimeInfo under Bazel 6; make python_bootstrap_template public

---

.github/workflows/create_archive_and_notes.sh

The release notes were using the old `pip.parse` api that used the `name` arg and
weren't mentioning the `python_version` arg.

docs: update pip.parse example in release notes

---

BUILD.bazel
CONTRIBUTING.md
docs/sphinx/BUILD.bazel
docs/sphinx/index.md
sphinxdocs/private/sphinx.bzl

This better unifies where docs can be viewed.
Also deletes some mentions of having to generate the docs manually.

docs: include changelog and contributing page in generated docs.

---

gazelle/python/generate.go
gazelle/python/testdata/binary_without_entrypoint/BUILD.in
gazelle/python/testdata/binary_without_entrypoint/BUILD.out
gazelle/python/testdata/binary_without_entrypoint/collided_main.py
gazelle/python/testdata/binary_without_entrypoint/main.py
gazelle/python/testdata/binary_without_entrypoint/main2.py

The `py_binary` targets for main modules should only depend on the modules that it imports, not blindly inheriting from the py_library.

fix: trimming deps in py_binary

---

examples/bzlmod/requirements.in
examples/bzlmod/requirements_lock_3_10.txt
examples/bzlmod/requirements_lock_3_9.txt
examples/bzlmod/requirements_windows_3_10.txt
examples/bzlmod/requirements_windows_3_9.txt
examples/pip_repository_annotations/requirements.in
examples/pip_repository_annotations/requirements.txt
internal_deps.bzl
tools/private/update_deps/update_coverage_deps.py

Before this PR all of our examples are referring to the default PyPI by its
legacy URL. This PR just makes things more consistent by updating URLs to point
to the pypi.org as pypi.python.org does not have any guarantees to be up.
See https://packaging.python.org/en/latest/guides/migrating-to-pypi-org/

doc: switch to pypi.org

---

python/BUILD.bazel
python/private/BUILD.bazel
python/private/auth.bzl
python/repositories.bzl

This is a simple change to make it possible to reuse the vendored
authentication code for easier reuse within the repository.
Split from #1625

refactor: extract auth.bzl out of repositories.bzl

---

python/private/text_util.bzl
tests/private/text_util/BUILD.bazel
tests/private/text_util/render_tests.bzl

Whilst prototyping for #1625, I realized that this feature would be useful
in general when rendering external repositories. This does not include a
CHANGELOG because it is not visible to the users.

internal: support setting visibility when rendering aliases

---

examples/bzlmod/whl_mods/BUILD.bazel
examples/bzlmod/whl_mods/pip_whl_mods_test.py

This refactors the `whl_mods` tests to not rely on the layout of the
repositories, which I found to be needed whilst prototyping on #1625.
Whilst doing this I realized that in general it would be great to
support `Path` instances in the `runfiles` library, but that should be
done next time.

test(bzlmod): refactor tests to not depend on implementation details

---

CHANGELOG.md
examples/bzlmod/whl_mods/pip_whl_mods_test.py
python/pip_install/pip_repository.bzl
python/private/patch_whl.bzl
python/private/repack_whl.py

Before this PR there was a typo, that was actually causing the
patching function to not use the provided patches. With this change
we are finally correctly doing it. After fixing this bug I noticed
that `repository_ctx.patch` results in files with `CRLF` on Windows,
which made me make the `RECORD` mismatch to be a warning rather than
a hard failure to make the CI happy and allow users on Windows to
patch wheels but see a warning if they have a multi-platform bazel
setup.
The `CRLF` endings on Windows issue is fixed in
bazelbuild/bazel@07e0d316a345a3cb2593f98525320590bbc56e30
Related #1631, #1639.

fix(whl_library): actually apply patches and warn if RECORD file patch is needed

---

gazelle/python/generate.go
gazelle/python/parser.go
gazelle/python/testdata/binary_without_entrypoint/BUILD.out
gazelle/python/testdata/binary_without_entrypoint/main.py

When multiple main modules import the same package, the package is only added to one of the main module's deps, this is because the `allDeps` set returned from `parse` removed the duplicates based on the import's name.
This PR have every main module maintains a list of deps it imports to avoid this issue.

fix: missing dependencies of py_binary

---

.github/workflows/mypy.yaml
CHANGELOG.md
python/runfiles/BUILD.bazel
python/runfiles/runfiles.py
tests/runfiles/runfiles_test.py

This change adds mypy types directly to the `rules_python.python.runfiles` library as well as regression testing to CI.

feat(runfiles): Added type hints to `@rules_python//python/runfiles`

---

CHANGELOG.md
python/private/bzlmod/python.bzl

This fixes a bug where, if a module tries to register a non-default toolchain with the
same version as rules_python's default toolchain, an error would occur. This happened
because the earlier (non-default) toolchain caused the later (default) toolchain to
be entirely skipped, and then no default toolchain would be seen. This most affects
intermediary modules that need to register a toolchain, but can't specify a default one.
To fix, just skip creating and registering the duplicate toolchain, but still check
its default-ness to determine if it's the default toolchain.
Fixes https://github.com/bazelbuild/rules_python/issues/1638

fix(bzlmod): allow modules to register the same toolchain as rules_python's default

---

CHANGELOG.md
python/private/common/py_runtime_rule.bzl
tests/py_runtime/pretend_binary
tests/py_runtime/py_runtime_tests.bzl
tests/py_runtime_info_subject.bzl

This PR allows `py_runtime` to accept an executable (e.g. `sh_binary`).
This makes it easier to customize the interpreter binary used, as it allows
intercepting invocation of the interpreter. For example, it can be used to
change how the interpreter searches for dynamic libraries.
Related to https://github.com/bazelbuild/rules_python/issues/1612

feat(py_runtime): Allow `py_runtime` to take an executable target as the interpreter

---

CHANGELOG.md

This is to prepare for the 0.28.0 release.

docs: update changelog for 0.28.0 release

---

CHANGELOG.md
gazelle/README.md
gazelle/python/generate.go
gazelle/python/testdata/binary_without_entrypoint_per_file_generation/BUILD.in
gazelle/python/testdata/binary_without_entrypoint_per_file_generation/BUILD.out
gazelle/python/testdata/binary_without_entrypoint_per_file_generation/README.md
gazelle/python/testdata/binary_without_entrypoint_per_file_generation/WORKSPACE
gazelle/python/testdata/binary_without_entrypoint_per_file_generation/lib.py
gazelle/python/testdata/binary_without_entrypoint_per_file_generation/lib2.py
gazelle/python/testdata/binary_without_entrypoint_per_file_generation/lib_and_main.py
gazelle/python/testdata/binary_without_entrypoint_per_file_generation/main.py
gazelle/python/testdata/binary_without_entrypoint_per_file_generation/main2.py
gazelle/python/testdata/binary_without_entrypoint_per_file_generation/test.yaml

[This previous PR](https://github.com/bazelbuild/rules_python/pull/1584) added the ability to make a `py_binary` target per file if `if __name__ == "__main__"` tokens were found in the file. This works great in the default case, but when `python_generation_mode` is set to `file`, the plugin now attempts to make both a `py_binary` and a `py_library` target for each main file, which results in an error.
This PR modifies the behavior to work properly with per-file target generation, and adds tests for this case.

fix: Fix per-file config interaction with one py_binary per main

---

CHANGELOG.md
WORKSPACE
gazelle/manifest/defs.bzl
gazelle/manifest/generate/generate.go
gazelle/manifest/manifest.go
gazelle/pythonconfig/pythonconfig.go
python/pip_install/pip_repository.bzl
python/private/bzlmod/pip.bzl
python/private/py_console_script_binary.bzl

According to our breaking change policy, we are removing the flag
since in the previous release it has been flipped by default and
enabled to all users in 0.27.0.

chore!: remove incompatible_generate_aliases and related flags

---

CHANGELOG.md
examples/wheel/BUILD.bazel
examples/wheel/wheel_test.py
python/private/py_wheel.bzl
tools/wheelmaker.py

Remove incompatible `whl` packaging flags that had been flipped
in `0.27.0` release.
Also fixes a bug where the the build stamp values (e.g. build username) were lowercased
when they shouldn't be.

chore/fix!: remove incompatible whl packaging flags

---

python/pip_install/tools/wheel_installer/wheel.py
python/pip_install/tools/wheel_installer/wheel_installer_test.py
python/pip_install/tools/wheel_installer/wheel_test.py

Summary:
- refactor: add an OS.interpreter constructor
- refactor: add an Arch.interpreter constructor
- test: add a specializations tests
- refactor: simplify sorting implementation
- refactor: introduce `__str__` to enums
Minor cleanup that will be useful to make this codebase
work for multiple Python versions.
Work towards #1643.

refactor(internal): simplify and cleanup dependency resolution

---

python/private/internal_config_repo.bzl

Respecting it for earlier versions was only done for testing purposes. The implementation requires the `py_internal` object, which only exists on Bazel 7 and higher.
Work towards https://github.com/bazelbuild/rules_python/issues/1069

internal(pystar): Only respect RULES_PYTHON_ENABLE_PYSTAR env var for Bazel 7+

---

CHANGELOG.md
examples/multi_python_versions/tests/my_lib_test.py
python/config_settings/config_settings.bzl
python/private/bzlmod/pip.bzl
python/private/bzlmod/pip_repository.bzl
tests/pip_hub_repository/render_pkg_aliases/render_pkg_aliases_test.bzl

This allows better interoperability between toolchains and the wheels
built by the `whl_library`, as wheels are usually compatible across all
of the python patch versions.

fix(bzlmod): use X.Y select for the hub repo

---

python/private/common/py_executable.bzl

This basically upstreams part of Google-internal patches for building native dep DSOs.
The APIs it uses are only available on Bazel rolling, but the code paths that activate them aren't enabled in rules_python.

internal: update native deps and linkstamp API updates to Bazel rolling APIs

---

python/private/common/BUILD.bazel
python/private/common/attributes.bzl

This upstreams a couple trivial Google patches to make rules_python more compatible with some Google-internal changes.
* Use list(dict) instead of dict.keys(). This is because some bzl files are run through a Python-based testing framework, and dict.keys() can't be concatenated to a list in Python 3.
* Expand visibility to all of rules_python instead of just the python subdirectory. This makes some patches that use internals easier to maintain, but also makes the visiblity more in line with the rest of the project (where `//:__subpackages__` is used for convenience, as it avoids having to change visibility frequently, but still prevents public dependencies).

refactor: broaden visibility and use list() instead of keys()

---

.bazelrc

Bazel 7.0.1 has a bug where lockfiles can cause a bogus error about cyclic dependencies. Removing the lockfile or disabling the lockfiles prevents it from triggering. We aren't
using lockfiles anyways.
This should make CI happy, which uses 7.0.1 in some configurations. Local development
isn't impacted because .bazelversion specifies 7.0.0
See https://github.com/bazelbuild/bazel/issues/20942

test: workaround cyclic dependency bzlmod bug by disabling lockfiles

---

gazelle/README.md

Latex output was shown, should just be escaped

docs: Update gazelle/README.md to fix `package_name` formatting

---

CHANGELOG.md
examples/wheel/BUILD.bazel
examples/wheel/wheel_test.py
python/private/py_wheel.bzl
tools/wheelmaker.py

The `compile_pip_requirements` rule promotes having `requirements.in` files describe python dependencies. This change aims to allow these files to be the source of truth for constraints by allowing the `py_wheel` rule to use them for adding requirements to a wheel. This reduces overhead in needing to maintain two lists of equal information (one as he `.in` and the other as starlark data).

feat(py_wheel): Added `requires_file` and `extra_requires_files` attrs

---

examples/wheel/BUILD.bazel
examples/wheel/wheel_test.py
tools/wheelmaker.py

The `requires_file` and `extra_requires_files` attributes added by https://github.com/bazelbuild/rules_python/pull/1710 break wheels by leaving trailing `;` and currently do not support `requirements.in` files with comments following a constraint on the same line. This PR fixes these issues.

fix(py_wheel): Fix parsing errors with `requires_file` attribute.

---

python/pip_install/pip_repository.bzl

Wheel installer failures can be very confusing because they're run during the repository phase where the isn't a great understanding of what they're doing. This makes the error message for failures provide details to help understand exactly what it was up to.

refactor: provide more detailed error message when wheel installer fails

---

CHANGELOG.md
WORKSPACE
python/versions.bzl

Updates versions:
* 3.11.6 -> 3.11.7
* 3.12.0  -> 3.12.1
Adds versions: 3.11.7, 3.12.1

chore: add python 3.11.7, 3.12.1 toolchain

---

CHANGELOG.md
python/private/common/py_executable.bzl
python/py_runtime_info.bzl
tests/base_rules/py_executable_base_tests.bzl

This fixes the bug where the PyRuntimeInfo symbol rules_python exported wasn't matching the provider identity that `py_binary` actually provided.
The basic problem was, when pystar is disabled:
* PyRuntimeInfo is the rules_python defined provider
* py_binary is `native.py_binary`, which provides only the builtin PyRuntimeInfo provider.
Thus, when users loaded the rules_python PyRuntimeInfo symbol, it was referring to a provider that the underlying py_binary didn't actually provide. Pystar is always disabled on Bazel 6.4,
and enabling it for Bazel 7 will happen eminently.
This typically showed up when users had a custom rule with an attribute definition that used the rules_python PyRuntimeInfo.
To fix, only use the rules_python define PyRuntimeInfo if pystar is enabled. This ensures the …

fix(PyRuntimeInfo): use builtin PyRuntimeInfo unless pystar is enabled.

---

tests/cc/current_py_cc_libs/BUILD.bazel
tests/cc/current_py_cc_libs/python_libs_linking_test.cc

This is just a basic to to ensure the
`@rules_python//python/cc:current_py_cc_libs` target is making the Python C libraries available; that the compiler and linker are both happy enough to resolve symbols.
The test program itself isn't actually runnable, as that requires more configuration than I can figure out in telling Python where its embedded runtime information is.
Fow now, the test is restricted to Linux. The Mac and Windows CC building isn't happy with it, but I'm out of my depth about how to make those happy.
Work towards https://github.com/bazelbuild/rules_python/issues/824

tests(cclibs): Basic test that the `current_py_cc_libs` target works

---

CHANGELOG.md

* Updates link and header
* Adds a missing link to a prior release
* Adds a mention of `:current_py_cc_libs` to the features added

chore: Update changelog for 0.30.0 release

---

.bcr/presubmit.yml

BCR now requires the presubmit configs to specify the Bazel versions to run tests with. Without this, the BCR checks fail and we can't do releases to BCR.

tests(bcr): Set Bazel version in BCR presubmit config.

---

CHANGELOG.md

* Create 0.31.0 section
* Move pystar note out of 0.30.0 section and into 0.31.0

chore: Update changelog for 0.31.0

---

examples/bzlmod/libs/my_lib/__init__.py

When adding a whl-only hub that gets selected for a particular
platform only, this check needed to be adjusted (as seen in #1744).

test(bzlmod): make the check for hub repo naming less strict

---

docs/sphinx/getting-started.md

The `python-build-standalone.readthedocs.io` site seems to be dead.

docs(getting-started): fix link to python-build-standalone quirks

---

python/private/repo_utils.bzl

Fixes "Error in format: Missing argument 'path'" error and correctly templates the binary name and `PATH`.
```
(17:54:57) ERROR: /Users/jesses/work/canva/WORKSPACE:120:17: fetching whl_library rule //external:pypi_jsmin: Traceback (most recent call last):
File "/private/var/tmp/_bazel_jesses/06c990151bb0d0bcaaf7ea85520191a3/external/rules_python/python/pip_install/pip_repository.bzl", line 783, column 59, in _whl_library_impl
environment = _create_repository_execution_environment(rctx, python_interpreter)
File "/private/var/tmp/_bazel_jesses/06c990151bb0d0bcaaf7ea85520191a3/external/rules_python/python/pip_install/pip_repository.bzl", line 257, column 47, in _create_repository_execution_environment
cppflags.extend(_get_xcode_location_cflags(rctx))
File …
```

fix(internal): correctly template error message in repository rules
